Repository kythe/kythe, pull requests merged in 2018-10, with the labels that each got.

#3087 Implement StandardJavaFileManager#setLocationsFromPaths
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
Labels: cla: yes, extraction, java

#3090 Support upcoming Bazel 0.18.0 release
  WORKSPACE
Labels: build, cla: yes

#3092 Update setup_release.sh to build release archive
  kythe/release/BUILD
  kythe/release/setup_release.sh
Labels: cla: yes, release

#3091 Decouple verifier from LLVM dependency by splitting //kythe/cxx/commo…
  kythe/cxx/common/BUILD
  kythe/cxx/common/kythe_uri.cc
  kythe/cxx/common/kythe_uri.h
  kythe/cxx/common/path_utils_test.cc
  kythe/cxx/doc/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/verifier/BUILD
Labels: cla: yes

#3093 Migrate javac_extractor to use ambient langtools
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/README.md
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/release/BUILD
  kythe/release/README.md
  kythe/release/release_test.sh
  kythe/web/site/examples.md
  third_party/javac/BUILD
Labels: cla: yes

#3094 Move workspace bazelrc to new location
  .bazelrc
  tools/bazel.rc
Labels: build, cla: yes

#3100 Don't crash if we try to write the same file to a kzip more than once
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#3097 First step towards getting java8 workaround for maven.
  kythe/go/extractors/config/base/mvn/mvn.go
  kythe/go/extractors/config/base/testdata/expected_mvn_config.Dockerfile
  kythe/go/extractors/config/base/testdata/mvn_config.json
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile
Labels: cla: yes

#3102 Group overloads together
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3103 Dep on kythe_uri target
  kythe/cxx/doc/BUILD
Labels: cla: yes

#3098 typescript: index default values in functions
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/function.ts
Labels: buildbot, cla: yes

#3104 Handle adding duplicate files to kzip archives
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
  kythe/cxx/common/kzip_writer_test.cc
Labels: cla: yes

#3105 Open common Java libraries to //visibility:public
  kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/proto/BUILD
Labels: cla: yes

#3106 Begin migrating external repository definitions to importable WORKSPACE function
  WORKSPACE
  external.bzl
Labels: cla: yes

#3107 Update protobuf to new release and resolve a TODO
  external.bzl
Labels: cla: yes

#3108 Migrate C++ dependencies to external.bzl
  WORKSPACE
  external.bzl
  third_party/libzip.BUILD
Labels: cla: yes

#3111 Migrate rest of Bazel dependencies to external.bzl
  WORKSPACE
  external.bzl
  kythe/go/util/cmdutil/BUILD
  setup.bzl
  third_party/googlelog.BUILD
  tools/build_rules/shims.bzl
Labels: cla: yes

#3112 Update Bazel rules_go to 0.15.4
  external.bzl
  setup.bzl
Labels: cla: yes

#3113 Move the Kythe default json pb any types
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/java/com/google/devtools/kythe/util/JsonUtil.java
Labels: cla: yes

#3114 Remove unused deps
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/jvm/BUILD
Labels: cla: yes

#3115 Update kythe/extractors/bazel/extract.sh so it works with kzips
  kythe/cxx/extractor/BUILD
  kythe/extractors/bazel/extract.sh
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
Labels: cla: yes

#3116 Use kzip format in java_verifier_test rule
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_edges.kythe_verifier.txt
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3117 Use kzip format in jvm_verifier_test rule
  kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/JarExtractor.java
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3118 Update viewindex documentation to include .kzip support
  kythe/go/platform/tools/viewindex/viewindex.go
Labels: cla: yes

#3119 Use kzip format in cc_verifier_test rule
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/indexing/frontend.cc
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#3121 Use kzip format in cc_bazel_extractor_test rule
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/indexing/frontend.cc
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3122 Migrate extract_java_aspect to output kzip files
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
Labels: cla: yes

#3123 Update ruby deps
  kythe/web/site/Gemfile.lock
  kythe/web/site/sync_docs.sh
Labels: cla: yes

#3124 Fix copyright author
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipException.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipReader.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/TestDataUtil.java
Labels: cla: yes

#3127 Add diagnostic node type for cxx code
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
Labels: cla: yes

#3128 Remove no-op std::move
  kythe/cxx/common/indexing/frontend.cc
Labels: cla: yes

#3129 Use declare_file instead of new_file
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3132 Java indexer: guard against null inferred lambda types
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#3131 Enable SSL redirects for kythe.io
  kythe/release/appengine/default/app.yaml
Labels: cla: yes

#3133 Replace or deprecate mentions of kindex files with kzip
  kythe/docs/kythe-index-pack.txt
  kythe/docs/schema/writing-an-indexer.txt
Labels: cla: yes

#3134 Add documentation to verifier_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3136 Prefer String.getBytes(Charset)
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
Labels: cla: yes

#3135 Java indexer: allow for analysis of multiple compilations
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
Labels: cla: yes

#3138 Update to LLVM r344140
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
  kythe/cxx/indexer/cxx/KytheVFS.h
  kythe/cxx/indexer/cxx/marked_source.cc
  tools/modules/versions.sh
Labels: cla: yes

#3139 Java indexer: do not include Symbol modifiers in hashes
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
Labels: cla: yes, indexing, java

#3140 Add check for asciidoctor gem
  kythe/web/site/Gemfile.lock
  kythe/web/site/sync_docs.sh
Labels: cla: yes

#3141 Fix check for asciidoctor gem
  kythe/web/site/sync_docs.sh
Labels: cla: yes

#3142 Shim binary for testing gcp cloud build setup.
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/helloworld/BUILD
  kythe/go/extractors/gcp/helloworld/cloudbuild.yaml
  kythe/go/extractors/gcp/helloworld/helloworld.go
Labels: cla: yes

#3143 Fix wording
  kythe/go/extractors/gcp/README.md
Labels: cla: yes

#3144 ClassFileIndexer: support indexing multiple compilations in kzip files
  kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
Labels: cla: yes

#3145 Java indexer: share abs node corpus with child
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Generics.java
Labels: cla: yes

#3148 fix: don't CHECK-fail in ProtoLibrarySupport
  kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
Labels: cla: yes

#3153 chore(platform): deprecate Go/Java indexpack libraries
  kythe/go/platform/indexpack/BUILD
  kythe/java/com/google/devtools/kythe/platform/indexpack/BUILD
Labels: cla: yes

#3154 build: update to latest Flogger version
  external.bzl
Labels: cla: yes

#3155 Point kythe java extractor artifacts at new gcr.io/kythe-public.
  kythe/go/extractors/config/base/gradle/gradle.go
  kythe/go/extractors/config/base/mvn/mvn.go
  kythe/go/extractors/config/base/testdata/expected_gradle_config.Dockerfile
  kythe/go/extractors/config/base/testdata/expected_mvn2_config.Dockerfile
  kythe/go/extractors/config/base/testdata/expected_mvn_config.Dockerfile
  kythe/go/extractors/config/base/testdata/gradle_config.json
  kythe/go/extractors/config/base/testdata/mvn2_config.json
  kythe/go/extractors/config/base/testdata/mvn_config.json
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
Labels: cla: yes

#3161 Another rename of for javac9-tools.jar
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile
Labels: cla: yes

#3160 Moves build preprocessing libraries into a binary
  kythe/go/extractors/config/constants/BUILD
  kythe/go/extractors/config/constants/constants.go
  kythe/go/extractors/config/preprocessor/BUILD
  kythe/go/extractors/config/preprocessor/README.md
  kythe/go/extractors/config/preprocessor/modifier/BUILD
  kythe/go/extractors/config/preprocessor/modifier/build_gradle_modifier.go
  kythe/go/extractors/config/preprocessor/modifier/modifier_test.go
  kythe/go/extractors/config/preprocessor/modifier/pom_xml_modifier.go
  kythe/go/extractors/config/preprocessor/modifier/testdata/modified-build.gradle
  kythe/go/extractors/config/preprocessor/modifier/testdata/modified-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/other-build.gradle
  kythe/go/extractors/config/preprocessor/modifier/testdata/other-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/plain-build.gradle
  kythe/go/extractors/config/preprocessor/modifier/testdata/plain-pom.xml
  kythe/go/extractors/config/preprocessor/preprocessor.go
  kythe/go/extractors/config/runextractor/gradlecmd/BUILD
  kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
  kythe/go/extractors/config/runextractor/mavencmd/BUILD
  kythe/go/extractors/config/runextractor/mavencmd/mavencmd.go
  kythe/go/extractors/config/runextractor/mavencmd/pom_xml_modifier_test.go
Labels: cla: yes, extraction, gradle, maven

#3165 build(buildbot): upgrade Bazel minimum to 0.18.0
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: build, cla: yes

#3167 Fix lint errors
  kythe/go/extractors/config/constants/constants.go
Labels: cla: yes

#3159 build: satisfy Bazel 0.18.0 `--all_incompatible_changes`
  WORKSPACE
  kythe/go/indexer/testdata/go_indexer_test.bzl
  kythe/proto/go.bzl
  third_party/libzip.BUILD
  tools/build_rules/expand_template.bzl
  tools/build_rules/shims.bzl
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
  tools/cpp/clang_configure.bzl
Labels: cla: yes

#3168 fix: Set default value for dropping fwd decl docs
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
Labels: cla: yes

#3169 Add a build-preprocessor docker image for config/preprocessor.
  kythe/go/extractors/config/preprocessor/BUILD
  kythe/go/extractors/config/preprocessor/Dockerfile
  kythe/go/extractors/config/preprocessor/preprocessor.go
Labels: cla: yes, extraction, maven

#3170 build(bazel): support upcoming 0.19.0 release
  .bazelrc
  WORKSPACE
Labels: cla: yes

#3171 build(bazel): update Go rules to 0.16.0
  WORKSPACE
  external.bzl
  go.mod
  go.sum
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/extraction_config_go_proto/extraction_config.pb.go
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
  setup.bzl
Labels: cla: yes

#3172 Add a cloudbuild.yaml for maven extraction on Cloud Build
  kythe/go/extractors/config/preprocessor/README.md
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/mvnpoc/cloudbuild.yaml
Labels: cla: yes, extraction, gradle, maven

#3166 fix: recover file VNames using file content; reorder singleton checking
  external.bzl
  kythe/cxx/common/BUILD
  kythe/cxx/common/scope_guard.h
  kythe/cxx/extractor/testdata/test_stdin_names.sh
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/indexed_parent_map.cc
  kythe/cxx/indexer/cxx/testdata/test_index_pack.sh
  kythe/cxx/indexer/cxx/testdata/test_kindex.sh
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/assertion_ast.h
  kythe/cxx/verifier/assertions.cc
  kythe/cxx/verifier/assertions.h
  kythe/cxx/verifier/testdata/test_singleton.sh
  kythe/cxx/verifier/testdata/test_verifier_regex.sh
  kythe/cxx/verifier/verifier.cc
  kythe/cxx/verifier/verifier.h
  kythe/cxx/verifier/verifier_main.cc
  kythe/docs/schema/example-go.sh
  kythe/go/indexer/testdata/basic/anchors.go
  kythe/go/indexer/testdata/basic/funcall.go
  kythe/go/indexer/testdata/basic/functions.go
  kythe/go/indexer/testdata/basic/imports.go
  kythe/go/indexer/testdata/basic/structref.go
  kythe/go/indexer/testdata/code/funcdecl.go
  kythe/go/indexer/testdata/meta.go
  kythe/go/indexer/testdata/unsafe.go
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
  kythe/release/release_test.sh
  kythe/typescript/testdata/class.ts
  kythe/typescript/testdata/computed_property.ts
  kythe/typescript/testdata/declaration_import.ts
  kythe/typescript/testdata/declare_module.d.ts
  kythe/typescript/testdata/default_export.ts
  kythe/typescript/testdata/default_import.ts
  kythe/typescript/testdata/expression.ts
  kythe/typescript/testdata/fake-genfiles/testdata/alt_module.ts
  kythe/typescript/testdata/function.ts
  kythe/typescript/testdata/generic.ts
  kythe/typescript/testdata/index_importer.ts
  kythe/typescript/testdata/index_module/index.ts
  kythe/typescript/testdata/reexport_importer.ts
  kythe/typescript/testdata/reexporter.ts
  kythe/typescript/testdata/root_dirs.ts
  kythe/typescript/testdata/type_alias.ts
Labels: cla: yes

#3175 style: clang-format .proto files
  kythe/proto/analysis_service.proto
  kythe/proto/explore.proto
  kythe/proto/extraction_config.proto
  kythe/proto/go.proto
  kythe/proto/graph.proto
  kythe/proto/identifier.proto
  kythe/proto/internal.proto
  kythe/proto/link.proto
  kythe/proto/pipeline.proto
  kythe/proto/schema.proto
  kythe/proto/serving.proto
  kythe/proto/status_service.proto
  kythe/proto/storage.proto
  kythe/proto/xref.proto
  kythe/proto/xref_serving.proto
Labels: cla: yes

#3176 style: google-java-format .java files
  kythe/java/com/google/devtools/kythe/analyzers/base/IndexerConfig.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/shared/ExtractorUtils.java
  kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitBasedJavaFileStore.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/BlockAnonymousSignatureGenerator.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipReader.java
Labels: cla: yes

#3177 style: clang-format .h/.cc files
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/KytheVFS.cc
Labels: cla: yes

#3174 style: add standard scripts for git hooks
  .commitlintrc.js
  kythe/web/site/contributing.md
  tools/arc/linter.sh
  tools/git/commit-msg.sh
  tools/git/pre-commit.sh
  tools/git/setup_hooks.sh
Labels: cla: yes

#3181 fix: mark jvm_nodes_tests as a large test
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
Labels: cla: yes

#3183 docs: Add debugging steps to cloud build examples.
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/examples/BUILD
  kythe/go/extractors/gcp/examples/helloworld.go
  kythe/go/extractors/gcp/examples/helloworld.yaml
  kythe/go/extractors/gcp/examples/mvn.yaml
Labels: cla: yes

#3182 build: update Flogger and google_bazel_common deps
  external.bzl
Labels: cla: yes

#3179 style: fix unused-lambda-capture warning
  kythe/cxx/common/index_pack_test.cc
Labels: cla: yes

#3180 style: remove unused variable
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
Labels: cla: yes

#3184 fix: Adding error message to git hook when commitlint not installed.
  tools/git/commit-msg.sh
Labels: cla: yes

#3186 fix: remove runextractor from javac-extractor-artifacts
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile
Labels: cla: yes, extraction

#3187 fix: do cloud build initial setup steps in parallel
  kythe/go/extractors/gcp/examples/gradle.yaml
  kythe/go/extractors/gcp/examples/mvn.yaml
Labels: cla: yes, extraction, gradle, maven

#3188 fix(beam): ensure disksort GBK finishes downstream node
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
Labels: cla: yes

#3189 feat: add test binary for cloud build REST API permissions
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/examples/helloworld/BUILD
  kythe/go/extractors/gcp/examples/helloworld/helloworld.go
  kythe/go/extractors/gcp/examples/helloworld/helloworld.yaml
  kythe/go/extractors/gcp/examples/restcheck/BUILD
  kythe/go/extractors/gcp/examples/restcheck/rest_auth_check.go
Labels: cla: yes

#3190 feat: add columnar encoding for edges api
  kythe/docs/rfc/2909.md
  kythe/go/serving/api/api.go
  kythe/go/serving/graph/BUILD
  kythe/go/serving/graph/columnar.go
  kythe/go/serving/graph/columnar/BUILD
  kythe/go/serving/graph/columnar/columnar_encoding.go
  kythe/go/serving/graph/columnar/columnar_test.go
  kythe/go/serving/graph/columnar_test.go
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/encoding.go
  kythe/go/serving/tools/http_server/http_server.go
  kythe/go/serving/tools/write_tables/write_tables.go
  kythe/go/serving/xrefs/columnar.go
  kythe/go/storage/inmemory/inmemory.go
  kythe/go/util/keys/keys.go
  kythe/go/util/schema/nodes/nodes.go
  kythe/proto/BUILD
  kythe/proto/graph_serving.proto
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
Labels: cla: yes, post-processing, storage

#3191 feat(post-processing): add related nodes to columnar cross-references
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
Labels: cla: yes, post-processing

#3192 feat(beam): encode scope name into GBK files
  kythe/go/util/disksort/disksort.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
Labels: cla: yes, post-processing

#3194 build(remote): update Bazel remote toolchains to 0.18.0
  .bazelrc
  WORKSPACE
  tools/arc/linter.sh
Labels: cla: yes

#3193 build(buildbot): upgrade Bazel to 0.19.0
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: build, cla: yes

#3195 build: update Apache Beam to commit cdd3458
  external.bzl
  go.mod
  go.sum
Labels: cla: yes

#3198 fix(post-processing): remove anchors from edge/xref relations
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/beamio/leveldb.go
Labels: cla: yes

#3199 fix(java_indexer): do not close System.out after first analysis
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
Labels: cla: yes

#3200 build: move vnames configuration to external target
  WORKSPACE
  external.bzl
  kythe/cxx/extractor/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3201 feat: limit disksort memory by custom Size method
  kythe/go/util/disksort/disksort.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
Labels: cla: yes

#3202 refactor: share common proto comparison logic
  kythe/go/serving/graph/BUILD
  kythe/go/serving/graph/columnar/BUILD
  kythe/go/serving/graph/columnar/columnar_test.go
  kythe/go/serving/graph/columnar_test.go
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/beamio/BUILD
  kythe/go/serving/pipeline/beamio/entries_test.go
  kythe/go/serving/pipeline/nodes/BUILD
  kythe/go/serving/xrefs/BUILD
  kythe/go/serving/xrefs/columnar/BUILD
  kythe/go/serving/xrefs/columnar/columnar_test.go
  kythe/go/serving/xrefs/columnar_test.go
  kythe/go/util/compare/BUILD
  kythe/go/util/compare/compare.go
  kythe/go/util/keys/BUILD
  kythe/go/util/keys/keys_test.go
  kythe/go/util/riegeli/BUILD
  kythe/go/util/riegeli/golden_test.go
  kythe/go/util/riegeli/riegeli_test.go
Labels: cla: yes

#3203 retain a reference to zip source on validation error
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_reader.h
  kythe/cxx/common/kzip_reader_test.cc
Labels: cla: yes

#3204 feat(xrefs): handle columnar decl/def CrossReferences
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/columnar_test.go
Labels: cla: yes

#3205 Update to LLVM/clang 345691
  kythe/cxx/extractor/cxx_extractor.cc
  tools/modules/versions.sh
Labels: cla: yes

#3207 refactor: make beamio.EncodeKeyValues a reusable Beam transform
  kythe/go/serving/pipeline/beamio/BUILD
  kythe/go/serving/pipeline/beamio/beamio.go
  kythe/go/serving/pipeline/beamio/leveldb.go
Labels: cla: yes
