Repository kythe/kythe, pull requests merged in 2018-12, with the labels that each got.

#3287 build: fix incompatabilities with upcoming Bazel 0.21 release
  external.bzl
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  setup.bzl
  third_party/protobuf.BUILD
Labels: cla: yes

#3290 fix(gotool_extractor): when no global corpus is given, use package's corpus for each file
  kythe/docs/schema/schema.txt
  kythe/go/extractors/golang/golang.go
  kythe/go/indexer/cmd/go_example/go_example.go
  kythe/go/indexer/testdata/basic/filenode.go
  kythe/go/indexer/testdata/basic/packageinit.go
  kythe/go/indexer/testdata/basic/packages.go
Labels: cla: yes, extraction, go

#3291 Remove index pack support from cxx extractor
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/extractor/testdata/BUILD
  kythe/cxx/extractor/testdata/test_index_pack.sh
  kythe/cxx/extractor/testdata/test_stdin_names.sh
Labels: cla: yes

#3294 fix(java_indexer): ensure static import refs are static
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Imports.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/StaticMethods.java
Labels: cla: yes

#3293 feat: support reading kzip files in kindex_tool
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/kindex_tool_main.cc
  third_party/protobuf.BUILD
Labels: cla: yes

#3295 fix(sh_test): use "set -e" instead of adding "-e" to shebang
  kythe/cxx/common/testdata/net_client_test_runner.sh
  kythe/cxx/common/testdata/start_http_service.sh
  kythe/cxx/extractor/testdata/test_alternate_platform.sh
  kythe/cxx/extractor/testdata/test_extract_transcript.sh
  kythe/cxx/extractor/testdata/test_has_include.sh
  kythe/cxx/extractor/testdata/test_indirect_has_include.sh
  kythe/cxx/extractor/testdata/test_kzip.sh
  kythe/cxx/extractor/testdata/test_main_source_file_env_dep.sh
  kythe/cxx/extractor/testdata/test_main_source_file_no_env_dep.sh
  kythe/cxx/extractor/testdata/test_metadata.sh
  kythe/cxx/extractor/testdata/test_modules.sh
  kythe/cxx/extractor/testdata/test_root_directory.sh
  kythe/cxx/extractor/testdata/test_stdin_names.sh
  kythe/cxx/indexer/cxx/testdata/test_kindex.sh
  kythe/cxx/tools/fyi/testdata/basic_test.sh
  kythe/cxx/tools/fyi/testdata/hopeless_test.sh
  kythe/cxx/tools/fyi/testdata/nothing_test.sh
  kythe/cxx/tools/fyi/testdata/test_case.sh
  kythe/cxx/tools/testdata/test_claim_tool_index_pack.sh
  kythe/cxx/tools/testdata/test_claim_tool_kindex.sh
  kythe/data/test_filevnames.sh
  kythe/go/platform/tools/indexpack_test.sh
  kythe/go/serving/tools/testdata/kwazthis_test.sh
  kythe/go/serving/tools/testdata/write_tables_test.sh
  kythe/javatests/com/google/devtools/kythe/analyzers/java/indexer_empty_cu_test.sh
  kythe/javatests/com/google/devtools/kythe/analyzers/java/indexer_source_root_test.sh
  kythe/javatests/com/google/devtools/kythe/analyzers/java/indexer_test.sh
  kythe/release/package_release.sh
  kythe/release/release_test.sh
  kythe/rust/indexer/testdata/one_case.sh
  tools/build_rules/rust/run_cargo.sh
  tools/modules/check.sh
  tools/modules/versions.sh
Labels: cla: yes

#3296 chore: mark a few golang tools/libs as deprecated in favor of kzip
  kythe/go/platform/kindex/BUILD
  kythe/go/platform/tools/indexpack/BUILD
  kythe/go/platform/tools/kindex_file_generator/BUILD
Labels: cla: yes

#3298 refactor: write kzip always for JavaStandalone extractor
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
  kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
  kythe/release/release_test.sh
Labels: cla: yes

#3297 refactor: remove deprecated kindex from cxx extractor
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/extractor/testdata/test_alternate_platform.sh
  kythe/cxx/extractor/testdata/test_extract_transcript.sh
  kythe/cxx/extractor/testdata/test_has_include.sh
  kythe/cxx/extractor/testdata/test_indirect_has_include.sh
  kythe/cxx/extractor/testdata/test_main_source_file_env_dep.sh
  kythe/cxx/extractor/testdata/test_main_source_file_no_env_dep.sh
  kythe/cxx/extractor/testdata/test_metadata.sh
  kythe/cxx/extractor/testdata/test_modules.sh
  kythe/cxx/extractor/testdata/test_root_directory.sh
  kythe/go/extractors/config/runextractor/compdb/BUILD
  kythe/go/extractors/config/runextractor/compdb/compdb_test.go
Labels: cla: yes

#3303 feat(build_details): add a build_config field to BuildDetails proto
  kythe/data/schema_index.textproto
  kythe/docs/schema/schema.txt
  kythe/go/util/schema/indexdata.go
  kythe/proto/buildinfo.proto
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
Labels: cla: yes

#3289 fix: add -fsanitize= to the unsupported args list
  kythe/cxx/extractor/CommandLineUtils.cc
Labels: buildbot, cla: yes

#3305 fix(java_indexer): ensure static import refs are accessible
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Imports.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/StaticMethods.java
Labels: cla: yes, indexing, java

#3311 feat(objc_indexer): marked source for category methods
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/objc/categories/marked_category.m
Labels: cla: yes

#3315 build(schema): include generated images in document zip
  kythe/docs/asciidoc.bzl
Labels: cla: yes

#3314 docs(macos): add macOS installation instructions
  kythe/web/site/getting-started.md
  kythe/web/site/install-macos.md
Labels: buildbot, cla: yes

#3316 fix: The link to the new macos docs was broken
  kythe/web/site/getting-started-macos.md
  kythe/web/site/getting-started.md
Labels: cla: yes

#3308 fix: change tools/modules/update.sh to use an archive instead of clone
  kythe/web/site/getting-started.md
  tools/modules/update.sh
Labels: cla: yes

#3318 feat: add docker image with a kythe install for use in google cloud build
  kythe/examples/bazel/BUILD
  kythe/go/extractors/gcp/bazel/BUILD
  kythe/go/extractors/gcp/bazel/Dockerfile
Labels: cla: yes

#3319 chore: run clang-format
  kythe/cxx/indexer/cxx/marked_source.cc
Labels: cla: yes

#3320 feat(objc_indexer): support marked source for @property
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/objc/marked_property.m
Labels: cla: yes

#3321 fix(cxx): add visibility for :status library for use in proto indexer
  kythe/cxx/common/BUILD
Labels: cla: yes

#3323 fix shell lint warnings in tools/modules/update.sh
  tools/modules/update.sh
Labels: cla: yes

#3325 fix: include wget in the list of packages to install on macOS
  kythe/web/site/getting-started-macos.md
Labels: buildbot, cla: yes

#3317 feat(java_indexer): emit implicit anchors for default constructors
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/SourceText.java
  kythe/java/com/google/devtools/kythe/util/Span.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java
Labels: cla: yes, indexing, java

#3326 fix: check for sentinel versions of llvm/clang in check.sh
  tools/modules/check.sh
Labels: cla: yes

#3329 ci(buildbot): add lang-proto to Buildbot ChangeSources
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3333 build: support version Bazel 0.21.0
  .bazelrc
  WORKSPACE
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: build, cla: yes

#3335 build(protobuf): update protobuf to latest 3.7.x candidate
  external.bzl
  third_party/protobuf.BUILD
Labels: cla: yes

#3332 feat: add example for extracting multiple mavens out of guava in gcb
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/config/kziptool/BUILD
  kythe/go/extractors/gcp/config/kziptool/Dockerfile
  kythe/go/extractors/gcp/examples/guava-mvn.yaml
Labels: cla: yes

#3330 fix(java_common): allow analyzers to throw InterruptedExceptions
  kythe/java/com/google/devtools/kythe/analyzers/base/AbstractCompilationAnalyzer.java
Labels: buildbot, cla: yes

#3336 feat: add a simple kzip validator
  kythe/go/extractors/validation/BUILD
  kythe/go/extractors/validation/validation.go
  kythe/go/platform/tools/kzip_validator/BUILD
  kythe/go/platform/tools/kzip_validator/kzip_validator.go
Labels: cla: yes

#3337 build(go_rules): update to 0.16.5
  setup.bzl
Labels: build, cla: yes

#3338 feat(gotool_extractor): use Go tool to extract package data
  kythe/docs/schema/example-go.sh
  kythe/go/extractors/cmd/gotool/gotool.go
  kythe/go/extractors/golang/BUILD
  kythe/go/extractors/golang/golang.go
  kythe/go/extractors/golang/packages.go
  kythe/go/indexer/cmd/go_example/BUILD
  kythe/go/indexer/cmd/go_example/go_example.go
  kythe/go/indexer/testdata/go_indexer_test.bzl
Labels: cla: yes

#3340 feat(gotool_extractor): add Docker image for Go extractor
  kythe/go/extractors/cmd/gotool/BUILD
  kythe/go/extractors/cmd/gotool/Dockerfile
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
  kythe/go/extractors/cmd/gotool/gotool.go
  kythe/go/extractors/golang/packages.go
Labels: cla: yes, extraction, go

#3342 fix(gotool_extractor): pass-through full build context
  kythe/go/extractors/golang/packages.go
Labels: cla: yes, extraction, go

#3341 fix: extract guava tests as well
  kythe/go/extractors/gcp/examples/guava-mvn.yaml
Labels: cla: yes

#3343 feat: add ability for kzip_validator to validate based on -repo_url
  external.bzl
  go.mod
  go.sum
  kythe/go/platform/tools/kzip_validator/BUILD
  kythe/go/platform/tools/kzip_validator/kzip_validator.go
  third_party/go/BUILD
  third_party/go/archiver.BUILD
  third_party/go/compress.BUILD
  third_party/go/lz4.BUILD
  third_party/go/rardecode.BUILD
  third_party/go/xi2xz.BUILD
  third_party/go/xz.BUILD
Labels: cla: yes
