Repository kythe/kythe, pull requests merged in 2018-11, with the labels that each got.

#3209 fix: modernize Bazel end-to-end example scripts
  kythe/examples/bazel/BUILD
  kythe/examples/bazel/BUILD.src.data
  kythe/examples/bazel/BUILD.third_party
  kythe/examples/bazel/bazel.WORKSPACE
  kythe/examples/bazel/kythe-index.sh
  kythe/examples/bazel/kythe_config.json
  kythe/examples/bazel/setup-bazel-repo.sh
Labels: cla: yes

#3211 feat: add Seek method to keyvalue.Iterator interface
  kythe/go/storage/inmemory/inmemory.go
  kythe/go/storage/inmemory/inmemory_test.go
  kythe/go/storage/keyvalue/keyvalue.go
  kythe/go/storage/leveldb/leveldb.go
Labels: cla: yes

#3213 fix: resolve clang warnings
  kythe/cxx/verifier/verifier.cc
  kythe/cxx/verifier/verifier_unit_test.cc
  third_party/jq.BUILD
Labels: cla: yes

#3212 ci(buildbot): allow up to 3 builds to run in parallel
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3206 feat: add proto for configuring kythe extraction on a repo
  kythe/proto/BUILD
  kythe/proto/repo.proto
  kythe/proto/repo_go_proto/repo.pb.go
Labels: cla: yes

#3214 fix(jvm_indexer): prepare code using ASM for Java 11
  external.bzl
  kythe/java/com/google/devtools/kythe/analyzers/jvm/KytheClassVisitor.java
Labels: cla: yes

#3215 feat(post-processing): allow `write_tables` to compact output LevelDB
  kythe/go/serving/tools/write_tables/write_tables.go
  kythe/go/storage/leveldb/leveldb.go
Labels: cla: yes

#3217 build: update Bazel rules_go to 0.16.1
  external.bzl
  setup.bzl
Labels: cla: yes

#3218 chore: find . -type f -exec sed 's|google/kythe|kythe/kythe|g' -i {} \;
  CONTRIBUTING.md
  README.adoc
  RELEASES.md
  kythe/cxx/extractor/README.md
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/docs/kythe-configurable-extraction.txt
  kythe/docs/kythe-verifier.txt
  kythe/docs/rfc/2909.md
  kythe/docs/rfc/2966.md
  kythe/docs/schema-overview.txt
  kythe/docs/schema/indexing-protobuf.txt
  kythe/docs/schema/marked-source.txt
  kythe/docs/schema/writing-an-indexer.txt
  kythe/examples/bazel/bazel.WORKSPACE
  kythe/go/extractors/cmd/bazel/govnames_test.json
  kythe/go/extractors/config/extractor.go
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/govname/govname_test.go
  kythe/go/platform/tools/extraction/README.md
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/README.md
  kythe/proto/driver.proto
  kythe/proto/graph_serving.proto
  kythe/proto/xref_serving.proto
  kythe/release/README.md
  kythe/release/appengine/buildbot/cache-llvm.sh
  kythe/release/appengine/buildbot/master/master.cfg.template
  kythe/release/appengine/default/main.go
  kythe/release/setup_release.sh
  kythe/rust/cargo-kythe/Cargo.toml
  kythe/rust/cargo-kythe/README.md
  kythe/rust/indexer/Cargo.toml
  kythe/typescript/README.md
  kythe/web/site/_data/development.yml
  kythe/web/site/examples.md
  kythe/web/site/getting-started.md
Labels: cla: yes

#3221 feat(sample-web-ui): display callers in xrefs panel
  kythe/web/ui/src-cljs/ui/service.cljs
  kythe/web/ui/src-cljs/ui/xrefs.cljs
Labels: cla: yes

#3220 feat(post-processing): emit columnar callers
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: cla: yes, post-processing

#3223 feat(post-processing): add support for Riegeli input files
  kythe/go/serving/pipeline/beamio/BUILD
  kythe/go/serving/pipeline/beamio/entries.go
  kythe/go/serving/pipeline/beamio/entries_test.go
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: cla: yes, post-processing

#3224 build: update Apache Beam to f1a4647
  external.bzl
  go.mod
  go.sum
Labels: cla: yes

#3225 docs(examples): modernize website examples.md
  kythe/extractors/bazel/extract.sh
  kythe/release/BUILD
  kythe/release/Dockerfile
  kythe/release/base/Dockerfile
  kythe/release/kythe.sh
  kythe/web/site/examples.md
Labels: cla: yes, documentation

#3227 feat(sample-web-ui): add link to related node definitions
  kythe/web/ui/src-cljs/ui/service.cljs
  kythe/web/ui/src-cljs/ui/xrefs.cljs
Labels: cla: yes

#3229 fix: specify revision to diff against when using arc
  tools/git/pre-commit.sh
Labels: cla: yes

#3230 fix: truncate USR SHA1, not USR; kUsr -> kClangUsr
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
Labels: cla: yes

#3228 feat(columnar): add definitions for related node xrefs
  kythe/docs/rfc/2909.md
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/columnar/columnar_encoding.go
  kythe/go/serving/xrefs/columnar/columnar_test.go
  kythe/go/serving/xrefs/columnar_test.go
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: cla: yes

#3231 test: move pre-commit hook to pre-push
  tools/git/pre-commit.sh
  tools/git/pre-push.sh
  tools/git/setup_hooks.sh
Labels: cla: yes

#3232 feat(cxx_indexer): read all compilations from a kzip file (#3120)
  kythe/cxx/common/indexing/frontend.cc
  kythe/cxx/common/indexing/frontend.h
Labels: cla: yes

#3234 fix(cxx_extractor): segfault when given nonexistent file
  kythe/cxx/extractor/cxx_extractor.cc
Labels: cla: yes

#3236 fix(docs): fixed a few broken links
  kythe/docs/exploring-kythe-sample-web-ui.txt
  kythe/docs/kythe-configurable-extraction.txt
  kythe/docs/kythe-storage.txt
  kythe/web/site/examples.md
Labels: cla: yes

#3237 chore: prise away some LLVM deps for #945
  kythe/cxx/common/BUILD
  kythe/cxx/indexer/cxx/BUILD
  third_party/llvm/src/BUILD
Labels: cla: yes

#3238 fix: remove spammy log line
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
Labels: cla: yes

#3239 fix: allow git hooks to not exist
  tools/git/setup_hooks.sh
Labels: cla: yes

#3240 build: remove unused build targets
  third_party/BUILD
  third_party/safe_html_types/BUILD
  third_party/safe_html_types/LICENSE
Labels: cla: yes

#3242 chore: remove more LLVM from common (#945)
  kythe/cxx/common/BUILD
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/indexing/KytheCachingOutput.cc
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_details.cc
  kythe/cxx/extractor/cxx_details.h
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/extractor/cxx_extractor_main.cc
  kythe/cxx/extractor/language.cc
  kythe/cxx/extractor/language.h
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/cxx/extractor/path_utils.cc
  kythe/cxx/extractor/path_utils.h
  kythe/cxx/extractor/path_utils_test.cc
  kythe/cxx/extractor/testdata/BUILD
  kythe/cxx/extractor/testdata/claim_pragma_test.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheClaimClient.cc
  kythe/cxx/indexer/cxx/KytheClaimClient.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/frontend.h
  kythe/examples/proto/BUILD
  third_party/llvm/src/BUILD
Labels: cla: yes

#3243 chore: remove the remaining llvm references from cxx/common (#945)
  kythe/cxx/common/BUILD
  kythe/cxx/common/kythe_metadata_file.cc
  kythe/cxx/common/kythe_metadata_file.h
  kythe/cxx/common/protobuf_metadata_file.cc
  kythe/cxx/common/protobuf_metadata_file.h
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/extractor/index_pack.cc
  kythe/cxx/extractor/index_pack.h
  kythe/cxx/extractor/index_pack_test.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
  kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/frontend.h
  kythe/cxx/indexer/cxx/proto_conversions.h
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/tools/fyi/fyi.cc
  kythe/cxx/tools/shuck_main.cc
  kythe/cxx/tools/static_claim_main.cc
Labels: cla: yes

#3244 chore: rename header guards (#945)
  kythe/cxx/extractor/cxx_details.h
  kythe/cxx/extractor/index_pack.h
  kythe/cxx/extractor/language.h
  kythe/cxx/extractor/path_utils.h
  kythe/cxx/indexer/cxx/KytheClaimClient.h
  kythe/cxx/indexer/cxx/frontend.h
  kythe/cxx/indexer/cxx/proto_conversions.h
Labels: cla: yes

#3245 chore: nits (#945)
  kythe/cxx/common/kythe_metadata_file.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
Labels: cla: yes

#3248 typescript: fix some lint issues
  kythe/typescript/indexer.ts
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#3250 typescript: enable strict mode and fix errors
  kythe/typescript/indexer.ts
  kythe/typescript/tsconfig.json
Labels: buildbot, cla: yes

#3249 refactor: replace iteration over depsets with explicit .to_list() call
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3251 refactor(cxx_indexer): enumerate compilations as they're read
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/frontend.h
Labels: cla: yes

#3254 fix(cxx frontend): set CompilationUnit.source_file for unpacked input
  kythe/cxx/indexer/cxx/frontend.cc
Labels: cla: yes

#3256 refactor: make gcp gen stuff more extensible, in prep for adding bazel
  kythe/go/extractors/gcp/config/common.go
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/extractors/gcp/config/gradle.go
  kythe/go/extractors/gcp/config/maven.go
Labels: cla: yes

#3257 fix: spelling
  kythe/go/extractors/gcp/config/maven.go
Labels: cla: yes

#3259 build: add Bazel target for commitlint binary
  WORKSPACE
  external.bzl
  kythe/web/site/contributing.md
  package-lock.json
  package.json
  setup.bzl
  tools/git/BUILD
  tools/git/commit-msg.sh
Labels: cla: yes

#3258 feat(cxx_indexer): Add support for member pointers and uses of them a…
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/semantic_hash.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/rec/rec_class_member_ptr.cc
  kythe/cxx/indexer/cxx/testdata/template/template_decl_arg.cc
Labels: cla: yes

#3262 fix(docs): a few documentation updates
  kythe/web/site/examples.md
Labels: cla: yes

#3265 build: fix incompatibility with Bazel 0.19.2
  tools/cpp/clang_configure.bzl
  tools/git/commit-msg.sh
Labels: build, cla: yes

#3267 docs: Add team members
  CONTRIBUTORS
Labels: cla: yes

#3261 fix example for expands/transitive
  kythe/docs/schema/schema.txt
Labels: buildbot, cla: yes

#3268 feat: support emitting USRs for other kinds of declarations
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/usr_alias.cc
  kythe/cxx/indexer/cxx/testdata/basic/usr_enum.cc
  kythe/cxx/indexer/cxx/testdata/basic/usr_function.cc
  kythe/cxx/indexer/cxx/testdata/basic/usr_record.cc
  kythe/cxx/indexer/cxx/testdata/basic/usr_var.cc
Labels: cla: yes

#3269 fix(cxx_common): Add a dependency for strict dependency checking
  kythe/cxx/common/indexing/BUILD
Labels: cla: yes

#3275 fix: make workaround source compatible with JDK 11
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#3274 feat: add C++ extraction/analysis to Bazel example
  kythe/examples/bazel/kythe-index.sh
  kythe/examples/bazel/setup-bazel-repo.sh
  third_party/libmemcached.BUILD
Labels: cla: yes

#3277 feat(post-processing): add diagnostics to file decorations
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/encoding.go
  kythe/go/serving/xrefs/columnar.go
  kythe/proto/BUILD
  kythe/proto/pipeline.proto
  kythe/proto/pipeline_go_proto/pipeline.pb.go
Labels: cla: yes, post-processing

#3276 Copy in utf8 line index utils
  kythe/cxx/common/BUILD
  kythe/cxx/common/utf8_line_index.cc
  kythe/cxx/common/utf8_line_index.h
  kythe/cxx/common/utf8_line_index_test.cc
Labels: cla: yes

#3278 feat: add visibility aliases and mark some protos/utils as public
  kythe/cxx/common/BUILD
  kythe/proto/BUILD
  visibility.bzl
Labels: cla: yes

#3282 Create a new path_utils library in kythe/cxx/common that doesn't depend on llvm
  kythe/cxx/common/BUILD
  kythe/cxx/common/kythe_uri.cc
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
  kythe/cxx/common/path_utils_test.cc
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/path_utils.cc
  kythe/cxx/extractor/path_utils.h
  kythe/cxx/extractor/path_utils_test.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/frontend.cc
Labels: cla: yes

#3283 feat: add ReadConcurrency scan option to kzip
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/kzip/kzip_test.go
Labels: cla: yes

#3284 Riegeli: support parsing chunk_size option
  AUTHORS
  CONTRIBUTORS
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_test.go
Labels: buildbot, cla: yes

#3255 Add documentation and examples for the Go tools to releases/README.md
  AUTHORS
  CONTRIBUTORS
  kythe/release/README.md
Labels: buildbot, cla: yes

#3285 build: support Bazel 0.20 release
  WORKSPACE
Labels: build, cla: yes

#3286 build(buildbot): upgrade Bazel to 0.20.0
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: build, cla: yes
