Repository kythe/kythe, pull requests merged in 2018-06, with the labels that each got.

#85 Update //third_party:licenses
  third_party/BUILD
  third_party/absl/BUILD
  third_party/absl/LICENSE
  third_party/auto/BUILD
  third_party/auto/LICENSE.txt
  third_party/boringssl/BUILD
  third_party/boringssl/LICENSE
  third_party/errorprone/BUILD
  third_party/errorprone/COPYING
  third_party/gflags/BUILD
  third_party/gflags/COPYING.txt
  third_party/glog/BUILD
  third_party/glog/COPYING
  third_party/guava/BUILD
  third_party/guava/COPYING
  third_party/jcommander/BUILD
  third_party/jcommander/license.txt
  third_party/jsr250_api/BUILD
  third_party/jsr250_api/LICENSE
  third_party/jsr305/BUILD
  third_party/jsr305/LICENSE
  third_party/libmemcached/BUILD
  third_party/libmemcached/COPYING
  third_party/libuuid/BUILD
  third_party/libuuid/COPYING
  third_party/ow2-asm/BUILD
  third_party/ow2-asm/LICENSE.txt
  third_party/re2/BUILD
  third_party/re2/LICENSE
  third_party/re2j/BUILD
  third_party/re2j/LICENSE
  third_party/safe_html_types/BUILD
  third_party/safe_html_types/LICENSE
  third_party/truth/BUILD
  third_party/truth/LICENSE
  third_party/zlib/BUILD
  third_party/zlib/README
Labels: release

#96 Setup release v0.0.27
  RELEASES.md
  kythe/release/BUILD
Labels: release

#61 Add Beam LevelDB sink implementation
  WORKSPACE
  kythe/go/serving/pipeline/beamio/BUILD
  kythe/go/serving/pipeline/beamio/leveldb.go
  kythe/go/serving/pipeline/beamio/leveldb_test.go
  kythe/go/serving/tools/write_tables/BUILD
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: post-processing

#68 Assemble direct cross-references from anchors
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/nodes/nodes.go
  kythe/go/serving/pipeline/nodes/nodes_test.go
  kythe/proto/BUILD
  kythe/proto/pipeline.proto
  kythe/proto/pipeline_go_proto/pipeline.pb.go
Labels: post-processing

#116 Add Beam pipeline to generate *srvpb.FileDecorations
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/nodes/BUILD
  kythe/go/serving/pipeline/nodes/nodes.go
  kythe/go/serving/pipeline/nodes/nodes_test.go
  kythe/go/serving/tools/write_tables/BUILD
  kythe/go/serving/tools/write_tables/write_tables.go
  kythe/go/util/compare/compare_test.go
  kythe/proto/pipeline.proto
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/serving.proto
Labels: post-processing

#140 Add support for Bazel 0.14.1
  WORKSPACE
Labels: build

#138 Add target definitions to Beam-produced file decorations
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
Labels: post-processing

#151 Add tests to ensure all used proto types and functions are registered with Beam
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/beamtest/BUILD
  kythe/go/serving/pipeline/beamtest/beamtest.go
  kythe/go/serving/tools/write_tables/BUILD
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: post-processing

#150 Add basic cross-references to Beam pipeline
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/tools/write_tables/write_tables.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/web/ui/src-cljs/ui/service.cljs
Labels: post-processing

#153 Add PagedEdgeSet to Beam pipeline output
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/nodes/nodes.go
  kythe/go/serving/tools/write_tables/write_tables.go
  kythe/go/util/compare/compare.go
  kythe/proto/pipeline.proto
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
Labels: post-processing

#159 Initialize beam in main to support remote worker API
  kythe/go/serving/pipeline/beamio/leveldb.go
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: post-processing

#162 Update io_bazel_rules_go to v0.12.1
  WORKSPACE
Labels: build

#167 Add missing runtime dependency for Java Truth library
  WORKSPACE
  kythe/javatests/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/javatests/com/google/devtools/kythe/doc/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/indexpack/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/tools/BUILD
  kythe/javatests/com/google/devtools/kythe/util/BUILD
  third_party/truth/BUILD
Labels: build

#168 Java indexer: search for ClassSymbol in all Java 9 modules
  kythe/java/com/google/devtools/kythe/platform/java/helpers/JavacUtil.java
Labels: java

#176 Inherit language from file vname when creating new anchor.
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
Labels: buildbot

#178 entrystream: add support for Riegeli files
  kythe/go/platform/tools/entrystream/BUILD
  kythe/go/platform/tools/entrystream/entrystream.go
Labels: storage

#2791 Add support for Bazel 0.15
  WORKSPACE
Labels: build
