Repository kythe/kythe, pull requests merged in 2018-08, with the labels that each got.

#2910 Use the new Bazel C++ toolchain API
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/cpp/CROSSTOOL.tpl
Labels: buildbot

#2911 Add package extutil, to bridge .kzip/.kindex output.
  kythe/go/extractors/bazel/extutil/BUILD
  kythe/go/extractors/bazel/extutil/extutil.go
Labels: buildbot

#2914 Bazel extractors: Update dependencies, support code.
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
  kythe/go/extractors/cmd/bazel/extract_kindex/BUILD
  kythe/go/extractors/cmd/bazel/extract_kindex/extract_kindex.go
Labels: buildbot

#2924 Bazel Go extractor: Ensure compilations are tagged for "go".
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
Labels: buildbot

#2909 RFC: Kythe Columnar Serving Format
  kythe/docs/rfc/2909.md
Labels: RFC, post-processing, storage

#2926 Add Bazel 0.16.1 builder to Buildbot
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: build

#2928 Re-work the genyacc macro.
  kythe/cxx/verifier/BUILD
  tools/build_rules/lexyacc.bzl
Labels: buildbot

#2931 Add columnar FileDecorations protobuf message definitions
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/filetree_test.go
  kythe/go/serving/pipeline/nodes/BUILD
  kythe/go/serving/pipeline/nodes/nodes.go
  kythe/go/serving/pipeline/nodes/nodes_test.go
  kythe/proto/BUILD
  kythe/proto/pipeline.proto
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: schema, storage

#2940 Update to latest flogger version 1b447d1663ff8703
  WORKSPACE
Labels: cla: yes

#2941 kzip doc: Clarify the computation of unit digests.
  kythe/docs/kythe-kzip.txt
Labels: cla: yes

#2942 Re-work the genlex macro.
  kythe/cxx/verifier/BUILD
  tools/build_rules/lexyacc.bzl
Labels: cla: yes

#2944 KLS: Deal more gracefully with zero-width definition spans.
  kythe/go/languageserver/languageserver.go
  kythe/go/languageserver/languageserver_test.go
Labels: cla: yes

#2946 KLS: Don't discard an unresolved empty location during remapping.
  kythe/go/languageserver/languageserver.go
Labels: cla: yes, language server

#2947 Link against JDK8 targeted langtools
  third_party/javac/BUILD
Labels: cla: yes

#2949 Update apache/beam to latest Go SDK version
  WORKSPACE
  go.mod
  go.sum
  third_party/beam/sdks/go/pkg/beam/runners/disksort/buffer.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/disksort.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
Labels: build, cla: yes, post-processing

#2952 Remove deprecated use of built-in http/git rules
  WORKSPACE
Labels: buildbot, cla: yes

#2953 Kzip reader/writer for Java
  kythe/cxx/common/testdata/BUILD
  kythe/cxx/common/testdata/garbage_unit.kzip
  kythe/cxx/common/testdata/stringset_with_empty_file.kzip
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipException.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipReader.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/TestDataUtil.java
Labels: cla: yes

#2954 Use our shasum tool instead of md5 for releases
  kythe/release/BUILD
  kythe/release/package_release.sh
  kythe/release/release_test.sh
  kythe/release/setup_release.sh
Labels: cla: yes

#2956 Add override annotation
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
Labels: cla: yes

#2958 Use wc -c instead of du -b
  kythe/go/platform/tools/kindex_file_generator/BUILD
Labels: cla: yes, macOS

#2960 Cleanup java kzip tests
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
  kythe/proto/go.proto
  kythe/proto/go_go_proto/go.pb.go
Labels: cla: yes

#2962 Remove ProtoTypeAdapter for Java JSON code
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/java/com/google/devtools/kythe/util/JsonUtil.java
  third_party/BUILD
  third_party/gson/BUILD
  third_party/gson/LICENSE
  third_party/gson/ProtoTypeAdapter.java
  third_party/gson/README.google
Labels: cla: yes

#2963 Update Bazel go rules to 0.15.1
  WORKSPACE
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/generate_go_protobufs.py
Labels: cla: yes

#2959 Add Kzip to java extractors
  kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/JarExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BazelJvmExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
Labels: cla: yes, java, storage

#2964 Add Go 1.11 to Buildbot
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#2965 Add kzip support for indexers
  kythe/java/com/google/devtools/kythe/analyzers/indexer.bazelproject
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
  kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
Labels: cla: yes

#2966 Add an RFC for the analyzer interface spec.
  kythe/docs/rfc/2966.md
Labels: cla: yes

#2969 Add driver.proto defining messages for the analyzer protocol.
  kythe/proto/BUILD
  kythe/proto/driver.proto
  kythe/proto/driver_go_proto/driver.pb.go
Labels: cla: yes

#2970 Add toolchain for tools needed for asciidoc rules
  WORKSPACE
  kythe/docs/asciidoc.bzl
  kythe/docs/schema/asciidoc_with_verifier.bzl
  tools/build_rules/external_tools/BUILD
  tools/build_rules/external_tools/external_tools_configure.bzl
  tools/build_rules/external_tools/external_tools_toolchain.bzl
Labels: cla: yes

#2971 Don't use parallel
  kythe/extractors/cmake/extract_compilation_database.sh
Labels: cla: yes

#2972 Add ResolvedDiagnostic/CorpusPath proto definitions
  kythe/proto/common.proto
  kythe/proto/common_go_proto/common.pb.go
Labels: cla: yes

#2973 Expose libzip/error.h and expand it to allow copy construction and co…
  kythe/cxx/common/BUILD
  kythe/cxx/common/libzip/error.cc
  kythe/cxx/common/libzip/error.h
Labels: cla: yes

#2974 Force GoDetails to be loaded in kzip c++ tests
  kythe/cxx/common/BUILD
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_reader.h
  kythe/cxx/common/kzip_reader_test.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
  kythe/cxx/common/kzip_writer_test.cc
Labels: cla: yes

#2975 Analysis protocol: Clarify request lifetime.
  kythe/docs/rfc/2966.md
Labels: cla: yes
