Repository kythe/kythe, pull requests merged in 2018-09, with the labels that each got.

#2979 Mark ref/queries edge kind as an anchor edge
  kythe/java/com/google/devtools/kythe/analyzers/base/EdgeKind.java
Labels: cla: yes

#2981 Get //kythe/docs/schema:schema building again
  kythe/docs/schema/asciidoc_with_verifier.bzl
  kythe/docs/schema/example-cxx.sh
  kythe/docs/schema/example-dot.sh
  kythe/docs/schema/example-go.sh
  kythe/docs/schema/example-objc.sh
  tools/build_rules/external_tools/external_tools_configure.bzl
Labels: cla: yes

#2982 Define a deprecated tag and use it for C++
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/attribute_deprecated.cc
  kythe/docs/schema/schema.txt
Labels: cla: yes

#2985 Go indexer: Fix more anonymous struct field declarations.
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/anonymous.go
Labels: cla: yes

#2983 Use our own custom shasum tool
  kythe/docs/schema/asciidoc_with_verifier.bzl
  kythe/docs/schema/example-base.sh
  kythe/docs/schema/example-cxx.sh
  kythe/docs/schema/example-dot.sh
  kythe/docs/schema/example-go.sh
  kythe/docs/schema/example-java.sh
  kythe/docs/schema/example-objc.sh
  tools/build_rules/external_tools/external_tools_configure.bzl
Labels: cla: yes

#2980 Support new location for project-specific Bazel options
  .bazelrc
  tools/bazel.rc
Labels: cla: yes

#2986 go_indexer: Remove indexpack support.
  kythe/go/indexer/cmd/go_indexer/BUILD
  kythe/go/indexer/cmd/go_indexer/go_indexer.go
Labels: cla: yes, go

#2987 Implement the encoding for columnar FileDecorations
  kythe/go/serving/xrefs/columnar/BUILD
  kythe/go/serving/xrefs/columnar/columnar_encoding.go
  kythe/go/serving/xrefs/columnar/columnar_test.go
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: cla: yes

#2988 Move common schema functions into schema package
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/nodes/nodes.go
  kythe/go/util/schema/schema.go
Labels: cla: yes

#2989 Implement columnar FileDecorations table reader
  kythe/go/serving/xrefs/BUILD
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/columnar/columnar_encoding.go
  kythe/go/serving/xrefs/columnar_test.go
Labels: cla: yes

#2991 Implement columnar FileDecorations post-processing
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/encoding.go
  kythe/go/serving/tools/write_tables/BUILD
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: cla: yes, post-processing

#2992 Support upcoming Bazel 0.17
  WORKSPACE
Labels: build, cla: yes

#2995 Make --check_for_singletons the default and clean up failing tests
  kythe/cxx/extractor/testdata/extract_verify_stddef_test.cc
  kythe/cxx/extractor/testdata/test_stdin_names_verify.cc
  kythe/cxx/indexer/cxx/testdata/test_index_pack.sh
  kythe/cxx/indexer/cxx/testdata/test_kindex.sh
  kythe/cxx/verifier/verifier_main.cc
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/DefaultPackage.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericMethod.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Generics.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Imports.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Inheritance.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Lambdas.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MemberReferences.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Names.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/PluginTests.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Selectors.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/WildcardMethod.java
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt
  kythe/release/release_test.sh
Labels: cla: yes

#2996 Fix JVM PluginTests edge
  kythe/javatests/com/google/devtools/kythe/analyzers/java/TestPlugin.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/PluginTests.java
Labels: cla: yes

#2997 Ignore singletons in jvm_nodes_tests
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
Labels: cla: yes

#3000 Update gradlecmd to support different javacWrapper
  kythe/go/extractors/config/runextractor/gradlecmd/gradle_build_modifier.go
  kythe/go/extractors/config/runextractor/gradlecmd/gradle_build_modifier_test.go
  kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
  kythe/go/extractors/config/runextractor/gradlecmd/testdata/modified-gradle.build
  kythe/go/extractors/config/runextractor/gradlecmd/testdata/other-gradle.build
Labels: cla: yes

#2998 Implement columnar CrossReferences encoding
  kythe/go/serving/xrefs/columnar/columnar_encoding.go
  kythe/go/serving/xrefs/columnar/columnar_test.go
  kythe/go/util/keys/keys.go
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: cla: yes

#3002 Make kzip_{reader,writer} visible
  kythe/cxx/common/BUILD
Labels: cla: yes

#3003 Add test for compilation database extraction
  kythe/extractors/cmake/BUILD
  kythe/extractors/cmake/extract_compilation_database.sh
  kythe/extractors/cmake/test_extract_compilation_database.sh
  kythe/extractors/cmake/testdata/expected.file
  kythe/extractors/cmake/testdata/expected.unit
  kythe/go/extractors/config/runextractor/compdb/BUILD
  kythe/go/extractors/config/runextractor/compdb/compdb_test.go
  kythe/go/extractors/config/runextractor/compdb/testdata/compilation_database.json
  kythe/go/extractors/config/runextractor/compdb/testdata/test_file.cc
Labels: cla: yes

#3004 Java indexer: analyze default annotation values
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
Labels: cla: yes, indexing, java

#3005 Fix another singleton variable in the marked-source example.
  kythe/docs/schema/marked-source.txt
Labels: cla: yes

#3006 Default extracted verifier tests to not check for singletons.
  kythe/docs/schema/example-java.sh
  kythe/docs/schema/example-objc.sh
  kythe/docs/schema/kythe-filter.conf
Labels: cla: yes

#3007 Java indexer: avoid NPE with erroneous compilations missing identifie…
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#3008 Java indexer: emit diagnostic for incomplete java.lang.* Symbols
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#3010 xref_serving.proto: add UNKNOWN default values for enums
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: cla: yes

#3011 Remove further usage of deprecated repository rules
  WORKSPACE
Labels: buildbot, cla: yes

#3013 Make the asciidoc rule emit outputs to a zip file.
  kythe/docs/asciidoc.bzl
  kythe/web/site/sync_docs.sh
  tools/build_rules/external_tools/external_tools_configure.bzl
Labels: cla: yes

#3014 Missing operator= return values in StatusOr
  kythe/cxx/common/status_or.h
Labels: cla: yes

#3015 Add a Kythe schema overview doc.
  kythe/docs/BUILD
  kythe/docs/schema-overview.txt
Labels: cla: yes

#3017 Site sync: Explicitly build the schema-overview doc.
  kythe/web/site/sync_docs.sh
Labels: cla: yes

#3019 Upgrade Buildbot container to debian:stretch
  kythe/docs/BUILD
  kythe/release/appengine/buildbot/Dockerfile
Labels: cla: yes

#3018 Implement columnar CrossReferences serving reader
  kythe/go/serving/xrefs/BUILD
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/columnar_test.go
  kythe/proto/xref_serving.proto
Labels: cla: yes

#3020 Implement columnar CrossReferences post-processing
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/beamio/leveldb.go
  kythe/go/serving/pipeline/encoding.go
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: cla: yes, post-processing

#3021 Go: Mark result parameters as part of the TYPE in MarkedSource.
  kythe/go/indexer/indexer.go
  kythe/go/indexer/testdata/code/methdecl.go
Labels: cla: yes

#3022 Always build gradle clean.
  kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
Labels: cla: yes

#3023 Some automated clang-tidy fixes from previous commit
  kythe/cxx/common/file_vname_generator.h
  kythe/cxx/common/index_pack.h
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
  kythe/cxx/verifier/assertions.h
  kythe/cxx/verifier/verifier.h
Labels: cla: yes

#3025 Add .vscode to kythe .gitignore
  .gitignore
Labels: cla: yes

#3024 Add MarkedSources to columnar CrossReferences
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/pipeline/beamtest/beamtest.go
  kythe/go/serving/pipeline/encoding.go
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/columnar_test.go
Labels: cla: yes

#3027 Update apache/beam to 09857b18ffd8
  WORKSPACE
  go.mod
  go.sum
Labels: cla: yes, post-processing

#3028 Another round of clang-tidy.
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
Labels: cla: yes

#3029 Remove concurrency from Beam disksort runner
  third_party/beam/BUILD
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk_test.go
Labels: cla: yes

#3030 Remove unused Shipshape config
  .shipshape
Labels: cla: yes

#3031 Add experimental config for Bazel's Remote Build Execution
  WORKSPACE
  tools/bazel.rc
  tools/remote_test.sh
Labels: build, cla: yes

#3032 Add Bazel RBE builder in Buildbot
  kythe/release/appengine/buildbot/master/master.cfg.template
  tools/bazel.rc
Labels: cla: yes

#3033 Add custom RBE toolchain for Kythe system dependencies
  tools/bazel.rc
  tools/modules/update.sh
  tools/platforms/BUILD
  tools/platforms/Dockerfile
  tools/remote_test.sh
Labels: cla: yes

#3034 Remove irrelevant location parameter from BuildNodeIdForTemplate{Name…
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
Labels: cla: yes

#3035 Fix verifier tests in RBE environment
  kythe/go/indexer/testdata/go_indexer_test.bzl
  tools/remote_test.sh
Labels: cla: yes

#3036 Fix asciidoc targets in RBE environment
  kythe/docs/asciidoc.bzl
  tools/remote_test.sh
Labels: cla: yes

#3037 Fork Flogger to build Java targets in RBE environment
  WORKSPACE
  tools/remote_test.sh
Labels: cla: yes

#3038 Fix java_verifier_tests in RBE environment
  tools/build_rules/verifier_test/verifier_test.bzl
  tools/remote_test.sh
Labels: cla: yes

#3040 Use RBE for all Bazel 0.17.1 Buildbot configurations
  kythe/release/appengine/buildbot/master/master.cfg.template
  tools/remote_test.sh
Labels: cla: yes

#3041 Split type MarkedSource nodes containing decl names
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/marked_source/ms_array.cc
Labels: C++, cla: yes

#3043 Bazel extractors: Emit .kzip files by default.
  kythe/go/extractors/bazel/extractors.bzl
Labels: cla: yes

#3044 Ensure asciidoc invocation gets data runfiles (for Java)
  kythe/docs/asciidoc.bzl
  kythe/docs/schema/java-schema-unit-template.CompilationUnit
Labels: cla: yes

#3045 Add //kythe/docs/schema to Buildbot release tests
  kythe/docs/schema/BUILD
  kythe/docs/schema/asciidoc_with_verifier.bzl
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3047 Remove platform directory prefixes from go_binary output paths
  tools/build_rules/shims.bzl
Labels: build, cla: yes

#3046 Add runextractor to kythe-java-extractor-artifacts image.
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile
Labels: cla: yes, extraction, maven

#3048 Bazel extractor: Remove a redundant call to config.FixUnit.
  kythe/go/extractors/bazel/extractor.go
  kythe/go/extractors/bazel/extractor_test.go
Labels: cla: yes

#3050 Add helper method for Kotlin indexer
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
Labels: cla: yes

#3052 Remove MvnPomPreprocessor, mvn-extract.sh
  kythe/go/extractors/config/testdata/expected_mvn_config.Dockerfile
  kythe/go/extractors/config/testdata/mvn_config.json
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile
  kythe/java/com/google/devtools/kythe/platform/tools/BUILD
  kythe/java/com/google/devtools/kythe/platform/tools/MvnPomPreprocessor.java
  kythe/java/com/google/devtools/kythe/platform/tools/pom_compiler_plugin_fragment.xml
  kythe/javatests/com/google/devtools/kythe/platform/tools/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/tools/MvnPomPreprocessorTest.java
  kythe/javatests/com/google/devtools/kythe/platform/tools/testdata/expected_pom.xml
  kythe/javatests/com/google/devtools/kythe/platform/tools/testdata/test_pom_with_plugin.xml
  kythe/javatests/com/google/devtools/kythe/platform/tools/testdata/test_pom_without_plugin.xml
Labels: cla: yes

#3053 Use filepath.Dir & filepath.Base instead of filepath.Split.
  kythe/go/extractors/config/runextractor/backup/backup.go
Labels: cla: yes, extraction, maven

#3058 Excise remaining references to old maven scripts and preprocessor.
  kythe/docs/kythe-configurable-extraction.txt
  kythe/go/extractors/config/default/mvn/mvn.go
  kythe/go/extractors/config/extractor.go
  kythe/go/extractors/config/runextractor/README.md
  kythe/java/com/google/devtools/kythe/extractors/java/maven/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/maven/mvn-extract.sh
Labels: cla: yes, extraction, maven

#3049 Riegeli: implement transposed record chunk encoder
  kythe/go/platform/tools/entrystream/entrystream.go
  kythe/go/util/riegeli/BUILD
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_bench_test.go
  kythe/go/util/riegeli/riegeli_test.go
  kythe/go/util/riegeli/riegeli_test.proto
  kythe/go/util/riegeli/riegeli_test_go_proto/riegeli_test.pb.go
  kythe/go/util/riegeli/transpose_decoder.go
  kythe/go/util/riegeli/transpose_encoder.go
  kythe/go/util/riegeli/transpose_util.go
  kythe/go/util/riegeli/writer.go
  kythe/proto/go.bzl
Labels: cla: yes

#3057 Refactor BuildNodeIdForType and TraverseTypeLoc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/node_set.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/enum_fwd_ref.cc
Labels: cla: yes

#3063 Java extractor: pass through -processorpath; don't delete gensrcdir early
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes, extraction, java

#3064 Add Bazel aspect to run javac_extractor
  kythe/data/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
Labels: cla: yes, extraction, java

#3062 Add logic for selecting maven or gradle based on repo build file.
  kythe/go/extractors/config/BUILD
  kythe/go/extractors/config/base/BUILD
  kythe/go/extractors/config/base/base.go
  kythe/go/extractors/config/base/base_test.go
  kythe/go/extractors/config/base/gradle/BUILD
  kythe/go/extractors/config/base/gradle/gradle.go
  kythe/go/extractors/config/base/mvn/BUILD
  kythe/go/extractors/config/base/mvn/mvn.go
  kythe/go/extractors/config/base/testdata/expected_gradle_config.Dockerfile
  kythe/go/extractors/config/base/testdata/expected_mvn2_config.Dockerfile
  kythe/go/extractors/config/base/testdata/expected_mvn_config.Dockerfile
  kythe/go/extractors/config/base/testdata/gradle_config.json
  kythe/go/extractors/config/base/testdata/mvn2_config.json
  kythe/go/extractors/config/base/testdata/mvn_config.json
  kythe/go/extractors/config/config_parser.go
  kythe/go/extractors/config/config_parser_test.go
  kythe/go/extractors/config/config_selector.go
  kythe/go/extractors/config/config_selector_test.go
  kythe/go/extractors/config/extractor.go
Labels: cla: yes, extraction, gradle, maven

#3065 Bazel extractor: Avoid re-recording input files already added.
  kythe/go/extractors/bazel/extractor.go
  kythe/go/extractors/bazel/extractor_test.go
Labels: cla: yes

#3066 Fix lint errors from last minute change in previous commit.
  kythe/go/extractors/config/base/gradle/gradle.go
  kythe/go/extractors/config/base/mvn/mvn.go
Labels: cla: yes

#3061 Riegeli: add textual encoding/decoding of WriterOptions
  kythe/go/platform/tools/entrystream/entrystream.go
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_bench_test.go
  kythe/go/util/riegeli/riegeli_test.go
Labels: cla: yes

#3067 Reformat Skylark files
  kythe/cxx/tools/fyi/testdata/compile_commands.bzl
  kythe/go/extractors/bazel/extractors.bzl
  kythe/go/indexer/testdata/go_indexer_test.bzl
  kythe/go/util/vnameutil/test/macros.bzl
  kythe/proto/go.bzl
  kythe/rust/indexer/testdata/rust_indexer_test.bzl
  third_party/go/build.bzl
  tools/build_rules/docker.bzl
  tools/build_rules/expand_template.bzl
  tools/build_rules/rust/cargo.bzl
  tools/build_rules/shims.bzl
  tools/build_rules/testing.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
  tools/cpp/clang_configure.bzl
  version.bzl
Labels: cla: yes

#3068 Add .bzl files to buildifier lint check
  tools/arc/linter.sh
Labels: cla: yes

#3070 Riegeli: encode RecordsMetadata with WriterOptions
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_test.go
  kythe/go/util/riegeli/transpose_decoder.go
  kythe/go/util/riegeli/transpose_encoder.go
  kythe/go/util/riegeli/writer.go
Labels: cla: yes

#3071 Rename extract_kindex to extract_kzip.
  kythe/go/extractors/bazel/extractors.bzl
  kythe/go/extractors/cmd/bazel/BUILD
  kythe/go/extractors/cmd/bazel/extract_kzip/BUILD
  kythe/go/extractors/cmd/bazel/extract_kzip/extract_kzip.go
Labels: cla: yes

#3073 Rename the kindex_extractor macro to kzip_extractor.
  kythe/go/extractors/bazel/extractors.bzl
Labels: cla: yes

#3074 Fix KzipWriter to include mandatory directory entries and update test…
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
  kythe/cxx/common/kzip_writer_test.cc
  kythe/cxx/extractor/testdata/test_kzip.sh
Labels: cla: yes

#3072 Make maven/gradle extractors default to using kzip
  kythe/go/extractors/config/base/gradle/gradle.go
  kythe/go/extractors/config/base/mvn/mvn.go
  kythe/go/extractors/config/base/testdata/expected_gradle_config.Dockerfile
  kythe/go/extractors/config/base/testdata/expected_mvn2_config.Dockerfile
  kythe/go/extractors/config/base/testdata/expected_mvn_config.Dockerfile
  kythe/go/extractors/config/base/testdata/gradle_config.json
  kythe/go/extractors/config/base/testdata/mvn2_config.json
  kythe/go/extractors/config/base/testdata/mvn_config.json
  kythe/go/extractors/config/runextractor/README.md
  kythe/go/extractors/config/runextractor/constants/constants.go
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes, extraction, gradle, maven

#3076 Write out JSON correctly for Java kzips
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
  kythe/java/com/google/devtools/kythe/platform/kzip/kzip.bazelproject
  kythe/java/com/google/devtools/kythe/util/JsonUtil.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
Labels: cla: yes

#3077 Bootstrap JVM extractor details messages
  kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BazelJvmExtractor.java
Labels: cla: yes, extraction

#3080 Buildbot: dynamically check Kythe team membership for PRs
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3081 Buildbot: upgrade Bazel to 0.17.2
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3082 Only replace Decl TSI if the location-aware type is an undeduced type
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/function/function_knr_defn.c
  kythe/cxx/indexer/cxx/testdata/function/function_picky_types.c
Labels: cla: yes

#3079 Simplify the use of recordTapp and recordTsigma calls
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
Labels: cla: yes

#3083 Fix building @io_kythe//third_party/llvm/src:clang_builtin_headers
  third_party/llvm/src/BUILD
  tools/build_rules/cc_resources.bzl
Labels: build, cla: yes

#3084 Implement StandardJavaFileManager for wrapper class
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes, extraction, java

#3086 Riegeli: fix seeking in files with metadata record
  kythe/go/util/riegeli/reader.go
  kythe/go/util/riegeli/riegeli_test.go
Labels: cla: yes
