Repository kythe/kythe, pull requests merged in 2019-06, with the labels that each got.

#3782 fix: correct chunk position starting a block boundary
  kythe/go/util/riegeli/BUILD
  kythe/go/util/riegeli/reader.go
  kythe/go/util/riegeli/riegeli_test.go
  kythe/go/util/riegeli/util.go
  kythe/go/util/riegeli/writer.go
Labels: cla: yes, storage

#3788 fix(java_indexer): only emit MarkedSource for defined symbols
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: cla: yes, indexing, java

#3789 chore(build): allow overriding extract_kzip tool path
  kythe/go/extractors/bazel/extractors.bzl
Labels: cla: yes

#3791 revert: "fix(java_indexer): only emit MarkedSource for defined symbols (#3788)
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: cla: yes

#3790 chore: add tag/deprecated as a fact in schema.proto for easier parsing
  kythe/data/schema_index.textproto
  kythe/go/util/schema/indexdata.go
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
Labels: cla: yes

#3792 fix(java_indexer): only emit MarkedSource for defined symbols
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3793 fix(java_common): make FactEmitters Closeable
  kythe/java/com/google/devtools/kythe/analyzers/base/FactEmitter.java
  kythe/java/com/google/devtools/kythe/analyzers/base/StreamFactEmitter.java
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
Labels: cla: yes

#3794 deprecation(java_indexer): change default to --emit_jvm=SEMANTIC
  kythe/docs/schema/example-java.sh
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
Labels: cla: yes, indexing, java

#3795 test(java_indexer): make cross-compilation tests more precise
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
Labels: cla: yes, indexing, java

#3798 ci(buildbot): upgrade Go compiler to 1.12.5
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg
Labels: cla: yes

#3796 build: add .bazelminversion file to match .bazelversion
  .bazelminversion
  BUILD
  WORKSPACE
  tools/BUILD
  tools/check_bazel_versions.sh
  version.bzl
Labels: cla: yes

#3797 build: update Bazel to v0.26.1
  .bazelversion
  version.bzl
Labels: cla: yes

#3799 ci(buildbot): use Bazelisk to dynamically determine Bazel versions
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/bazel
  kythe/release/appengine/buildbot/master/master.cfg
  tools/arc/linter.sh
Labels: cla: yes

#3800 feat(java_indexer): emit refs to JVM graph for externally defined nodes
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/common/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java
Labels: cla: yes, indexing, java

#3801 chore: fix spelling
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#3803 fix(java_indexer): avoid NPE when referencing Java package in comment
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java
Labels: cla: yes, indexing, java

#3804 style: call static methods on class
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#3787 feature: Plugin model for TypeScript indexer
  kythe/typescript/indexer.ts
  kythe/typescript/test.ts
  kythe/typescript/testdata/plugin.ts
  kythe/typescript/testdata/tsconfig.json
Labels: buildbot, cla: yes

#3674 Improve documentation for cross-language support
  kythe/docs/schema/BUILD
  kythe/docs/schema/indexing-generated-code.txt
  kythe/web/site/sync_docs.sh
Labels: buildbot, cla: yes

#3805 build: update rules_nodejs to v0.31.1
  .bazelignore
  .bazelminversion
  .bazelrc
  WORKSPACE
  external.bzl
  setup.bzl
  tools/git/BUILD
  version.bzl
Labels: build, cla: yes

#3807 build: add Bazel targets for typescript indexer
  WORKSPACE
  kythe/typescript/BUILD
  kythe/typescript/indexer.ts
  kythe/typescript/tsconfig.json
  package-lock.json
  package.json
Labels: build, cla: yes, typescript

#3808 build: disable symlink_node_modules to mitigate build failures
  WORKSPACE
Labels: build, cla: yes

#3809 build: add Bazel test for utf8_test.ts
  .gitignore
  kythe/typescript/BUILD
  package-lock.json
  package.json
Labels: build, cla: yes, typescript

#3810 build: add Bazel test for TS indexer
  kythe/typescript/BUILD
  kythe/typescript/test.ts
Labels: build, cla: yes, typescript

#3811 style: remove unused import
  kythe/typescript/test.ts
Labels: cla: yes

#3813 chore(llvm): update LLVM to r363125
  kythe/cxx/tools/fyi/fyi.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_deps.bzl
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3784 feat(typescript_indexer): Getter/Setter entries
  CONTRIBUTORS
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/getter_setter.ts
Labels: buildbot, cla: yes

#3812 feat(typescript_indexer): wrap plugin indexing in try/catch block
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3703 chore: explicity mark py_binary version
  tools/build_rules/verifier_test/BUILD
Labels: cla: yes, cleanup

#3817 build: disable incompatible_list_based_execution_strategy_selection
  .bazelrc
Labels: cla: yes

#3785 feat(typescript_indexer): VName schema compliance for constructors
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
Labels: buildbot, cla: yes

#3806 docs(typescript_indexer): document separate compilation
  kythe/typescript/README.md
Labels: buildbot, cla: yes

#3818 fix(objc): Log extractor errors
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
Labels: cla: yes, objective-c

#3820 refactor(typescript_indexer): defer method to TypeScript compiler
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3821 feat(extraction): initial support for extracting openjdk11
  go.mod
  go.sum
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/extractors/openjdk11/BUILD
  kythe/extractors/openjdk11/README.md
  kythe/extractors/openjdk11/extract/extract.go
  kythe/extractors/openjdk11/java_wrapper/java_wrapper.go
  kythe/extractors/openjdk11/vnames.json
  kythe/extractors/openjdk8/BUILD
  kythe/extractors/openjdk8/Dockerfile
  kythe/extractors/openjdk8/extract.sh
  kythe/extractors/openjdk8/run.sh
  kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
Labels: cla: yes

#3822 fix(proto): include deprecation tags for messages, enums and enum values.
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
  kythe/cxx/indexer/proto/testdata/basic/deprecated.proto
Labels: cla: yes

#3824 build: update to Bazel v0.27.0
  .bazelversion
  version.bzl
Labels: cla: yes

#3826 fix(java_indexer): emit MarkedSource for defined nodes referenced earlier in analysis
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: bug, cla: yes, indexing, java

#3827 fix(extraction): make java_wrapper handle a few more modules
  kythe/extractors/openjdk11/java_wrapper/java_wrapper.go
Labels: cla: yes

#3829 chore(java_common): move JDK9-compatibility shims to common base
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
Labels: cla: yes

#3830 chore(java_extractor): delete unused method
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3831 chore(java_extactor): remove more now-unused members
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3832 fix(java_indexer): emit and test type parameter MarkedSources
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: bug, cla: yes, indexing, java

#3828 feat(typescript_indexer): pass module name creation logic to plugins
  kythe/typescript/indexer.ts
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#3837 feat(build): switch to using targets generated by kythe/llvmbzlgen
  external.bzl
  tools/build_rules/llvm/cmakedefines/BUILD
  tools/build_rules/llvm/cmakedefines/cmakedefines.go
  tools/build_rules/llvm/configure_file.bzl
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_deps.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
Labels: cla: yes

#3838 chore(java_common): propagate underlying exceptions if possible
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
Labels: cla: yes

#3839 chore: automated fixes from downstream linter
  kythe/typescript/indexer.ts
Labels: cla: yes

#3840 feat(kzip): add `info` command to kzip tool which returns count of compilation units and referenced corpus names.
  kythe/go/platform/tools/kzip/BUILD
  kythe/go/platform/tools/kzip/infocmd/BUILD
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
  kythe/go/platform/tools/kzip/kzip.go
Labels: cla: yes

#3836 feat(kzip): add support for encoding compilation units as proto and/or JSON in kzips.
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/kzip/kzip_test.go
  kythe/go/platform/kzip/missing-pbunit.kzip
  kythe/go/platform/kzip/missing-unit.kzip
  kythe/go/platform/tools/kzip/flags/BUILD
  kythe/go/platform/tools/kzip/flags/encoding.go
  kythe/go/platform/tools/kzip/mergecmd/BUILD
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#3842 feat(kzip): create permits specifying encoding
  kythe/go/platform/tools/kzip/createcmd/BUILD
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#3843 fix(kzip): EncodingFlag fully implements flag.Getter and flag.Value
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/tools/kzip/flags/encoding.go
Labels: cla: yes

#3844 Use non-deprecated Throwables.throwIfUnchecked method
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
Labels: cla: yes

#3845 fix(kzip): ensure the EncodingFlag has a suitable default.
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#3846 fix(kzip): use proper incantation so testdata still found on import
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip_test.go
  kythe/go/platform/kzip/testdata/missing-pbunit.kzip
  kythe/go/platform/kzip/testdata/missing-unit.kzip
Labels: cla: yes

#3848 Update website runtime to Go 1.12
  .arclint
  kythe/release/appengine/default/.gcloudignore
  kythe/release/appengine/default/BUILD
  kythe/release/appengine/default/app.yaml
  kythe/release/appengine/default/go.mod
  kythe/release/appengine/default/main.go
Labels: cla: yes

#3847 build: disable version check for Bazel release candidates
  version.bzl
Labels: cla: yes

#3849 test(go_indexer): fix broken tests
  kythe/go/indexer/BUILD
  kythe/go/indexer/testdata/code/interface.go
  kythe/go/indexer/testdata/code/structtype.go
Labels: cla: yes

#3850 fix(go_indexer): use only name for a named type's MarkedSource
  kythe/go/indexer/markedsource.go
  kythe/go/indexer/testdata/code/interface.go
  kythe/go/indexer/testdata/code/structtype.go
Labels: cla: yes
