Repository kythe/kythe, pull requests merged in 2019-09, with the labels that each got.

#4051 docs: document the compilation unit digesting algorithm
  kythe/docs/kythe-kzip.txt
Labels: cla: yes

#4052 chore(cxx_common): update llvm to version 370702
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor_test.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4054 fix(java_indexer): accept AutoValue.Builder interface definitions
  kythe/java/com/google/devtools/kythe/analyzers/java/AutoValuePlugin.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AutoValues.java
Labels: cla: yes, indexing, java

#4053 fix(java_extractor): and tests should use ambient langtools
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD
Labels: cla: yes

#4056 test(java_indexer): add tests for full method defines
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
Labels: cla: yes

#4058 feat(java_indexer): add typed edges for `this`/`super`
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Selectors.java
Labels: cla: yes, indexing, java

#4057 chore(cxx_common): cleanups necessary to update to C++17
  .bazelrc
  kythe/cxx/common/BUILD
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/extractor/textproto/textproto_schema.cc
  kythe/cxx/indexer/textproto/analyzer.cc
  third_party/libmemcached.BUILD
  tools/platforms/BUILD
  tools/platforms/Dockerfile
Labels: cla: yes

#4059 fix(cxx_indexer): whitelist and test std::make_shared
  kythe/cxx/indexer/cxx/ImputedConstructorSupport.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/libraries/make_shared_factories.cc
  kythe/cxx/indexer/cxx/testdata/libraries/make_unique_factories.cc
Labels: cla: yes

#4048 feat(java_common): implement standard compilation unit digesting
  kythe/cxx/common/testdata/56bf5044e1b5c4c1cc7c4b131ac2fb979d288460e63352b10eef80ca35bd0a7b.pbtxt
  kythe/cxx/common/testdata/BUILD
  kythe/cxx/common/testdata/bb761979683e7c268e967eb5bcdedaa7fa5d1d472b0826b00b69acafbaad7ee6.pbtxt
  kythe/cxx/common/testdata/e9e170dcfca53c8126755bbc8b703994dedd3af32584291e01fba164ab5d3f32.pbtxt
  kythe/go/platform/kcd/kythe/BUILD
  kythe/go/platform/kcd/kythe/units_test.go
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/CompilationUnits.java
  kythe/java/com/google/devtools/kythe/platform/shared/TestDataUtil.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/CompilationUnitsTest.java
Labels: cla: yes

#4041 chore: remove kindex support in golang tools and indexer
  kythe/go/extractors/cmd/gotool/BUILD
  kythe/go/extractors/cmd/gotool/gotool.go
  kythe/go/extractors/golang/BUILD
  kythe/go/extractors/golang/golang.go
  kythe/go/indexer/cmd/go_example/BUILD
  kythe/go/indexer/cmd/go_example/go_example.go
  kythe/go/indexer/cmd/go_indexer/go_indexer.go
  kythe/go/indexer/indexer.go
Labels: cla: yes

#4060 feat(java_common): use the standard compilation unit digest for kzip
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#4063 perf(post_processing): use heap.Fix in disksort
  kythe/go/util/disksort/disksort.go
Labels: cla: yes

#4061 feat(typescript_indexer): print plugin names
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4062 feat(typescript_indexer): don't emit duplicate nodes for namespaces
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/namespace.ts
Labels: buildbot, cla: yes

#4035 refactor(typescript_indexer): use native `ts.HasExpressionInitializer`
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4066 fix(extraction): update bazel-extractor Docker image to clang-6.0
  kythe/extractors/bazel/Dockerfile
Labels: cla: yes

#4068 chore: update max bazel version; remove redundant flag
  .bazelversion
  version.bzl
Labels: cla: yes

#4071 chore(java_indexer): remove indexpack support
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
  kythe/java/com/google/devtools/kythe/platform/indexpack/Archive.java
  kythe/java/com/google/devtools/kythe/platform/indexpack/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/indexer_test.sh
  kythe/javatests/com/google/devtools/kythe/platform/indexpack/ArchiveTest.java
  kythe/javatests/com/google/devtools/kythe/platform/indexpack/BUILD
Labels: cla: yes

#4072 feat(post_processing): support Riegeli Snappy compression
  kythe/go/util/riegeli/BUILD
  kythe/go/util/riegeli/compression.go
  kythe/go/util/riegeli/golden_test.go
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_bench_test.go
  kythe/go/util/riegeli/riegeli_test.go
  kythe/go/util/riegeli/testdata/golden.entries.snappy.riegeli
  kythe/go/util/riegeli/util.go
Labels: cla: yes

#4073 deprecation: remove usages of extutil.ExtractAndWrite
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
  kythe/go/extractors/proto/BUILD
  kythe/go/extractors/proto/extract_proto_kzip.go
Labels: cla: yes

#4074 chore: add minimum Go version to go.mod
  go.mod
Labels: cla: yes

#4075 chore: remove more indexpack usages including pack2kzip and indexpack tools
  kythe/cxx/tools/testdata/BUILD
  kythe/cxx/tools/testdata/test_claim_tool_index_pack.sh
  kythe/go/platform/tools/BUILD
  kythe/go/platform/tools/indexpack/BUILD
  kythe/go/platform/tools/indexpack/indexpack.go
  kythe/go/platform/tools/indexpack_test.sh
  kythe/go/platform/tools/pack2kzip/BUILD
  kythe/go/platform/tools/pack2kzip/pack2kzip.go
  kythe/release/BUILD
  kythe/release/README.md
  kythe/release/release_test.sh
Labels: cla: yes

#4076 ci(buildbot): add wrapper script to use go.mod required compiler version
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/go
  kythe/release/appengine/buildbot/master/master.cfg
Labels: cla: yes

#4077 chore: remove remaining indexpack support
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/index_pack.cc
  kythe/cxx/extractor/index_pack.h
  kythe/cxx/extractor/index_pack_test.cc
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/shuck_main.cc
  kythe/cxx/tools/static_claim_main.cc
  kythe/docs/BUILD
  kythe/docs/kythe-compilation-database.txt
  kythe/docs/kythe-index-pack.txt
  kythe/docs/kythe-kzip.txt
  kythe/go/platform/indexpack/BUILD
  kythe/go/platform/indexpack/indexpack.go
  kythe/go/platform/indexpack/indexpack_test.go
  kythe/go/platform/kcd/packdb/BUILD
  kythe/go/platform/kcd/packdb/packdb.go
  kythe/go/platform/kcd/packdb/packdb_test.go
Labels: cla: yes

#4078 build: update to Go 1.13
  go.mod
  setup.bzl
Labels: build, cla: yes

#4079 ci(buildbot): find go tool other than self for fallback
  kythe/release/appengine/buildbot/go
Labels: cla: yes

#4080 chore: tidy go.{mod,sum} files
  external.bzl
  go.mod
  go.sum
Labels: cla: yes

#4081 fix: be more precise for ijwb targets
  kythe/java/com/google/devtools/kythe/analyzers/indexer.bazelproject
Labels: cla: yes

#4082 fix(java): handle more null data from java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#4083 fix(extractors): Don't include kzip creation time in kzip
  kythe/go/platform/kzip/kzip.go
Labels: cla: yes

#4084 feat(kzip): add function for merging multiple KzipInfos together
  kythe/go/platform/kzip/info/BUILD
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
Labels: cla: yes

#4085 fix(extractor): Don't include time in kzips for java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#4086 fix(extractor): Set cxx extractor kzip times to a constant
  kythe/cxx/common/kzip_writer.cc
Labels: cla: yes

#4087 fix(go): Change action go bazel extractor runs on
  kythe/extractors/BUILD
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
  kythe/go/util/tools/print_extra_action/BUILD
  kythe/release/release.BUILD
Labels: cla: yes

#4089 fix: remove unused load statement
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
Labels: cla: yes

#4092 typescript: index inputs that contain errors
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/compilefail.ts
  kythe/typescript/testdata/tsconfig.for.tests.json
Labels: buildbot, cla: yes

#4093 Port remaining uses of kindex_tool to kzip and remove it
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/kindex_repo_test.header
  kythe/cxx/indexer/cxx/testdata/kindex_repo_test.header2
  kythe/cxx/indexer/cxx/testdata/kindex_repo_test.main
  kythe/cxx/indexer/cxx/testdata/kindex_repo_test.unit
  kythe/cxx/indexer/cxx/testdata/kindex_repo_test.verify
  kythe/cxx/indexer/cxx/testdata/kindex_test.header
  kythe/cxx/indexer/cxx/testdata/kindex_test.main
  kythe/cxx/indexer/cxx/testdata/kindex_test.unit
  kythe/cxx/indexer/cxx/testdata/kindex_test.verify
  kythe/cxx/indexer/cxx/testdata/test_kindex.sh
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/kindex_tool_main.cc
  kythe/cxx/tools/static_claim_main.cc
  kythe/cxx/tools/testdata/BUILD
  kythe/cxx/tools/testdata/claim_test_1.kindex_UNIT
  kythe/cxx/tools/testdata/claim_test_1.kzip_UNIT.json
  kythe/cxx/tools/testdata/claim_test_2.kindex_UNIT
  kythe/cxx/tools/testdata/claim_test_2.kzip_UNIT.json
  kythe/cxx/tools/testdata/java.kindex_UNIT
  kythe/cxx/tools/testdata/java.kindex_cf28b786fa21d0c45156e8011ac809afc454703fa03d767a5aeeed382f902795
  kythe/cxx/tools/testdata/test_claim_tool_kindex.sh
  kythe/cxx/tools/testdata/test_claim_tool_kzip.sh
  kythe/cxx/tools/testdata/test_kindex_tool.sh
Labels: cla: yes

#4094 fix: add additional logging info to serving read errors
  kythe/go/serving/xrefs/xrefs.go
Labels: cla: yes

#4096 feat(kzip info): add option to read compilation units in parallel
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/tools/kzip/infocmd/BUILD
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
Labels: cla: yes

#4095 fix(kzip info): determine unit corpus and file language more robustly
  kythe/go/platform/kzip/info/BUILD
  kythe/go/platform/kzip/info/info.go
Labels: cla: yes

#4097 fix(cxx_indexer): emit references to dependent names based on name, not location
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/template/template_depname_path_graph.cc
  kythe/cxx/indexer/cxx/type_map.cc
Labels: cla: yes

#4064 Clarify documentation of vname root and path
  kythe/docs/kythe-storage.txt
  kythe/docs/kythe-uri-spec.txt
  kythe/docs/schema/schema.txt
  kythe/proto/storage.proto
Labels: buildbot, cla: yes

#4098 fix(proto_indexer): proto fields have subkind "field"
  kythe/cxx/indexer/proto/proto_graph_builder.cc
  kythe/cxx/indexer/proto/testdata/basic/message-fields.proto
Labels: cla: yes

#4100 fix: remove extraneous ws
  kythe/proto/storage.proto
Labels: cla: yes

#4101 feat(java_common): add forwarding method for setPathFactory
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
Labels: cla: yes

#4103 fix(java_common): cufs shares FileDataProvider and should not close it
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes

#4104 fix(java_common): adjust case when getting default format
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#4105 feat(typescript): Support AngularTemplateCompile mnemonic
  kythe/extractors/BUILD
  kythe/extractors/bazel/README.md
  kythe/release/release.BUILD
Labels: cla: yes

#4106 fix(java_common): normalize paths before looking them up
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes

#4107 chore: Use consistent casing for subcommand c.Fail
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
  kythe/go/extractors/config/runextractor/compdbcmd/compdbcmd.go
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/filtercmd/filtercmd.go
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes
