Repository kythe/kythe, pull requests merged in 2019-02, with the labels that each got.

#3422 Move LLVM dependency to an external repository
  external.bzl
  kythe/cxx/extractor/BUILD
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/tools/fyi/BUILD
  third_party/llvm/BUILD
  third_party/llvm/README.google
  third_party/llvm/src/BUILD
  third_party/llvm/src/clang_builtin_headers.cc
  tools/build_rules/llvm/BUILD
  tools/build_rules/llvm/cmake_defines.bzl
  tools/build_rules/llvm/cmakedefines/BUILD
  tools/build_rules/llvm/cmakedefines/cmakedefines.go
  tools/build_rules/llvm/configure_file.bzl
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_deps.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
  tools/modules/BUILD
  tools/modules/abspath.sh
  tools/modules/check.sh
  tools/modules/update.sh
  tools/modules/versions.sh
Labels: cla: yes

#3424 fix(web_api): properly marshal protos with jsonpb
  kythe/go/services/web/web.go
Labels: cla: yes

#3426 build: move kythe/build to kythe/extractors
  kythe/examples/bazel/kythe-index.sh
  kythe/extractors/BUILD
  kythe/extractors/bazel/extract.sh
  kythe/extractors/extractors.bzl
  kythe/web/site/examples.md
Labels: cla: yes

#3428 feat: optionally use a default VName if no rules match
  kythe/cxx/common/file_vname_generator.cc
  kythe/cxx/common/file_vname_generator.h
  kythe/cxx/common/file_vname_generator_test.cc
Labels: cla: yes

#3427 Add support in the C++ extractor for including build_config in BuildDetails
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/extractor/testdata/BUILD
  kythe/cxx/extractor/testdata/build_config.UNIT
  kythe/cxx/extractor/testdata/build_config.cc
  kythe/cxx/extractor/testdata/test_build_config.sh
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/kindex_tool_main.cc
Labels: cla: yes

#3429 build: update to tagged versions of stringset and shell
  external.bzl
  go.mod
  go.sum
  tools/build_rules/shims.bzl
Labels: build, buildbot, cla: yes

#3433 build: update to a tagged version of the go-cmp module
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3434 build: update to a tagged version of the Go zstd module
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3435 build: update to a tagged version of the Go etree module
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3425 feat(filetree): structured entries in DirectoryReply
  kythe/go/services/filetree/BUILD
  kythe/go/services/filetree/filetree.go
  kythe/go/serving/filetree/BUILD
  kythe/go/serving/filetree/filetree.go
  kythe/proto/filetree.proto
  kythe/proto/filetree_go_proto/filetree.pb.go
Labels: cla: yes

#3437 feat(cxx_indexer): include build/config fact on anchors when present
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/build_config.cc
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#3438 build: use default cc_configure
  .bazelrc
  WORKSPACE
  kythe/go/extractors/gcp/bazel/Dockerfile
  kythe/web/site/getting-started.md
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/cpp/CROSSTOOL.tpl
  tools/cpp/clang_configure.bzl
  tools/cpp/empty.cc
  tools/cpp/include/bits/c++config.h
  tools/docker/Dockerfile
Labels: cla: yes

#3443 fix(docs): clean up LLVM docs for #3441
  kythe/web/site/getting-started.md
Labels: cla: yes

#3444 feat: pass-through build config in pipeline
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
  kythe/go/serving/xrefs/assemble/assemble.go
  kythe/go/util/schema/facts/facts.go
Labels: cla: yes, post-processing

#3442 fix: remove an obsolete test case
  external.bzl
  go.mod
  go.sum
  kythe/go/extractors/govname/govname_test.go
Labels: buildbot, cla: yes

#3445 build: update to a tagged version of the Go protobuf module
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3446 docs: update the macOS instructions for #3439
  kythe/web/site/getting-started-macos.md
Labels: buildbot, cla: yes

#3447 feat(llvm): update LLVM to r353272
  kythe/cxx/extractor/path_utils.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3448 build: fix broken govname_test
  external.bzl
  go.mod
  go.sum
  kythe/go/extractors/govname/govname_test.go
Labels: cla: yes

#3449 feat(api): add DecorationsRequest filter for build config
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes

#3450 feat(columnar): support build_config filtering of columnar decorations
  kythe/go/serving/pipeline/beam_integration_test.go
  kythe/go/serving/pipeline/encoding.go
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/columnar/columnar_encoding.go
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: cla: yes

#3452 chore(docs): remove last mentions of tools/modules/update.sh
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/bazel/Dockerfile
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/cache-llvm.sh
  kythe/release/appengine/buildbot/master/master.cfg.template
  kythe/web/site/getting-started.md
Labels: cla: yes

#3453 ci(buildbot): update Go compiler to 1.11.5
  kythe/release/appengine/buildbot/Dockerfile
Labels: build, cla: yes

#3431 chore: cleanup old revisions from go.sum
  external.bzl
  go.mod
  go.sum
  third_party/go/BUILD
  third_party/go/googleapis_gax.BUILD
Labels: cla: yes

#3454 feat: add extract_kzip tool to release archive
  kythe/release/BUILD
  kythe/release/README.md
Labels: cla: yes, release

#3455 chore: update setup_release.sh to use clog-cli
  RELEASES.md
  kythe/release/setup_release.sh
Labels: cla: yes, release

#3457 chore: point old refs from phabricator to github issues
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_class_base_recurring.cc
  kythe/cxx/indexer/cxx/testdata/template/template_blame_member.cc
  kythe/cxx/indexer/cxx/testdata/template/template_blame_pspec_member.cc
  kythe/cxx/indexer/cxx/testdata/template/template_fn_member_spec_defn.cc
  kythe/cxx/tools/testdata/BUILD
  kythe/cxx/verifier/verifier.cc
  kythe/go/indexer/BUILD
  kythe/go/indexer/indexer.go
  kythe/go/util/kytheuri/uri_test.go
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/indexer_source_root_test.sh
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericComments.java
Labels: cla: yes

#3458 release(dev): add stricter checking of commit messages
  .commitlintrc.js
Labels: cla: yes, release

#3456 chore: setup release v0.0.30
  RELEASES.md
  kythe/release/BUILD
  kythe/release/setup_release.sh
Labels: cla: yes, release

#3460 test: add failing test case for #3459
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AnnotationComments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
Labels: cla: yes

#3461 chore: remove usage of deprecated `Lists.newArrayList()`
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/JavacUtil.java
  kythe/java/com/google/devtools/kythe/platform/shared/MetadataLoaders.java
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/JvmGraphTest.java
Labels: cla: yes

#3464 build: update io_kythe_lang_proto to e9b68f17
  external.bzl
Labels: cla: yes

#3465 feat(cxx_common): Add ref imports edge field
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
Labels: cla: yes

#3260 use the first token in the file as the module link
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/index_module/index.ts
  kythe/typescript/testdata/module.ts
  kythe/typescript/testdata/module_with_function.ts
  kythe/typescript/testdata/reexport_importer.ts
  kythe/typescript/testdata/reexporter.ts
Labels: buildbot, cla: yes

#3466 TypeScript 3.3
  kythe/typescript/package.json
  kythe/typescript/yarn.lock
Labels: buildbot, cla: yes

#3470 build(extraction): add custom Java proto toolchain with 'annotate_code'
  kythe/extractors/BUILD
Labels: build, cla: yes, extraction

#3471 docs: update link to Riegeli writer options document
  kythe/go/util/riegeli/golden_test.go
  kythe/go/util/riegeli/riegeli.go
Labels: cla: yes, documentation

#3467 fix(typescript_indexer): obey VNames that come in from the input
  kythe/typescript/indexer.ts
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#3463 test: add tests for line comments on methods
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AnnotationComments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
Labels: cla: yes

#3472 build: update github.com/google/subcommands to tagged version 1.0.1
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3473 build: update github.com/pkg/errors to tagged version v0.8.1
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3474 build: update github.com/google/go-querystring to tagged version v1.0.0
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3475 build: update github.com/pierrec/lz4 to tagged v2.0.8
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3476 build: update go.opencensus.io to tagged version v0.15.0
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3478 build: update github.com/nwaples/rardecode to tagged version v1.0.0
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3479 build: remove unused dependency on github.com/google/go-github
  external.bzl
  go.mod
  go.sum
  third_party/go/BUILD
Labels: buildbot, cla: yes

#3480 chore(ts_indexer): Use more standard syntax for lambda
  kythe/typescript/test.ts
Labels: cla: yes

#3485 build: update github.com/mholt/archiver to tagged release v3.1.1
  external.bzl
Labels: buildbot, cla: yes

#3484 docs: clarify the comment on the CompilationUnit.v_name field
  kythe/proto/analysis.proto
Labels: buildbot, cla: yes

#3488 build: update package gopkg.in/yaml.v2 to tagged version v2.2.2
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3491 Make kythe/cxx/common/path_utils.cc relativize against root dir.
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
  kythe/cxx/common/path_utils_test.cc
Labels: buildbot, cla: yes

#3486 build: use github.com/google/uuid for Go UUID generation
  external.bzl
  go.mod
  go.sum
  kythe/go/extractors/config/runextractor/cmakecmd/BUILD
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
  kythe/go/extractors/config/runextractor/compdbcmd/BUILD
  kythe/go/platform/indexpack/BUILD
  kythe/go/platform/indexpack/indexpack.go
  third_party/go/uuid.BUILD
Labels: buildbot, cla: yes

#3492 build: update github.com/google/orderedcode to tagged version v0.0.1
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3489 fix: address part of #3459 by claiming comments for annotation lines
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AnnotationComments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
Labels: cla: yes

#3493 build(bazel): support upcoming Bazel 0.23.0 release
  WORKSPACE
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: build, cla: yes

#3487 feat(tooling): migrate kythe CLI to new filetree API
  kythe/go/services/cli/command_ls.go
Labels: API, CLI, cla: yes

#3495 Use std::string and string_view-like APIs more uniformly
  external.bzl
  kythe/cxx/common/file_vname_generator.cc
  kythe/cxx/indexer/cxx/GraphObserver.h
Labels: cla: yes

#3490 Make pipeline more tolerant to some errors (affects write_tables tool).
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/pipeline.go
Labels: buildbot, cla: yes

#3494 test(java_indexer): add test for xrefs between java and proto extensions
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto2.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/testdata2.proto
Labels: cla: yes

#3498 Post-std::string clean up moving an unnecessarily inline function out of line
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/GraphObserver.cc
  kythe/cxx/indexer/cxx/GraphObserver.h
Labels: cla: yes

#3481 fix two warnings
  kythe/typescript/indexer.ts
  package.json
Labels: buildbot, cla: yes

#3419 Add KytheFS + configure kythe_langserver...
  .kythe_settings.json
  README.langserver
  external.bzl
  kythe/go/serving/tools/kythefs/BUILD
  kythe/go/serving/tools/kythefs/kythefs.go
  third_party/go/go_fuse.BUILD
Labels: buildbot, cla: yes

#3496 fix: propagating a downstream fix on typescript
  kythe/typescript/test.ts
Labels: cla: yes

#3499 feat(extraction): add Bazel extraction Docker image
  kythe/data/BUILD
  kythe/data/vnames.bzl
  kythe/extractors/BUILD
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/README.md
  kythe/extractors/bazel/extract.sh
  kythe/extractors/bazel/extractors.BUILD
  kythe/extractors/bazel/extractors.WORKSPACE
  kythe/extractors/bazel/extractors.bazelrc
  tools/build_rules/docker.bzl
Labels: cla: yes, extraction

#3500 refactor(cxx_indexer): DependentName nodes and edges
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/template/template_dependent_dtor.cc
  kythe/cxx/indexer/cxx/testdata/template/template_dependent_dtor_qualified.cc
Labels: cla: yes

#3503 chore: move most of kythe/go/extractors/gcp to kythe/extractors/gcp
  kythe/extractors/gcp/README.md
  kythe/extractors/gcp/examples/BUILD
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/helloworld/BUILD
  kythe/extractors/gcp/examples/helloworld/helloworld.go
  kythe/extractors/gcp/examples/helloworld/helloworld.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/extractors/gcp/examples/restcheck/BUILD
  kythe/extractors/gcp/examples/restcheck/rest_auth_check.go
  kythe/go/extractors/gcp/config/BUILD
  kythe/go/extractors/gcp/config/converter_test.go
Labels: cla: yes

#3507 fix: remove the smallest of characters
  kythe/typescript/test.ts
Labels: cla: yes

#3501 chore: remove older style bazel gcp extraction
  kythe/go/extractors/gcp/bazel/BUILD
  kythe/go/extractors/gcp/bazel/Dockerfile
Labels: cla: yes

#3505 fix: some documentation fixes for bazel gcp
  kythe/extractors/bazel/README.md
  kythe/extractors/bazel/extract.sh
  kythe/extractors/gcp/README.md
Labels: cla: yes

#3497 Beam: support reading input files from a directory.
  kythe/go/serving/pipeline/beamio/entries.go
  kythe/go/serving/pipeline/beamio/entries_test.go
  kythe/go/serving/tools/write_tables/write_tables.go
Labels: buildbot, cla: yes

#3502 fix: go style errors introduced in previous commit
  README.langserver.md
  kythe/go/serving/tools/kythefs/kythefs.go
Labels: buildbot, cla: yes

#3508 fix: downstream fix to provider syntax
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3513 fix(cxx_common): anticipate changes in Bison 3.3 syntax
  kythe/cxx/verifier/assertions.yy
  kythe/web/site/getting-started.md
Labels: cla: yes

#3509 feat(extraction): add generic GCB Bazel extraction config
  kythe/extractors/bazel/README.md
  kythe/extractors/gcp/bazel/README.md
  kythe/extractors/gcp/bazel/bazel.yaml
Labels: cla: yes, extraction

#3511 feat(cxx_common): proto plugin to embed metadata in C++ headers
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/proto_metadata_plugin.cc
  kythe/extractors/BUILD
Labels: C++, cla: yes, extraction

#3512 feat(api): add CrossReferencesRequest filter for build config
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/xrefs/xrefs.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes

#3515 fix(dev): use POSIX safe flags for tr
  kythe/data/vnames.bzl
Labels: buildbot, cla: yes

#3518 fix: downstream change from java bazel
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3517 fix(dev): provide a starting point for the find command
  kythe/docs/asciidoc.bzl
Labels: buildbot, cla: yes

#3519 fix(dev): include brotli and leveldb in the macOS package list
  kythe/web/site/getting-started-macos.md
Labels: buildbot, cla: yes

#3522 build: update Apache Beam to 2a412352
  external.bzl
  go.mod
  go.sum
  kythe/go/serving/pipeline/beamio/BUILD
  kythe/go/serving/pipeline/beamio/beamio.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/buffer.go
  third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
Labels: build, cla: yes

#3525 chore(dev): update github.com/golang/snappy to tagged release v0.0.1
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3524 fix: pin gradle/maven extraction to jdk8 instead of using gcb image
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/constants/constants.go
  kythe/go/extractors/gcp/config/converter_test.go
  kythe/go/extractors/gcp/config/gradle.go
  kythe/go/extractors/gcp/config/maven.go
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
Labels: cla: yes

#3523 feat(api): add build configurations per FileTree entry
  kythe/proto/filetree.proto
  kythe/proto/filetree_go_proto/filetree.pb.go
Labels: API, cla: yes

#3527 feat(serving): add build configs to FileTree serving data
  kythe/go/serving/filetree/filetree.go
  kythe/go/serving/pipeline/BUILD
  kythe/go/serving/pipeline/filetree.go
  kythe/go/serving/pipeline/filetree_test.go
  kythe/proto/filetree.proto
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
Labels: cla: yes, post-processing, storage

#3530 fix(build): remove duplicate src paths in java_extract_kzip
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3529 build: update Bazel rules_go to 0.17.0
  external.bzl
  kythe/go/util/riegeli/riegeli_test.proto
  kythe/go/util/riegeli/riegeli_test_go_proto/riegeli_test.pb.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/analysis_service.proto
  kythe/proto/analysis_service_go_proto/analysis_service.pb.go
  kythe/proto/buildinfo.proto
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim.proto
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common.proto
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx.proto
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver.proto
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset.proto
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore.proto
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/extraction_config.proto
  kythe/proto/extraction_config_go_proto/extraction_config.pb.go
  kythe/proto/filecontext.proto
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree.proto
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/go.proto
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph.proto
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/graph_serving.proto
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  kythe/proto/identifier.proto
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal.proto
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java.proto
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link.proto
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline.proto
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/repo.proto
  kythe/proto/repo_go_proto/repo.pb.go
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service.proto
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage.proto
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/storage_service.proto
  kythe/proto/storage_service_go_proto/storage_service.pb.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving.proto
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
  setup.bzl
Labels: build, cla: yes

#3533 fix(cxx_extractor): remove deprecated and now-unused field
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/testdata/altroot_altpath_file.UNIT
  kythe/cxx/extractor/testdata/arm.UNIT
  kythe/cxx/extractor/testdata/build_config.UNIT
  kythe/cxx/extractor/testdata/has_include_test.UNIT
  kythe/cxx/extractor/testdata/indirect_has_include_test.UNIT
  kythe/cxx/extractor/testdata/main_source_file_env_dep_with.UNIT
  kythe/cxx/extractor/testdata/main_source_file_env_dep_without.UNIT
  kythe/cxx/extractor/testdata/main_source_file_no_env_dep_with.UNIT
  kythe/cxx/extractor/testdata/main_source_file_no_env_dep_without.UNIT
  kythe/cxx/extractor/testdata/metadata.UNIT
  kythe/cxx/extractor/testdata/modules.UNIT
  kythe/cxx/extractor/testdata/transcript_main.UNIT
  kythe/cxx/tools/kindex_tool_main.cc
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#3532 fix(pipeline): beam output path can contain a filesystem scheme
  kythe/go/serving/pipeline/beamio/leveldb.go
  kythe/go/serving/pipeline/beamio/leveldb_test.go
Labels: buildbot, cla: yes

#3531 feat(cxx_indexer): add tests and fix support for C++/proto metadata references
  kythe/cxx/common/protobuf_metadata_file.cc
  kythe/cxx/extractor/cxx_extractor_main.cc
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/proto.cc
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#3537 feat(go_platform): add kzip subcommand for creating trivial kzips
  kythe/extractors/gcp/README.md
  kythe/go/platform/tools/kzip/BUILD
  kythe/go/platform/tools/kzip/createcmd/BUILD
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/kzip.go
  kythe/go/platform/tools/kzip/mergecmd/BUILD
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#3534 fix: pin gcp extraction example and tests to :stable
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/constants/constants.go
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
Labels: cla: yes

#3536 fix: normalize env vars used for input and output to gcp extraction
  kythe/extractors/gcp/README.md
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
Labels: cla: yes

#3535 fix: quiet the error printing in gcp
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/gcp/config/gradle.go
  kythe/go/extractors/gcp/config/maven.go
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
Labels: cla: yes

#3539 fix: remove javac-extractor.err and .out printing from javac-wrapper.sh
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/extractors/gcp/config/gradle.go
  kythe/go/extractors/gcp/config/maven.go
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
  kythe/release/release_test.sh
Labels: cla: yes, extraction, gradle, maven

#3538 feat(kzip_create): allow embedding details messages in kzips
  kythe/go/platform/tools/kzip/createcmd/BUILD
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
Labels: cla: yes

#3541 refactor(build): move cc proto verifier tests into a bzl macro
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
Labels: cla: yes

#3543 chore(cleanup): delete the obsolete kindex_file_generator
  kythe/go/platform/tools/kindex_file_generator/BUILD
  kythe/go/platform/tools/kindex_file_generator/kindex_file_generator.go
Labels: cla: yes

#3542 feat(kzip_create): allow complete specification of a compilation unit
  kythe/go/platform/tools/kzip/createcmd/BUILD
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/createcmd/flag.go
Labels: cla: yes

#3544 fix(kzip_create): implement flag.Getter for all flat types
  kythe/go/platform/tools/kzip/createcmd/flag.go
Labels: cla: yes

#3545 fix: add support for bazel BuildSteps generation
  kythe/extractors/gcp/README.md
  kythe/extractors/gcp/bazel/README.md
  kythe/extractors/gcp/bazel/bazel.yaml
  kythe/extractors/gcp/examples/bazel.yaml
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/constants/constants.go
  kythe/go/extractors/gcp/config/BUILD
  kythe/go/extractors/gcp/config/bazel.go
  kythe/go/extractors/gcp/config/common.go
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/extractors/gcp/config/converter_test.go
  kythe/go/extractors/gcp/config/testdata/bazel-multi.json
  kythe/go/extractors/gcp/config/testdata/bazel-multi.yaml
  kythe/go/extractors/gcp/config/testdata/bazel.json
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
  kythe/proto/repo.proto
  kythe/proto/repo_go_proto/repo.pb.go
Labels: cla: yes

#3546 chore: remove mkdir step from gcp extraction
  kythe/extractors/gcp/examples/bazel.yaml
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/gcp/config/common.go
  kythe/go/extractors/gcp/config/testdata/bazel-multi.yaml
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
Labels: cla: yes

#3547 chore: allow user-provided bazelrc
  .bazelrc
  .gitignore
Labels: cla: yes

#3548 build: update Bazel rules_go to 0.17.1
  WORKSPACE
  setup.bzl
Labels: build, cla: yes

#3552 build: use Args objects to format action arguments
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/java_verifier_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: build, cla: yes

#3554 build: remove unnecessary params file in java_proto_verifier_test
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: build, cla: yes

#3555 fix(dev): update the pinned version of Gazelle
  setup.bzl
Labels: buildbot, cla: yes

#3556 fix: tag google cloud builds
  kythe/extractors/gcp/examples/bazel.yaml
  kythe/extractors/gcp/examples/gradle.yaml
  kythe/extractors/gcp/examples/guava-android-mvn.yaml
  kythe/extractors/gcp/examples/guava-mvn.yaml
  kythe/extractors/gcp/examples/mvn.yaml
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/extractors/gcp/config/testdata/bazel-multi.yaml
  kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/gradle.yaml
  kythe/go/extractors/gcp/config/testdata/guava-mvn.json
  kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
  kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
  kythe/go/extractors/gcp/config/testdata/mvn.yaml
Labels: cla: yes

#3559 fix(guava): allow using guava along with modules
  external.bzl
Labels: cla: yes

#3558 build: update github.com/jmhodges/levigo to tagged release v1.0.0
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3560 fix(docs): clarify VName documentation in analysis.proto
  kythe/proto/analysis.proto
Labels: cla: yes

#3562 build: replace use of deprecated Gazelle rule
  tools/build_rules/shims.bzl
Labels: build, cla: yes

#3564 fix(tooling): migrate kythefs from deprecated FileTree API
  kythe/go/serving/tools/kythefs/kythefs.go
Labels: API, CLI, cla: yes, cleanup

#3566 fix(tooling): migrate 'kythe ls' filters from deprecated FileTree API
  kythe/go/services/cli/command_ls.go
Labels: API, CLI, cla: yes, cleanup

#3561 feat(java_indexer): add MarkedSources for array/generic tapp nodes
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: cla: yes, indexing, java

#3565 build: update github.com/googleapis/gax-go to tagged release v1.0.1
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes
