Repository kythe/kythe, pull requests merged in 2019-10, with the labels that each got.

#4110 fix(tooling): check error before result
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#4111 fix(tooling): do not consider the empty kzip an error
  kythe/go/platform/kzip/kzip.go
Labels: cla: yes

#4113 build(bazel): disable persistent worker mode for TypeScript
  .bazelrc
Labels: cla: yes

#4114 feat(extraction): add proto definition for VName rewrite rules
  kythe/go/util/vnameutil/BUILD
  kythe/go/util/vnameutil/rewrite.go
  kythe/proto/BUILD
  kythe/proto/storage.proto
  kythe/proto/storage_go_proto/storage.pb.go
Labels: cla: yes

#4116 feat(extraction): add support to parse VName rules from any io.Reader
  kythe/go/util/vnameutil/rewrite.go
Labels: cla: yes

#4117 feat(extraction): export VNameRewriteRule proto conversion function
  kythe/go/util/vnameutil/rewrite.go
Labels: cla: yes

#4115 feat(java_indexer): Initial path-based JavaFileManager implementation
  kythe/java/com/google/devtools/kythe/platform/java/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4118 drop a log line that always prints
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4119 fix(java): javadoc format fix
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4120 fix(go extractor): fix invalid Details messages for packages
  kythe/go/extractors/golang/golang.go
Labels: cla: yes

#4121 style: format Python code
  kythe/proto/generate_go_protobufs.py
  kythe/release/appengine/buildbot/master/master.cfg
  tools/build_rules/verifier_test/unbundle.py
Labels: cla: yes

#4122 feat(java_indexer): command line option to use path-based file manager
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
  kythe/java/com/google/devtools/kythe/platform/java/JavacAnalysisDriver.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4124 fix: cleanup a few pylint warnings
  kythe/proto/generate_go_protobufs.py
Labels: cla: yes

#4123 fix(java_indexer): use Java 8 method instead of Java 9 method
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4125 chore: fix a typo in the openjdk11 extractor script
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes

#4126 feat(java_extractor): use Optional<Location> and allow updating it
  kythe/java/com/google/devtools/kythe/extractors/java/InputUsageRecord.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#4127 fix(java_common): switch to using java.util.Optional over Guava
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#4130 fix(java_extractor): include working directory in extracted proto
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#4132 feat(go_indexer): emit line comments when no preferred doc is present
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/comments.go
Labels: cla: yes, go, indexing

#4133 feat(java_indexer): move path-based file manager config to base class
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
Labels: cla: yes

#4134 feat(go_indexer): emit parameter comments
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/comments.go
Labels: cla: yes, go, indexing

#4131 fix(jdk_extractor): bazel runfiles no longer expect the workspace name
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes

#4136 fix(java_indexer): use Path to resolve metadata (fixes #4135)
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java
Labels: cla: yes

#4137 fix(java_indexer): cast to base with asPath to support JDK8
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#4140 fix: EntrySet::emitted becomes volatile
  kythe/java/com/google/devtools/kythe/analyzers/base/EntrySet.java
Labels: cla: yes

#4142 fix(release): Make sure clog is installed
  kythe/release/setup_release.sh
Labels: cla: yes

#4144 chore: fix setup_release.sh commit message
  kythe/release/setup_release.sh
Labels: cla: yes

#4143 release: v0.0.31
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4145 fix(java): record EntrySet emission before calling emitter
  kythe/java/com/google/devtools/kythe/analyzers/base/EntrySet.java
Labels: cla: yes

#4148 fix(docs): update note on Go stdlib corpus name
  kythe/docs/rfc/2967.md
Labels: cla: yes

#4149 docs: reserve all corpus names starting with "kythe"
  kythe/docs/kythe-storage.txt
Labels: cla: yes

#4151 build(bazel): support Bazel 1.1.0
  .bazelversion
  version.bzl
Labels: build, cla: yes

#4152 chore: remove unused proto message
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4150 chore(oss): Record required and source files
  kythe/go/platform/kzip/info/BUILD
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4153 chore: Don't reuse proto field name
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4155 chore: Count required inputs by their corpus
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4156 chore: Count sources by their required input vname corpus
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4158 Corp
  kythe/go/platform/kzip/info/info.go
Labels: cla: yes

#4157 feat(kzip info): default --read_concurrency to numcpu
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
Labels: cla: yes

#4159 chore: add a place to store kzip size in KzipInfo
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4161 chore: Record kzip size in KzipInfo
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
Labels: cla: yes

#4162 chore: Add sources without required inputs to kzip info count
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4163 feat(release): add extractors.bazelrc to release
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
  kythe/extractors/bazel/extractors.bazelrc
  kythe/release/BUILD
Labels: cla: yes

#4167 fix(tools): fix generate_compilation_database on macOS (#4166)
  tools/cpp/generate_compilation_database.sh
Labels: cla: yes

#4168 fix(bazel-extractor): fix permissions when extracting release archive
  kythe/extractors/bazel/Dockerfile
Labels: cla: yes

#4170 release: v0.0.32
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4172 doc: Add example for extracting non-kythe bazel repo
  kythe/web/site/examples.md
Labels: cla: yes

#4176 release: v0.0.33
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4177 feat(schema): support the generates relation between file nodes
  kythe/docs/schema/schema.txt
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: cla: yes, schema

#4178 feat(runextractor): pipe underlying cmake stderr to stderr
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
Labels: cla: yes

#4179 fix(jvm extractor): use class files as srcs, not jar
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
Labels: cla: yes
