Repository kythe/kythe, pull requests merged in 2019-01, with the labels that each got.

#3347 fix(json_proto): prepare for upstream case-sensitivity changes
  external.bzl
  kythe/cxx/common/json_proto.cc
Labels: cla: yes

#3349 fix(cxx): use static_cast to avoid sign-compare warning
  kythe/cxx/common/indexing/KytheCachingOutput.h
Labels: cla: yes

#3351 style: remove incorrect comment
  external.bzl
Labels: cla: yes

#3350 build: support Bazel version 0.22.0
  WORKSPACE
Labels: cla: yes

#3353 build: add target to construct a kzip archive for all Java test files
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/BUILD
Labels: cla: yes

#3309 docs(rfc): add an RFC for incorporating build description into the graph
  kythe/docs/rfc/2967.md
Labels: cla: yes

#3354 feat: add kzip cli tool
  kythe/go/platform/tools/kzip/BUILD
  kythe/go/platform/tools/kzip/kzip.go
  tools/build_rules/extraction.bzl
Labels: cla: yes, extraction

#3355 fix(rfc2967): clarify rules around config-dependent generated files
  kythe/docs/rfc/2967.md
Labels: cla: yes

#3356 fix: replace zipmerge with 'kzip merge'
  kythe/go/extractors/cmd/gotool/BUILD
  kythe/go/extractors/cmd/gotool/Dockerfile
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
  kythe/go/platform/tools/kzip/kzip.go
Labels: cla: yes

#3358 feat: add protobuf indexer to release
  external.bzl
  kythe/release/BUILD
  kythe/release/README.md
Labels: cla: yes, release

#3360 build: remove proto visibility from third_party/llvm
  kythe/BUILD
  kythe/cxx/extractor/BUILD
  third_party/llvm/src/BUILD
Labels: build, cla: yes

#3361 build: simplify cc_resources header inclusion
  third_party/llvm/src/BUILD
  third_party/llvm/src/clang_builtin_headers.cc
  tools/build_rules/cc_resources.bzl
Labels: cla: yes

#3363 feat(entrystream): support aggregating entries into an EntrySet
  kythe/go/platform/tools/entrystream/BUILD
  kythe/go/platform/tools/entrystream/entrystream.go
Labels: cla: yes

#3364 chore: remove unused bazel rule _go_verifier_test()
  kythe/go/indexer/testdata/go_indexer_test.bzl
Labels: cla: yes

#3365 chore: split java_verifier_test definition into separate file
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
  tools/build_rules/verifier_test/java_verifier_test.bzl
  tools/build_rules/verifier_test/jvm_verifier_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: cla: yes

#3366 fix: add docs on extracting non-github repo
  kythe/go/platform/tools/kzip_validator/kzip_validator.go
Labels: cla: yes

#3367 fix: don't use a string pointer when we don't have to
  kythe/go/extractors/validation/validation.go
  kythe/go/platform/tools/kzip_validator/kzip_validator.go
Labels: cla: yes

#3368 fix: Prepare for a breaking change in clang
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
Labels: cla: yes

#3369 update llvm to r350964
  kythe/cxx/indexer/cxx/ImputedConstructorSupport.cc
  third_party/llvm/src/cxx_extractor_preprocessor_utils.cc
  tools/modules/versions.sh
Labels: cla: yes

#3371 build: fix buildbot scripts to work on darwin
  kythe/release/appengine/buildbot/bazel
  kythe/release/appengine/buildbot/cache-llvm.sh
Labels: cla: yes

#3370 refactor: move more path utils to llvm-free common library
  external.bzl
  kythe/cxx/common/BUILD
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
  kythe/cxx/common/path_utils_test.cc
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/path_utils.cc
  kythe/cxx/extractor/path_utils.h
  kythe/cxx/extractor/path_utils_test.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
Labels: cla: yes

#3372 fix: downstream clang-tidy fix
  kythe/cxx/indexer/cxx/ImputedConstructorSupport.cc
Labels: cla: yes

#3373 build: allow llvm cache location to be variable
  kythe/release/appengine/buildbot/cache-llvm.sh
Labels: cla: yes

#3374 Remove workaround for clang bug
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
Labels: buildbot, cla: yes

#3375 fix: use kzip tool instead of zipmerge for gcp extraction
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/config/kziptool/BUILD
  kythe/go/extractors/gcp/config/kziptool/Dockerfile
  kythe/go/extractors/gcp/examples/guava-mvn.yaml
Labels: cla: yes

#3378 fix(cxx_common): add enumerator for kDocUri fact
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
Labels: cla: yes

#3377 feat(gotool_extractor): canonicalize corpus names as package/repo roots
  kythe/go/extractors/cmd/gotool/BUILD
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
  kythe/go/extractors/cmd/gotool/gotool.go
  kythe/go/extractors/golang/golang.go
  kythe/go/extractors/govname/BUILD
  kythe/go/extractors/govname/govname.go
  kythe/go/extractors/govname/govname_test.go
Labels: cla: yes, extraction, go

#3382 chore: update ruby gems for website
  kythe/web/site/Gemfile.lock
Labels: cla: yes

#3381 refactor: more absl::string_view in path_utils
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
Labels: cla: yes

#3383 build: replace KytheJavaJar provider with standard JavaInfo
  tools/build_rules/verifier_test/java_verifier_test.bzl
  tools/build_rules/verifier_test/jvm_verifier_test.bzl
Labels: build, cla: yes

#3384 build: add java_proto_verifier_test Starlark rule
  external.bzl
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/testdata.proto
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3387 fix(testdata.proto): explicitly set java_package and dep on jsr250
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/testdata.proto
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3388 docs: typo
  kythe/go/extractors/govname/govname.go
Labels: cla: yes

#3389 style(bzl): cleanup java_proto_verifier_test implementation
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3392 build: remove use of legacy provider syntax
  tools/build_rules/extraction.bzl
Labels: cla: yes

#3390 fix: fix a typo in a comment
  kythe/go/platform/tools/kzip_validator/kzip_validator.go
Labels: cla: yes

#3391 build: allow non-tests to depend on java_proto_verifier_test kzips
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3393 fix: add documentation on the limitations of `build //...`
  kythe/web/site/getting-started.md
  kythe/web/ui/BUILD
Labels: cla: yes

#3380 fix(gotool_extractor): mark dep as missing if it cannot be built
  kythe/go/extractors/golang/golang.go
Labels: cla: yes, extraction, go

#3396 fix: add short hint in tools/modules/update on how force rebuild
  tools/modules/update.sh
Labels: cla: yes

#3398 build: add visibility for cxx/common:index_writer
  kythe/cxx/common/BUILD
Labels: cla: yes

#3397 Move leiningen to an external repository and remove the "local" attribute on genrule
  external.bzl
  kythe/web/ui/.gitignore
  kythe/web/ui/BUILD
  third_party/leiningen/lein_repo.bzl
Labels: cla: yes

#3400 fix(gotool_extractor): fix file paths with --canonicalize_package_corpus
  kythe/go/extractors/golang/golang.go
  kythe/go/extractors/govname/govname.go
  kythe/go/extractors/govname/govname_test.go
Labels: cla: yes, extraction, go

#3401 fix(docker_gotool_extractor): use stable output path, if possible
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
Labels: cla: yes

#3394 Fix govnames.json to reflect actual patterns.
  kythe/go/extractors/cmd/bazel/govnames.json
  kythe/go/extractors/cmd/bazel/govnames_test.json
Labels: buildbot, cla: yes

#3403 fix: adding example config for guava-android, distinct from guava
  kythe/go/extractors/gcp/README.md
  kythe/go/extractors/gcp/examples/guava-android-mvn.yaml
Labels: cla: yes

#3407 ci(buildbot): upgrade Bazel to 0.22.0
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3408 fix(go): use GoPackageInfo to resolve input import paths
  kythe/go/extractors/golang/golang.go
  kythe/go/extractors/govname/BUILD
  kythe/go/extractors/govname/govname.go
  kythe/go/extractors/govname/govname_test.go
  kythe/go/indexer/indexer.go
  kythe/go/indexer/indexer_test.go
  kythe/go/util/ptypes/ptypes.go
  kythe/proto/go.proto
  kythe/proto/go_go_proto/go.pb.go
Labels: cla: yes, extraction, go

#3409 fix: support pluginManagement in mvn.pom preprocessor
  kythe/go/extractors/config/preprocessor/modifier/modifier_test.go
  kythe/go/extractors/config/preprocessor/modifier/pom_xml_modifier.go
  kythe/go/extractors/config/preprocessor/modifier/testdata/child-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/modified-invalid-version-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/modified-wrong-source-version-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/modified-wrong-target-version-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/plugin-management-missing-version-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/plugin-management-pom.xml
  kythe/go/extractors/config/preprocessor/modifier/testdata/plugin-management-wrong-plugin-version-pom.xml
Labels: cla: yes

#3411 feat: add Typescript kzip extractor extra_action
  kythe/typescript/BUILD
Labels: cla: yes, extraction

#3413 feat(bazel_extractor): infer corpus from source files
  kythe/go/extractors/bazel/extractor.go
  kythe/go/extractors/bazel/settings.go
  kythe/typescript/BUILD
Labels: cla: yes, extraction

#3414 build: split vnames config by language with configurable corpus
  kythe/data/BUILD
  kythe/data/test_filevnames.sh
  kythe/data/vnames.bzl
  kythe/data/vnames.cxx.json
  kythe/data/vnames.java.json
  kythe/data/vnames.json
Labels: cla: yes

#3415 build: use common vnames config for Bazel example
  kythe/data/vnames.bzl
  kythe/examples/bazel/BUILD
  kythe/examples/bazel/bazel.WORKSPACE
  kythe/examples/bazel/kythe-index.sh
  kythe/examples/bazel/kythe_config.json
Labels: cla: yes

#3417 fix: remove unnecessary call to default_javac_opts
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3418 fix(bazel extractor): print file counts after handling source args
  kythe/go/extractors/bazel/extractor.go
Labels: cla: yes

#3420 fix(examples): fix a missing dependency from a docker rule
  kythe/examples/bazel/BUILD
Labels: cla: yes

#3421 build: aggregate extractor extra_actions into single BUILD package
  kythe/build/BUILD
  kythe/build/extractors.bzl
  kythe/cxx/extractor/BUILD
  kythe/data/BUILD
  kythe/data/vnames.go.json
  kythe/data/vnames_test.go.json
  kythe/examples/bazel/kythe-index.sh
  kythe/extractors/bazel/extract.sh
  kythe/go/extractors/cmd/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
  kythe/typescript/BUILD
  kythe/web/site/examples.md
Labels: cla: yes, extraction
