Repository kythe/kythe, pull requests merged in 2019-11, with the labels that each got.

#4164 refactor(typescript_indexer): allow to pass multiple files in indexer test
  kythe/typescript/test.ts
  package-lock.json
  package.json
Labels: buildbot, cla: yes

#4180 Migrate maven_jar usages to rules_jvm_external
  WORKSPACE
  external.bzl
  kythe/extractors/BUILD
  kythe/extractors/bazel/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/java/com/google/devtools/kythe/common/BUILD
  kythe/java/com/google/devtools/kythe/doc/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
  kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/javatests/com/google/devtools/kythe/doc/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/javatests/com/google/devtools/kythe/util/BUILD
  kythe/javatests/com/google/devtools/kythe/util/schema/BUILD
  setup.bzl
  third_party/go/BUILD
  third_party/guava/BUILD
  third_party/truth/BUILD
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: buildbot, cla: yes

#4182 Revert "fix(jvm extractor): use class files as srcs, not jar (#4179)"
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
Labels: cla: yes

#4184 chore(cxx): update LLVM to d3ec06d219788801380af1948c7f7ef9d3c6100b
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4187 feat(go_indexer): option to emit an edge for an anchor's semantic scope
  kythe/go/indexer/BUILD
  kythe/go/indexer/cmd/go_indexer/go_indexer.go
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/scopes.go
  kythe/go/indexer/testdata/go_indexer_test.bzl
Labels: cla: yes

#4185 chore(typescript_indexer): TypeScript 3.6 compat.
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4188 fix(java extractor): Handle source files in jars
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/src_in_jar/C1.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/src_in_jar/README
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/src_in_jar/pack.jar
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/src_in_jar/pack/C2.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/src_in_jar/pack2/C3.class
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/src_in_jar/pack2/C3.java
Labels: cla: yes

#4189 chore: remove usages of reflect.DeepEqual
  kythe/go/platform/analysis/proxy/BUILD
  kythe/go/platform/analysis/proxy/proxy_test.go
  kythe/go/storage/entryset/BUILD
  kythe/go/storage/entryset/entryset_test.go
Labels: cla: yes

#4190 fix(extractor): fix jsr250 path after #4180
  kythe/extractors/bazel/Dockerfile
Labels: cla: yes

#4191 fix(jvm extractor): use class files as srcs, not jar
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
Labels: cla: yes

#4165 feat(typescript_indexer): add references to imports of 3rd party modules
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/imports/import.ts
  kythe/typescript/testdata/imports/modules.d.ts
Labels: buildbot, cla: yes

#4192 feat(bazel extractor): put everything in the same corpus by default
  kythe/data/BUILD
  kythe/data/simple_vnames.json
  kythe/release/BUILD
  kythe/release/release.BUILD
Labels: cla: yes

#4193 feat(java_indexer): add `generates` edge to generated AutoValue sources
  kythe/java/com/google/devtools/kythe/analyzers/java/AutoValuePlugin.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
  kythe/java/com/google/devtools/kythe/analyzers/java/Plugin.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AutoValues.java
Labels: cla: yes

#4195 fix(kzip info): don't count compilation units by corpus
  kythe/go/platform/kzip/info/BUILD
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4196 fix(kzip info): trim extra spaces from error message
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/kzip/info/info_test.go
Labels: cla: yes

#4194 feat(java extractor): Include system modules in the compilation unit
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/system_modules/lib/jrt-fs.jar
  kythe/javatests/com/google/devtools/kythe/extractors/java/testdata/system_modules/lib/modules
Labels: cla: yes

#4200 Release v0.0.34
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4201 feat(serving): return known generators in DecorationsReply
  kythe/go/serving/xrefs/BUILD
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
Labels: cla: yes, serving

#4198 Improve CLI tool's display for truncated values
  kythe/go/services/cli/command_nodes.go
Labels: buildbot, cla: yes

#4199 Make verifier "?" output similar to goal form
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/assertion_ast.h
  kythe/cxx/verifier/assertions.cc
  kythe/cxx/verifier/testdata/just_file_node.dot
  kythe/cxx/verifier/testdata/regex_expected_error.txt
  kythe/cxx/verifier/testdata/singleton_inspect_expected_error.txt
  kythe/cxx/verifier/testdata/test_verifier_regex.sh
Labels: buildbot, cla: yes

#4202 chore(llvm): update to 5b9e4daef06dcfefc786737a32c8bbb5bd0fc5c4
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4203 chore(npm): run npm update to fix mem vulnerability
  package-lock.json
  package.json
  setup.bzl
Labels: cla: yes

#4204 feat(jvm_indexer): allow JVM nodes to be refined by corpus/root/path
  kythe/java/com/google/devtools/kythe/analyzers/base/CorpusPath.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/DESIGN.md
  kythe/java/com/google/devtools/kythe/analyzers/jvm/JvmGraph.java
Labels: cla: yes, java, schema

#4205 feat(java_indexer): plumb CorpusPaths for JVM nodes
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/KytheClassVisitor.java
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt
Labels: cla: yes, indexing, java

#3778 fix(release): include jsr250-api-1.0.jar in release archive
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/release/BUILD
Labels: cla: yes

#4206 release: v0.0.35
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4210 chore(java indexer): log filemanager exceptions
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
Labels: cla: yes

#4211 chore(java indexer): Handle null pointer
  kythe/java/com/google/devtools/kythe/platform/java/helpers/BlockAnonymousSignatureGenerator.java
Labels: cla: yes

#4212 Mirror all http_archives.
  external.bzl
Labels: buildbot, cla: yes

#4215 chore(llvm): update to revision 17e37ba57a69
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4216 fix(kzip): --encoding flag was previously ignored
  kythe/go/platform/tools/kzip/flags/encoding.go
Labels: cla: yes

#4217 build(bazel): support Bazel 1.2.0
  .bazelversion
  version.bzl
Labels: cla: yes

#4218 feat(java indexer): better support system modules
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
  kythe/java/com/google/devtools/kythe/platform/java/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
  kythe/java/com/google/devtools/kythe/platform/java/JavacAnalysisDriver.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4220 refactor(kzip info): allow composing other operations in kzip.Scan
  kythe/go/platform/kzip/info/info.go
Labels: cla: yes

#4221 fix(java indexer): fix startsWith check
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4222 chore(java indexer): Store absolute path
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4224 chore: fix typo
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4223 chore(java indexer): Use optional for possibly empty values
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
Labels: cla: yes

#4225 fix(java indexer): Clean up after exceptions
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
Labels: cla: yes

#4228 chore(site): fix README link
  kythe/web/site/examples.md
Labels: cla: yes
