Repository kythe/kythe, pull requests merged in 2019-04, with the labels that each got.

#3660 build: change '@io_kythe//' to '//' in newly-imported BUILD files
  kythe/cxx/extractor/proto/BUILD
  kythe/cxx/extractor/proto/testdata/proto_extractor_test.bzl
  kythe/cxx/extractor/textproto/BUILD
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/indexer/textproto/BUILD
  kythe/examples/bazel/kythe-index.sh
  kythe/go/extractors/proto/BUILD
Labels: cla: yes

#3659 build: remove kythe/lang-proto repo from buildbot
  kythe/release/appengine/buildbot/master/master.cfg
Labels: cla: yes

#3661 chore: minor improvements suggested by google3 analyzers
  kythe/cxx/extractor/proto/proto_extractor.cc
  kythe/cxx/indexer/proto/testdata/proto_verifier_test.bzl
  kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: cla: yes

#3662 chore: apply fixes from clang_tidy
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/extractor/CommandLineUtils.h
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/indexer/cxx/ImputedConstructorSupport.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
Labels: cla: yes

#3663 release: add proto extractor and textproto extractor/indexer
  kythe/release/BUILD
  kythe/release/README.md
Labels: cla: yes

#3664 chore: update github.com/minio/highwayhash to tagged release v1.0.0
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3666 feat: accumulate granular file counts of kzip contents
  kythe/go/extractors/validation/BUILD
  kythe/go/extractors/validation/validation.go
Labels: cla: yes

#3668 chore(go_indexer): move object MarkedSource impl to markedsource.go
  kythe/go/indexer/indexer.go
  kythe/go/indexer/markedsource.go
Labels: cla: yes, cleanup

#3669 feat(indexing): add LOOKUP_BY_TYPED kind to MarkedSource
  kythe/cxx/verifier/verifier.cc
  kythe/cxx/verifier/verifier.h
  kythe/proto/common.proto
  kythe/proto/common_go_proto/common.pb.go
Labels: cla: yes, indexing

#3670 fix: remove Option.D from compilation unit again
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#3672 chore: remove extraneous list instantiation
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
Labels: cla: yes

#3677 feat(proto_indexer): emit deprecation tags for proto fields
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
  kythe/cxx/indexer/proto/proto_graph_builder.cc
  kythe/cxx/indexer/proto/proto_graph_builder.h
  kythe/cxx/indexer/proto/testdata/BUILD
  kythe/cxx/indexer/proto/testdata/basic/deprecated.proto
Labels: cla: yes

#3678 fix(proto_indexer): empty deprecation message and addititional test case
  kythe/cxx/indexer/proto/proto_graph_builder.cc
  kythe/cxx/indexer/proto/testdata/basic/deprecated.proto
Labels: cla: yes

#3681 chore: add missing formatting directive in Go test
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#3682 chore: fix BUILD file formatting
  kythe/go/platform/tools/indexpack/BUILD
  kythe/go/serving/tools/kythefs/BUILD
Labels: cla: yes

#3683 chore: run google-java-format over .java sources
  kythe/java/com/google/devtools/kythe/analyzers/base/IndexerConfig.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java
  kythe/javatests/com/google/devtools/kythe/doc/MarkedSourceRendererTest.java
  kythe/javatests/com/google/devtools/kythe/util/QualifiedNameExtractorTest.java
Labels: cla: yes

#3685 chore: add missing copyright header
  kythe/cxx/indexer/proto/search_path.cc
  tools/arc/linter.sh
Labels: cla: yes

#3679 feat(tools): kzip can merge into the existing output file
  kythe/extractors/bazel/extract.sh
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
  kythe/go/platform/vfs/vfs.go
Labels: cla: yes

#3673 chore: refactor JavacOptionsUtils into mostly a builder format
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: cla: yes

#3686 fix(typescript_indexer): properly lookup file VNames
  kythe/typescript/indexer.ts
Labels: cla: yes, indexing, typescript

#3687 build: specify Java dependency on Any proto
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
Labels: cla: yes

#3688 chore: fix lint error
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
Labels: cla: yes

#3690 chore: add formatting directives to test failures
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#3689 feat(go_indexer): use LOOKUP_BY_TYPED MarkedSource child for variables
  kythe/go/indexer/markedsource.go
  kythe/go/indexer/testdata/code/funcdecl.go
  kythe/go/indexer/testdata/code/pkgvar.go
  kythe/go/indexer/testdata/types.go
Labels: cla: yes, go, indexing, structured documentation

#3691 chore: remove usage of deprecated com.google.common.base.Charsets
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java
Labels: cla: yes

#3692 feat(go_indexer): add deprecation facts for go
  kythe/go/indexer/BUILD
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/deprecation.go
  kythe/go/util/schema/facts/facts.go
Labels: cla: yes

#3693 fix(bazel): proto toolchain not guaranteed to support no_enforce_api_compatibility
  kythe/release/release.BUILD
Labels: cla: yes

#3694 fix: handle relative paths correctly in textproto and proto extractors
  kythe/cxx/extractor/proto/proto_extractor.cc
  kythe/cxx/extractor/textproto/BUILD
  kythe/cxx/extractor/textproto/testdata/BUILD
  kythe/cxx/extractor/textproto/testdata/subdir.UNIT
  kythe/cxx/extractor/textproto/testdata/subdir/subdir.pbtxt
  kythe/cxx/extractor/textproto/testdata/subdir/subdir.proto
  kythe/cxx/extractor/textproto/textproto_extractor.cc
Labels: cla: yes

#3667 feat(proto_indexer): add tests for oneof field xrefs
  WORKSPACE
  external.bzl
  kythe/cxx/indexer/cxx/testdata/proto/proto.cc
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/testdata.proto
Labels: cla: yes

#3695 refactor(cxx): move LoadFileOrDie() into a new file_utils library
  kythe/cxx/common/BUILD
  kythe/cxx/common/file_utils.cc
  kythe/cxx/common/file_utils.h
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/proto/BUILD
  kythe/cxx/extractor/proto/proto_extractor.cc
  kythe/cxx/extractor/textproto/BUILD
  kythe/cxx/extractor/textproto/textproto_extractor.cc
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/assertions.cc
Labels: cla: yes

#3697 fix(compdb_test): ignore log files intead of treating as kzip
  kythe/go/extractors/config/runextractor/compdb/compdb_test.go
Labels: cla: yes

#3696 feat(java_common): add utility to convert schema proto enums
  kythe/go/util/schema/BUILD
  kythe/go/util/schema/mkdata/mkdata.go
  kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/base/EdgeKind.java
  kythe/java/com/google/devtools/kythe/analyzers/base/NodeKind.java
  kythe/java/com/google/devtools/kythe/util/schema/BUILD
  kythe/proto/BUILD
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
Labels: cla: yes, java, schema

#3701 docs: fix alternate root example to match URI spec
  kythe/docs/kythe-uri-spec.txt
Labels: cla: yes

#3702 chore: replace deprecated Truth API usage
  kythe/javatests/com/google/devtools/kythe/util/PositionMappingsTest.java
Labels: cla: yes, cleanup

#3704 feat(schema): add schema proto representation of a Kythe Entry
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
Labels: cla: yes, schema

#3705 fix(cxx_indexer): use URI-friendly encoding for VName fields
  kythe/cxx/common/kythe_uri_test.cc
  kythe/cxx/indexer/cxx/GraphObserver.cc
Labels: cla: yes

#3707 feat(api): allow a semantic scope to be associated per decoration
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes
