Repository kythe/kythe, pull requests merged in 2019-07, with the labels that each got.

#3835 fix(typescript_indexer): point class type and values at the class name
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
Labels: buildbot, cla: yes

#3851 feat(go extractor): allow specifying go +build tags
  kythe/go/extractors/cmd/gotool/BUILD
  kythe/go/extractors/cmd/gotool/gotool.go
Labels: cla: yes

#3853 feat(go extractor image): add KYTHE_GO_BUILD_TAGS env variable
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
Labels: cla: yes

#3819 fix(typescript_indexer): differentiate signatures of static and instance members
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
  kythe/typescript/testdata/getter_setter.ts
Labels: buildbot, cla: yes

#3854 test(typescript_indexer): mark test tsconfig.json files
  kythe/typescript/test.ts
  kythe/typescript/testdata/tsconfig-files.for.tests.json
  kythe/typescript/testdata/tsconfig.for.tests.json
Labels: buildbot, cla: yes

#3852 feat(kzip): support both proto and JSON encodings in Java for compilations in kzips. Also move kzip testdata to common location.
  kythe/cxx/common/testdata/BUILD
  kythe/cxx/common/testdata/missing-pbunit.kzip
  kythe/cxx/common/testdata/missing-unit.kzip
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip_test.go
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipReader.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
Labels: cla: yes

#3856 fix(go): -tags is space-separated, not comma
  kythe/go/extractors/golang/packages.go
Labels: cla: yes

#3858 build(bazel): support Bazel 0.27.1
  .bazelversion
  version.bzl
Labels: cla: yes

#3859 fix(textproto): continue analysis even if schema comments are invalid
  kythe/cxx/indexer/textproto/analyzer.cc
Labels: cla: yes

#3860 fix(java): minor java changes as suggested by downstream analyzers
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
Labels: cla: yes

#3841 fix(typescript_indexer): Do not name scopes created by rvalues
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/rvalue.ts
Labels: buildbot, cla: yes

#3862 fix(java tests): apparently '_' is a keyword now
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java
Labels: cla: yes

#3861 fix(KZipWriterTest.java): remove previous kzip before writing new one
  kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
Labels: cla: yes

#3863 feat(typescript_indexer): reference modules in export statements
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/export.ts
Labels: buildbot, cla: yes

#3864 feat(typescript_indexer): add xrefs for declarations in objects
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/object.ts
Labels: buildbot, cla: yes

#3855 typescript: handle variables declared within for-loop initializer
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/for.ts
Labels: buildbot, cla: yes

#3823 typescript: handle constraints/bounds in generics
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/generic.ts
Labels: buildbot, cla: yes

#3873 feat(typescript_indexer): add support for indexing module decls
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/declare_module.d.ts
  kythe/typescript/testdata/namespace.ts
Labels: buildbot, cla: yes

#3866 refactor(typescript_indexer): reduce TODO error logging
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3865 feature(typescript_indexer): index binding element parameters
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/function.ts
Labels: buildbot, cla: yes

#3871 feat(typescript_indexer): index export equals and import equals nodes
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/equals_export.ts
  kythe/typescript/testdata/equals_import.ts
Labels: buildbot, cla: yes

#3875 build(bazel): support Bazel 0.28.0
  .bazelversion
  version.bzl
Labels: cla: yes

#3876 feat(build): add generic kzip_archive rule
  tools/build_rules/verifier_test/kzip_archive.bzl
Labels: cla: yes

#3878 Security
  package-lock.json
  package.json
Labels: cla: yes

#3872 feat(typescript_indexer): emit "overrides" edges for overriden methods
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
Labels: buildbot, cla: yes

#3857 fix(typescript_indexer): do not give anonymous names to binding patterns
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/binding_pattern.ts
Labels: buildbot, cla: yes

#3877 chore(build_rules): use simpler arguments when invoking kzip create
  tools/build_rules/verifier_test/kzip_archive.bzl
Labels: cla: yes

#3874 release: add kzip_validator tool to release archive
  kythe/release/BUILD
Labels: cla: yes

#3867 feature(typescript_indexer): index computed function names
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/function.ts
Labels: buildbot, cla: yes

#3870 feat(typescript_indexer): emit "aliases" edge on aliased types
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/type_alias.ts
Labels: buildbot, cla: yes

#3881 feature(typescript_indexer): add Kythe typings
  kythe/typescript/kythe.ts
Labels: buildbot, cla: yes

#3882 fix(typescript_indexer): don't throw on unfound module path
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3885 chore(llvm): cleanup extraneous print statement
  tools/build_rules/llvm/llvm.bzl
Labels: cla: yes

#3886 build: upgrade to Truth 1.0
  external.bzl
Labels: cla: yes

#3887 fix: upgrade commitlint to 8.1.0 to upgrade lodash version
  package-lock.json
  package.json
Labels: cla: yes

#3889 fix(java_extractor): deal with both kinds of Generated annotations
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/ProcessAnnotation.java
Labels: cla: yes

#3892 chore(java_extractor): make test less brittle on JDK changes
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#3884 refactor(typescript_indexer): integrate Kythe types in indexer
  kythe/typescript/BUILD
  kythe/typescript/indexer.ts
  kythe/typescript/kythe.ts
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#3880 fix(typescript_indexer): add anon signature part for function expressions
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/function.ts
Labels: buildbot, cla: yes

#3883 refactor(typescript_indexer): cleanup module path resolution
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3891 fixup: fail extraction after first failed command
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3893 chore(java_indexer): add support and tests for JDK9 Generated annotation
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingMetadata.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingMetadata.java.meta
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingProtobufMetadata.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingProtobufMetadata.java.pb.meta
Labels: cla: yes

#3890 feat: Add commands necessary for tensorflow builds
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3895 feat: add KYTHE_PRE_BUILD_STEP handling to go extractor image
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
Labels: cla: yes

#3897 build: support Bazel 0.28.1
  .bazelversion
  version.bzl
Labels: build, cla: yes

#3896 Replace option value
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: cla: yes

#3898 feat(java_indexer): add basic tests for java-9-10-11 features
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DiamondOperations.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/LocalInference.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/PrivateInterfaceMethods.java
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3900 fix(cxx_indexer): properly reference C++17 deduced templates
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/template/template_class_ctor_deduction.cc
Labels: cla: yes

#3901 fix(serving): remove spammy log lines
  kythe/go/serving/xrefs/xrefs.go
Labels: cla: yes, serving

#3903 chore(cxx_indexer): pull memcahced-dependent claiming into separate file
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/DynamicClaimClient.cc
  kythe/cxx/indexer/cxx/DynamicClaimClient.h
  kythe/cxx/indexer/cxx/KytheClaimClient.cc
  kythe/cxx/indexer/cxx/KytheClaimClient.h
  kythe/cxx/indexer/cxx/frontend.cc
Labels: cla: yes

#3783 feat(typescript_indexer): define VName specification
  kythe/typescript/SCHEMA.md
  kythe/typescript/testdata/schema.ts
Labels: buildbot, cla: yes

#3904 chore(cxx_indexer): use CHECK rather than if/exit when opening memcached
  kythe/cxx/indexer/cxx/frontend.cc
Labels: cla: yes

#3910 fixup: Add jsr250 dep for Kythe annotated protos
  kythe/extractors/BUILD
Labels: cla: yes

#3911 fixup: Add jsr250 to our release proto toolchain
  kythe/release/release.BUILD
Labels: cla: yes

#3899 feat(typescript_indexer): add support for indexing literal properties
  kythe/typescript/SCHEMA.md
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/object.ts
  kythe/typescript/testdata/schema.ts
Labels: buildbot, cla: yes

#3913 chore(build): switch to a maintained YAML package
  external.bzl
  go.mod
  go.sum
  kythe/go/extractors/gcp/config/BUILD
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/test/testutil/BUILD
  kythe/go/test/testutil/testutil.go
  third_party/go/BUILD
  third_party/go/k8s_yaml.BUILD
Labels: buildbot, cla: yes

#3915 docs: remove obsolete readme.md
  readme.md
Labels: cla: yes

#3916 fixup(c++): Don't build manual targets
  tools/cpp/generate_compilation_database.sh
Labels: cla: yes

#3920 build: update Apache Beam to commit 7688bcf
  external.bzl
  go.mod
  go.sum
  third_party/beam/sdks/go/pkg/beam/runners/disksort/buffer.go
Labels: cla: yes

#3919 feat(tooling): implement (*riegeli.Writer).Position
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_test.go
Labels: cla: yes

#3921 fix(bazel extractor): better handling of bazel exit code
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3922 chore: use checkerframework @Nullable annotation
  external.bzl
  kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/base/NodeKind.java
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/InputUsageRecord.java
  kythe/java/com/google/devtools/kythe/platform/java/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/KytheMetadataLoader.java
  kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java
Labels: cla: yes

#3924 fix: proper java formatting
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
Labels: cla: yes

#3923 feat: Add bazel wrapper for external extraction
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/bazel_wrapper.sh
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3917 feat: use bazel query to find targets to extract
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3912 feat(cxx_common): document and implement kythe metadata as proto
  kythe/cxx/common/BUILD
  kythe/cxx/common/json_proto.cc
  kythe/cxx/common/json_proto.h
  kythe/cxx/common/kythe_metadata_file.cc
  kythe/cxx/common/kythe_metadata_file.h
  kythe/proto/BUILD
  kythe/proto/metadata.proto
Labels: cla: yes

#3925 fix: Properly handle target expressions
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3927 fix: use [[ ]] everywhere
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3926 fix: use bash not sh to execute helper script
  kythe/extractors/bazel/bazel_wrapper.sh
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3908 feat(typescript_indexer): add support for utf-16 offset lookup
  kythe/typescript/indexer.ts
  kythe/typescript/utf8.ts
  kythe/typescript/utf8_test.ts
Labels: buildbot, cla: yes

#3928 feat(java_common): rudimentary CompilationUnit FileSystem
  kythe/java/com/google/devtools/kythe/extractors/shared/ExtractorUtils.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/ByteBufferByteChannel.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileAttributes.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemProvider.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java
  kythe/javatests/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes

#3909 feat(typescript_indexer): expose getSymbolName through IndexerHost
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3888 feat(typescript_indexer): add minimal support for JSX
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/tsconfig.for.tests.json
  kythe/typescript/testdata/tsx.tsx
Labels: buildbot, cla: yes

#3930 fix(java_common): replace or remove JDK9+ methods
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes

#3931 fix(java_common): fix for error prone errors in test
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes

#3932 chore(java_common): a few low-priority cleanups for CU filesystem
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemProvider.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes
