Repository kythe/kythe, pull requests merged in 2019-08, with the labels that each got.

#3936 fix: strict dependencies for textproto indexer
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
Labels: cla: yes

#3935 feat(jdk_indexing): allow extracting only specific make targets
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes

#3937 fix(java_common): allow resolving relative paths against CU working dir
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java
Labels: cla: yes

#3938 chore(tests): update googletest version to something more modern
  external.bzl
Labels: cla: yes

#3939 docs(go extractor): remove mention of kindex and indexpack
  kythe/go/extractors/cmd/gotool/gotool.go
Labels: cla: yes

#3940 feat(cxx_common): support proto encoding of compilation units in kzips
  kythe/cxx/common/BUILD
  kythe/cxx/common/kzip_encoding.h
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_reader.h
  kythe/cxx/common/kzip_reader_test.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
  kythe/cxx/common/kzip_writer_test.cc
Labels: cla: yes

#3933 feat(kzip tool): add more details and json output mode to `kzip info`
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
Labels: cla: yes

#3941 build: migrate to Starlark Java rules
  external.bzl
  kythe/extractors/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/java/com/google/devtools/kythe/common/BUILD
  kythe/java/com/google/devtools/kythe/doc/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/indexpack/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/java/com/google/devtools/kythe/util/schema/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/javatests/com/google/devtools/kythe/doc/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/indexpack/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/javatests/com/google/devtools/kythe/util/BUILD
  kythe/javatests/com/google/devtools/kythe/util/schema/BUILD
  kythe/proto/BUILD
  setup.bzl
  third_party/bazel/BUILD
  third_party/guava/BUILD
  third_party/javac/BUILD
  third_party/truth/BUILD
Labels: build, cla: yes

#3942 build: migrate to Starlark Proto rules
  external.bzl
  kythe/examples/proto/BUILD
  kythe/extractors/BUILD
  kythe/go/util/riegeli/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  kythe/proto/BUILD
  setup.bzl
  third_party/bazel/BUILD
Labels: build, cla: yes

#3943 fix: add an ErrPermissionDenied for services to return
  kythe/go/services/xrefs/xrefs.go
Labels: cla: yes

#3944 fix(cxx_common): update LLVM to r367622
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/marked_source.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3945 docs(schema): add property/{reads,writes} edges
  kythe/data/schema_index.textproto
  kythe/docs/schema/schema.txt
  kythe/go/util/schema/indexdata.go
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/typescript/kythe.ts
Labels: cla: yes, schema

#3947 feat(docker_extract): support selecting encoding for kzip generation
  kythe/extractors/bazel/extract.sh
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
Labels: cla: yes

#3948 fix(cxx): clang-format recently edit cxx files
  kythe/cxx/common/kzip_encoding.h
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
Labels: cla: yes

#3952 fix: update references to the javac-9 jar
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile
  third_party/javac/README.google
Labels: cla: yes

#3949 ci(buildbot): add builder to run 'arc lint'
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg
  tools/arc/linter.sh
Labels: cla: yes

#3955 fix(java_build): remove jvm_flags which complicate running on newer JDKs
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
Labels: cla: yes

#3954 fix(doc): update kzip doc for proto encoding and unit naming
  kythe/docs/kythe-kzip.txt
Labels: cla: yes

#3958 ci(buildbot): install golint tool
  kythe/release/appengine/buildbot/Dockerfile
Labels: cla: yes

#3956 cleanup(go extractor): remove unused --local_path flag
  kythe/go/extractors/cmd/gotool/gotool.go
  kythe/go/extractors/golang/golang.go
Labels: cla: yes

#3959 build: re-enable NPM symlinks; Bazel min version -> 0.28.0
  .bazelminversion
  WORKSPACE
  version.bzl
Labels: build, cla: yes

#3906 Comment localhost:<port> vs :<port> for server "listen" specifications
  README.langserver.md
  kythe/docs/schema/writing-an-indexer.txt
  kythe/examples/bazel/kythe-index.sh
  kythe/go/languageserver/bin/main.go
  kythe/go/serving/tools/http_server/http_server.go
  kythe/release/appengine/xrefs/server.go
  kythe/rust/cargo-kythe/src/main.rs
  kythe/web/site/examples.md
Labels: buildbot, cla: yes

#3957 feat(kzip): add `kzip view` command
  kythe/extractors/bazel/README.md
  kythe/go/platform/tools/kzip/BUILD
  kythe/go/platform/tools/kzip/kzip.go
  kythe/go/platform/tools/kzip/viewcmd/BUILD
  kythe/go/platform/tools/kzip/viewcmd/protodeps.go
  kythe/go/platform/tools/kzip/viewcmd/viewcmd.go
  kythe/go/platform/tools/viewindex/BUILD
  kythe/release/BUILD
  kythe/release/release_test.sh
  kythe/testdata/BUILD
  kythe/testdata/test.kzip
Labels: cla: yes

#3964 test(java_extractor): test/run Bazel Java extractor as aspect
  kythe/go/util/tools/write_extra_action/BUILD
  kythe/go/util/tools/write_extra_action/write_extra_action.go
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/bazel/BUILD
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes, extraction, java

#3966 fix: warn (don't fail) on multiple java outputs
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
Labels: cla: yes

#3965 cleanup(tests): use kzip instead of kindex_tool in proto/textproto tests
  kythe/cxx/extractor/proto/testdata/custom_corpus.UNIT
  kythe/cxx/extractor/proto/testdata/custom_root_directory.UNIT
  kythe/cxx/extractor/proto/testdata/custom_vname_config.UNIT
  kythe/cxx/extractor/proto/testdata/duplicate_imports.UNIT
  kythe/cxx/extractor/proto/testdata/duplicate_imports2.UNIT
  kythe/cxx/extractor/proto/testdata/kzip_diff_test.sh
  kythe/cxx/extractor/proto/testdata/multiple_source_files.UNIT
  kythe/cxx/extractor/proto/testdata/proto_extractor_test.bzl
  kythe/cxx/extractor/proto/testdata/relative_imports.UNIT
  kythe/cxx/extractor/proto/testdata/simple.UNIT
  kythe/cxx/extractor/textproto/testdata/custom_corpus.UNIT
  kythe/cxx/extractor/textproto/testdata/deps.UNIT
  kythe/cxx/extractor/textproto/testdata/extra_imports.UNIT
  kythe/cxx/extractor/textproto/testdata/multiple_proto_files.UNIT
  kythe/cxx/extractor/textproto/testdata/simple.UNIT
  kythe/cxx/extractor/textproto/testdata/subdir.UNIT
  kythe/cxx/extractor/textproto/testdata/without_schema.UNIT
  kythe/cxx/tools/BUILD
Labels: cla: yes

#3967 fix(tests): make proto/textproto tests not rely on `jq`
  kythe/cxx/extractor/proto/testdata/custom_corpus.UNIT
  kythe/cxx/extractor/proto/testdata/custom_root_directory.UNIT
  kythe/cxx/extractor/proto/testdata/custom_vname_config.UNIT
  kythe/cxx/extractor/proto/testdata/duplicate_imports.UNIT
  kythe/cxx/extractor/proto/testdata/duplicate_imports2.UNIT
  kythe/cxx/extractor/proto/testdata/kzip_diff_test.sh
  kythe/cxx/extractor/proto/testdata/multiple_source_files.UNIT
  kythe/cxx/extractor/proto/testdata/proto_extractor_test.bzl
  kythe/cxx/extractor/proto/testdata/relative_imports.UNIT
  kythe/cxx/extractor/proto/testdata/simple.UNIT
  kythe/cxx/extractor/textproto/testdata/custom_corpus.UNIT
  kythe/cxx/extractor/textproto/testdata/deps.UNIT
  kythe/cxx/extractor/textproto/testdata/extra_imports.UNIT
  kythe/cxx/extractor/textproto/testdata/multiple_proto_files.UNIT
  kythe/cxx/extractor/textproto/testdata/simple.UNIT
  kythe/cxx/extractor/textproto/testdata/subdir.UNIT
  kythe/cxx/extractor/textproto/testdata/without_schema.UNIT
  kythe/go/util/formatjson/BUILD
  kythe/go/util/formatjson/formatjson.go
Labels: cla: yes

#3968 fix(cxx_extractor): update comments to mention kzip instead of kindex
  kythe/cxx/extractor/README.md
  kythe/cxx/extractor/cxx_extractor_main.cc
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/cxx/extractor/testdata/run_cxx_bazel_extraction.sh
  kythe/cxx/extractor/testdata/run_objc_bazel_extraction.sh
Labels: cla: yes

#3969 refactor(kzip): use kzip.Scan() helper
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
Labels: cla: yes

#3970 fix(java_indexer): dynamically resolve JRE 9 bootclasspath
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: cla: yes, indexing, java

#3972 fix: accept either JRE 8 or JRE 9 style classpath in test
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: cla: yes

#3971 feat(kzip tool): use vfs to allow for changing filesystem impl
  kythe/go/platform/tools/kzip/infocmd/BUILD
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
  kythe/go/platform/tools/kzip/viewcmd/BUILD
  kythe/go/platform/tools/kzip/viewcmd/viewcmd.go
  kythe/go/platform/vfs/vfs.go
  kythe/go/platform/vfs/zip/fs.go
Labels: cla: yes

#3962 Add details to schema "diagnostic"
  kythe/docs/schema/schema.txt
Labels: buildbot, cla: yes

#3974 chore(java_indexer): remove unnecessary dependency on custom FileManager
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
Labels: cla: yes

#3975 fix(java_common): add file digest as Path URI host
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java
Labels: cla: yes

#3976 fix(java_indexer): implement JDK9+ path-based FileObject methods
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
Labels: cla: yes

#3977 fix(java_common): mark CompilationUnitFileSystem public
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
Labels: cla: yes

#3978 chore: clang-tidy and other robot suggested fixes
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/tools/shuck_main.cc
Labels: cla: yes

#3979 fix(doc): clarify variable subkinds and aliases edge
  kythe/docs/schema/schema.txt
Labels: cla: yes

#3980 feat(serving): experimental support for xrefs indirection
  kythe/go/serving/xrefs/BUILD
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
  kythe/go/util/flagutil/flagutil.go
Labels: cla: yes, serving

#3981 fix(java_common): satisfy linters
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
Labels: cla: yes

#3983 typescript: handle 'typeof'
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/typeof.ts
Labels: buildbot, cla: yes

#3984 feat(serving): add wildcard node kind support to xrefs indirection
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
Labels: cla: yes, serving

#3985 chore(build): update protobuf dependency and clean up repo names
  external.bzl
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/tools/proto_metadata_plugin.cc
  kythe/examples/proto/BUILD
  kythe/extractors/BUILD
  kythe/go/util/riegeli/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/java/com/google/devtools/kythe/common/BUILD
  kythe/java/com/google/devtools/kythe/doc/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/indexpack/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
  kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/java/com/google/devtools/kythe/util/schema/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/base/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/jvm/BUILD
  kythe/javatests/com/google/devtools/kythe/doc/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/indexpack/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/BUILD
  kythe/javatests/com/google/devtools/kythe/util/BUILD
  kythe/javatests/com/google/devtools/kythe/util/schema/BUILD
  kythe/proto/BUILD
  setup.bzl
  third_party/bazel/BUILD
  third_party/guava/BUILD
  third_party/javac/BUILD
  third_party/truth/BUILD
Labels: cla: yes

#3986 fix(java_extractor): support missing -s in aspect extraction
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AutoValues.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
Labels: cla: yes, extraction, java

#3987 chore(build): remove obsolete compatibility flags
  .bazelrc
Labels: cla: yes

#3973 feature(typescript_indexer): emit reference for "this" keyword
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
Labels: buildbot, cla: yes

#3982 typescript: update from 3.3 => 3.5
  kythe/typescript/package.json
  kythe/typescript/yarn.lock
Labels: buildbot, cla: yes

#3988 fix(lint): ignore .lock files in copyright checks
  tools/arc/linter.sh
Labels: buildbot, cla: yes

#3989 chore(cxx_common): update to LLVM r368958
  .bazelrc
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3992 docs(schema): cleanup java schema examples; use extractor
  kythe/docs/schema/asciidoc_with_verifier.bzl
  kythe/docs/schema/example-base.sh
  kythe/docs/schema/example-java.sh
  kythe/docs/schema/java-schema-file-data-template.FileData
  kythe/docs/schema/java-schema-unit-template.CompilationUnit
  kythe/docs/schema/schema.txt
Labels: cla: yes, documentation

#3991 feat(kzip info): add proto output format to `kzip info`
  kythe/go/platform/tools/kzip/infocmd/BUILD
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#3994 refactor(kzip): move KzipInfo creation logic into a library
  kythe/go/platform/kzip/info/BUILD
  kythe/go/platform/kzip/info/info.go
  kythe/go/platform/tools/kzip/infocmd/BUILD
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
Labels: cla: yes

#3995 docs(info.go): fix package comment
  kythe/go/platform/kzip/info/info.go
Labels: cla: yes

#3996 chore(cxx_indexer): delete now-dead code post llvm update
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
Labels: cla: yes

#3997 fix(tooling): use uncompressed riegeli block size when decompressing
  kythe/go/util/riegeli/compression.go
  kythe/go/util/riegeli/reader.go
  kythe/go/util/riegeli/riegeli_bench_test.go
  kythe/go/util/riegeli/transpose_decoder.go
Labels: cla: yes

#3918 feature(typescript_indexer): extend symbol cache to store contexts
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#3998 feat(kzip): add filter subcommand to kzip tool
  kythe/go/platform/tools/kzip/BUILD
  kythe/go/platform/tools/kzip/filtercmd/BUILD
  kythe/go/platform/tools/kzip/filtercmd/filtercmd.go
  kythe/go/platform/tools/kzip/kzip.go
Labels: cla: yes

#4000 chore(cxx_common): replace uses of llvm::make_unique w/ absl::make_unique
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/indexer_worklist.cc
  kythe/cxx/tools/fyi/fyi.cc
  kythe/cxx/tools/fyi/fyi_main.cc
Labels: cla: yes

#4001 chore(cxx_tools): fix for missing build dependency
  kythe/cxx/tools/fyi/BUILD
Labels: cla: yes

#4003 typescript: enable more strictness flags
  kythe/typescript/indexer.ts
  kythe/typescript/tsconfig.json
Labels: buildbot, cla: yes

#4004 fix(cxx_indexer): allow protobuf metadata in .stubby.h files
  kythe/cxx/common/protobuf_metadata_file.cc
Labels: cla: yes

#4007 fix: bump nokogiri to 1.10.4
  kythe/web/site/Gemfile.lock
Labels: cla: yes

#4008 fix(build): include C++14 options in default build flags
  .bazelrc
  kythe/web/site/getting-started.md
Labels: buildbot, cla: yes

#4009 feat(cxx_extractor): allow resolving symlinks when creating vname paths
  kythe/cxx/common/BUILD
  kythe/cxx/common/libzip/error.cc
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
  kythe/cxx/common/path_utils_test.cc
  kythe/cxx/common/status.cc
  kythe/cxx/common/status.h
  kythe/cxx/common/status_or.h
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/extractor/cxx_extractor_test.cc
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/cxx/extractor/proto/proto_extractor.cc
  kythe/cxx/indexer/proto/kythe_indexer_main.cc
Labels: cla: yes

#4010 fix(cxx_verifier): fix MSAN error on use-of-uninitialized
  kythe/cxx/verifier/assertions.cc
Labels: cla: yes

#4013 chore(java): apply standard formatting
  kythe/java/com/google/devtools/kythe/platform/kzip/KZip.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipReader.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#4012 fix(kzip): make default kzip encodings explicit
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
  kythe/go/platform/kzip/kzip.go
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#4014 feat(linter): report better messages when clang-format fails
  tools/arc/linter.sh
Labels: cla: yes

#4016 fix: clean up link in temp dir for test
  kythe/cxx/common/path_utils_test.cc
Labels: cla: yes

#4015 feat(kzip): obtain default kzip encoding from env var
  kythe/cxx/common/kzip_writer.cc
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/tools/kzip/flags/encoding.go
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: cla: yes

#4017 feat(extraction): allow details to be added to a kindex required input
  kythe/go/platform/kindex/kindex.go
  kythe/go/platform/kindex/kindex_test.go
Labels: cla: yes

#4018 fix(kzip): populate KzipInfo.total_files in info.go
  kythe/go/platform/kzip/info/info.go
Labels: cla: yes

#4011 chore(cxx): switch to using Abseil flags library over gflags
  external.bzl
  kythe/cxx/common/BUILD
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/net_client_test.cc
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
  kythe/cxx/common/path_utils_test.cc
  kythe/cxx/doc/BUILD
  kythe/cxx/doc/doc.cc
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/extractor/cxx_extractor_main.cc
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/cxx/extractor/proto/BUILD
  kythe/cxx/extractor/proto/proto_extractor_main.cc
  kythe/cxx/extractor/textproto/BUILD
  kythe/cxx/extractor/textproto/textproto_extractor.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/GoogleFlagsLibrarySupport.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/indexer/proto/kythe_indexer_main.cc
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/tools/fyi/fyi_main.cc
  kythe/cxx/tools/generate_compile_commands/BUILD
  kythe/cxx/tools/kindex_tool_main.cc
  kythe/cxx/tools/shuck_main.cc
  kythe/cxx/tools/static_claim_main.cc
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/verifier_main.cc
  kythe/examples/proto/BUILD
  kythe/examples/proto/proto_indexer.cc
  third_party/googlelog.BUILD
Labels: cla: yes

#4020 feat(schema): embed metadata in schema.proto source file
  kythe/data/schema_index.textproto
  kythe/go/util/schema/BUILD
  kythe/go/util/schema/indexdata.go
  kythe/go/util/schema/mkdata/BUILD
  kythe/go/util/schema/mkdata/mkdata.go
  kythe/java/com/google/devtools/kythe/util/schema/BUILD
  kythe/proto/BUILD
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
Labels: cla: yes, schema

#4019 chore(cxx_extractor): only log detailed search path once
  kythe/cxx/extractor/cxx_extractor.cc
Labels: cla: yes

#4022 fix(cxx_common): fix path_utils_test when tempdir is a symlink
  kythe/cxx/common/path_utils_test.cc
Labels: cla: yes

#4040 chore(extraction): remove kindex support from go/extractors/bazel/...
  kythe/go/extractors/bazel/extractor.go
  kythe/go/extractors/bazel/extractor_test.go
  kythe/go/extractors/bazel/extutil/extutil.go
Labels: cla: yes

#4042 fix(javac-wrapper): use `set -e` to propagate errors
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
Labels: cla: yes

#4043 chore(cleanup): fix some warnings, DEBUG and unnecessary deps
  .bazelrc
  external.bzl
  kythe/cxx/extractor/BUILD
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/frontend.h
  kythe/cxx/tools/BUILD
  kythe/docs/asciidoc.bzl
  kythe/docs/schema/asciidoc_with_verifier.bzl
Labels: cla: yes

#4045 chore: update boringssl and use github mirror
  external.bzl
Labels: cla: yes

#4046 Revert "fix(javac-wrapper): use `set -e` to propagate errors (#4042)"
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
Labels: cla: yes

#4047 fix(go_common): use nondeprecated zip file handle mod time
  kythe/go/platform/kzip/kzip.go
Labels: cla: yes

#4044 feat(kzip): change Unit.Digest() to return hex string representation
  kythe/go/platform/kcd/kcd.go
  kythe/go/platform/kcd/kcd_test.go
  kythe/go/platform/kcd/kythe/units.go
  kythe/go/platform/kcd/kythe/units_test.go
  kythe/go/platform/kcd/memdb/memdb.go
  kythe/go/platform/kzip/kzip.go
Labels: cla: yes

#4049 chore(cxx_common): update llvm to r370422
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes
