Repository kythe/kythe, pull requests merged in 2019-03, with the labels that each got.

#3563 fix: resolve #3557 by codifying behavior of filtering
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#3569 build: update github.com/hanwen/go-fuse to tagged release v1.0.0
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3570 chore: remove an unused import from analysis.proto
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor.h
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/static_claim_main.cc
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/tools/indexpack/BUILD
  kythe/go/platform/tools/indexpack/indexpack.go
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: buildbot, cla: yes

#3568 deprecation(api): remove deprecated DirectoryReply fields
  kythe/go/services/filetree/BUILD
  kythe/go/services/filetree/filetree.go
  kythe/go/serving/filetree/filetree.go
  kythe/proto/filetree.proto
  kythe/proto/filetree_go_proto/filetree.pb.go
Labels: API, cla: yes, cleanup

#3571 build: restore missing proto dependency
  kythe/cxx/tools/BUILD
Labels: build, cla: yes

#3572 feat(api): add set of build configs per Corpus in CorpusRootsReply
  kythe/proto/filetree.proto
  kythe/proto/filetree_go_proto/filetree.pb.go
Labels: API, cla: yes

#3574 release: support release archive as Bazel repository
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
  kythe/extractors/bazel/extractors.WORKSPACE
  kythe/extractors/bazel/extractors.bazelrc
  kythe/release/BUILD
  kythe/release/release.BUILD
  kythe/release/release.WORKSPACE
Labels: cla: yes

#3576 fix(docs): update getting started for clang-3.6
  kythe/web/site/getting-started.md
Labels: cla: yes

#3577 release: add Bazel extractor for java_import rules
  kythe/extractors/bazel/extractors.bazelrc
  kythe/release/BUILD
  kythe/release/release.BUILD
Labels: cla: yes, extraction, release

#3578 release: add kzip tool
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
  kythe/release/BUILD
  kythe/release/README.md
Labels: CLI, cla: yes, release

#3579 release: add cc_proto_metadata_plugin
  kythe/extractors/bazel/extractors.bazelrc
  kythe/release/BUILD
  kythe/release/README.md
  kythe/release/release.BUILD
Labels: cla: yes, extraction, release

#3573 fix(dev): format shasum_tool output to match sha256sum
  kythe/go/platform/tools/shasum_tool/shasum_tool.go
Labels: cla: yes, release

#3580 feat(serving): add build configs per corpus
  kythe/go/serving/filetree/filetree.go
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/filetree.go
  kythe/go/serving/pipeline/filetree_test.go
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
Labels: cla: yes, post-processing, storage

#3582 build: update protobuf to v3.7.0
  external.bzl
Labels: build, cla: yes

#3583 build: support --incompatible_disallow_dict_plus
  tools/build_rules/llvm/cmake_defines.bzl
Labels: build, cla: yes

#3584 build: remove manually written header include path
  third_party/googlelog.BUILD
  third_party/googlelog/BUILD
Labels: build, cla: yes

#3585 build: remove obsolete Go build.bzl macro
  third_party/go/build.bzl
  third_party/go/uuid.BUILD
Labels: build, cla: yes

#3581 test(cxx indexer): ensure xrefs are created for proto extension fields
  external.bzl
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
  kythe/cxx/indexer/cxx/testdata/proto/proto2.cc
Labels: cla: yes

#3575 chore: downstream javadoc warning fix
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
Labels: cla: yes

#3586 Add newlines between verifier -show_protos output.
  kythe/cxx/verifier/verifier_main.cc
Labels: buildbot, cla: yes

#3587 feat(tooling): add --build_config filter to 'kythe decor' command
  kythe/go/platform/tools/kzip/createcmd/BUILD
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/createcmd/flag.go
  kythe/go/services/cli/BUILD
  kythe/go/services/cli/command_decor.go
  kythe/go/util/flagutil/BUILD
  kythe/go/util/flagutil/flagutil.go
Labels: CLI, cla: yes

#3588 feat(tooling): add --build_config filter to 'kythe xrefs' command
  kythe/go/services/cli/commands_xrefs.go
Labels: CLI, cla: yes

#3590 fix(cxx_indexer): attach build_config to file claim tokens
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
Labels: cla: yes

#3591 build: fix error with --incompatible_new_actions_api
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: build, cla: yes

#3592 build: fix error with --incompatible_depset_union
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: buildbot, cla: yes

#3594 build: update github.com/dsnet/compress to tagged release v0.0.1
  external.bzl
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3595 build: update lein to latest version
  external.bzl
  third_party/leiningen/lein_repo.bzl
Labels: cla: yes

#3598 ci(buildbot): remove --keep_going option from Bazel build
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3596 feat(extraction): use bazelisk in Bazel extractor Dockerfile extraction
  external.bzl
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3599 build: update min/max Bazel versions to 0.22.0/0.23.1
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: build, cla: yes

#3597 release: remove sample web ui
  kythe/release/BUILD
  kythe/release/release_test.sh
Labels: cla: yes

#3602 fix(bazel): Ensure extra actions actually get hooked up.
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3604 fix(post_processing): convert DirectoryReply to FileDirectory for serving data
  kythe/go/serving/pipeline/pipeline.go
Labels: cla: yes, post-processing

#3603 fix(example): use new FileTree API in sample web ui
  kythe/web/ui/.gitignore
  kythe/web/ui/src-cljs/ui/service.cljs
Labels: API, UI, cla: yes

#3601 feat(java_indexer): add MarkedSources for function tapp nodes
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: cla: yes, indexing, java

#3605 fix(go_indexer): always emit anchor for anon value types
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/anonymous.go
Labels: cla: yes, go, indexing

#3606 fix(go_indexer): handle overrides for structs in a other packages
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/override.go
Labels: cla: yes, go, indexing

#3607 fix(java_extractor): initial work enabling extraction of openjdk11
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: buildbot, cla: yes

#3609 chore: fix clang-format annotation
  kythe/cxx/doc/javadoxygen_markup_handler.cc
Labels: cla: yes

#3610 feat(go_indexer): emit bindings for anonymous interface members
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/basic/anonymous.go
Labels: cla: yes, go, indexing

#3611 feat(go_indexer): add typed edges for bindings
  kythe/go/extractors/govname/BUILD
  kythe/go/extractors/govname/types.go
  kythe/go/indexer/BUILD
  kythe/go/indexer/emit.go
  kythe/go/indexer/facts.go
  kythe/go/indexer/indexer.go
  kythe/go/indexer/testdata/types.go
Labels: cla: yes, go, indexing

#3612 fix(java_extractor): use reflection to access/override JDK bits.
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3616 fix(java_extractor): move JDK9 method reflection to static members
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3617 fix(java_extractor): replace JDK9 findFirst with loop
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes

#3618 fix(docs): update release docs to specify kzip
  kythe/release/README.md
Labels: cla: yes

#3619 fix(cxx_indexer): use build_config when claiming implicit AST subtrees
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
Labels: cla: yes

#3620 fix(java_extractor): change an iterable to a collection
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3621 chore(java_extractor): address java-tidy warnings
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3623 fix(java_extractor): change a collection to an iterable
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3624 chore(java_extractor): suppress Iterable<Path> warning in override
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
Labels: cla: yes

#3626 fix(docs): NodeKind.getSubkind returns Optional.
  kythe/java/com/google/devtools/kythe/analyzers/base/NodeKind.java
Labels: cla: yes

#3615 feat(go_indexer): convert variadic function parameters from slice
  kythe/go/extractors/govname/types.go
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/types.go
Labels: cla: yes, go, indexing

#3627 feat(go_indexer): add receiver type to function types
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/types.go
Labels: cla: yes, go, indexing

#3628 feat(java_indexer): add receiver type to function types
  kythe/docs/schema/schema.txt
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/WildcardMethod.java
Labels: cla: yes, indexing, java

#3630 chore(cxx_indexer): update LLVM to r356441
  kythe/cxx/extractor/path_utils.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3631 feat(go_indexer): add MarkedSource for tapp/tbuiltin nodes
  kythe/go/indexer/BUILD
  kythe/go/indexer/emit.go
  kythe/go/indexer/markedsource.go
  kythe/go/indexer/testdata/types.go
Labels: cla: yes, go, indexing

#3629 fix(bazel): Extraction exits with nonzero error code if unable to create kzip
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3632 fix(java_indexer): box LOOKUP_BY_PARAM MarkedSources with text
  kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: cla: yes, indexing, java

#3634 chore: map[*]bool, map[string]struct{} -> map[*]struct{}, stringset
  kythe/go/extractors/config/smoke/BUILD
  kythe/go/extractors/config/smoke/smoke.go
  kythe/go/indexer/emit.go
  kythe/go/indexer/indexer.go
  kythe/go/platform/indexpack/BUILD
  kythe/go/platform/indexpack/indexpack_test.go
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip.go
  kythe/go/services/link/link.go
  kythe/go/serving/explore/BUILD
  kythe/go/serving/explore/explore.go
  kythe/go/storage/entryset/entryset.go
Labels: cla: yes

#3635 feat(go_indexer): overriding method type satisfies interface method type
  kythe/docs/schema/schema.txt
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/override.go
  kythe/go/indexer/testdata/types.go
Labels: cla: yes, go, indexing, schema

#3637 chore(cxx): update LLVM to r356623
  kythe/cxx/extractor/path_utils.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_deps.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3638 fix(leiningen): fail lein setup w/ incompatible JDK
  .bazelrc
  third_party/leiningen/lein_repo.bzl
Labels: cla: yes

#3639 fix(leiningen): have the lein wrapper script exit on any failure
  third_party/leiningen/lein_repo.bzl
Labels: cla: yes

#3640 fix(leiningen): ensure wrapper script uses /bin/bash rather than /bin/sh
  third_party/leiningen/lein_repo.bzl
Labels: cla: yes

#3641 feat(bazel): support package installation at extraction time to support system dependencies
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#3642 fix(bazel): add curses to always-installed packages in the Bazel dockerfile
  kythe/extractors/bazel/Dockerfile
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#2977 Record @deprecated javadoc tags in the Java indexer
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java
Labels: buildbot, cla: yes

#3644 fix(cxx): remove dependency on ncurses/terminfo
  tools/build_rules/llvm/cmake_defines.bzl
  tools/build_rules/llvm/llvm.BUILD
Labels: cla: yes

#3645 chore: libncurses removal doc fixes
  kythe/extractors/bazel/Dockerfile
  kythe/release/README.md
  kythe/release/appengine/buildbot/Dockerfile
  kythe/web/site/getting-started.md
  tools/docker/Dockerfile
  tools/platforms/Dockerfile
Labels: cla: yes

#3646 Move the lex/yacc rules to using a locally-configured toolchain
  .bazelrc
  external.bzl
  kythe/cxx/verifier/BUILD
  tools/build_rules/lexyacc.bzl
  tools/build_rules/lexyacc/BUILD
  tools/build_rules/lexyacc/lexyacc.bzl
Labels: cla: yes

#3648 chore: use upstream find_cpp_toolchain rather than custom version
  kythe/cxx/tools/fyi/testdata/compile_commands.bzl
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/toolchain_utils.bzl
Labels: cla: yes

#3649 Remove obsolete assertion
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: buildbot, cla: yes

#3652 build: update min/max bazel version to 0.22/0.24
  .bazelrc
  WORKSPACE
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/master/master.cfg.template
Labels: cla: yes

#3647 fix(bazel): include jsr250 jar for java extraction
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/release/release.BUILD
Labels: cla: yes

#3643 Emit kythe/tag/deprecated for elements annotated @Deprecated
  kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DeprecationAnnotations.java
Labels: buildbot, cla: yes

#3653 release: change buildbot config to use secrets directly
  kythe/release/appengine/buildbot/.gitignore
  kythe/release/appengine/buildbot/Dockerfile
  kythe/release/appengine/buildbot/bazelrc
  kythe/release/appengine/buildbot/cloudbuild.yaml
  kythe/release/appengine/buildbot/deploy.sh
  kythe/release/appengine/buildbot/master/master.cfg
Labels: cla: yes

#3654 chore: update gflags to v2.2.2
  external.bzl
Labels: cla: yes

#3655 chore: update bazel_toolchains to include 0.24.0
  WORKSPACE
Labels: cla: yes

#3656 fix(build): fully qualify workspace references in lexyacc rules
  tools/build_rules/lexyacc/lexyacc.bzl
Labels: cla: yes
