Repository kythe/kythe, pull requests merged in 2019-05, with the labels that each got.

#3709 chore: upstream removal of deprecated truth library
  external.bzl
  kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
Labels: cla: yes

#3710 chore: migrate from is(Not)SameAs to is(Not)SameInstanceAs
  kythe/javatests/com/google/devtools/kythe/extractors/shared/ExtractorUtilsTest.java
  kythe/javatests/com/google/devtools/kythe/util/KytheURITest.java
Labels: cla: yes, cleanup

#3708 feat(cxx_indexer): provide defines spans for functions
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/function/function_defines.cc
  kythe/cxx/indexer/cxx/testdata/function/function_member_defines.cc
  kythe/cxx/indexer/cxx/testdata/template/template_fn_defines.cc
Labels: cla: yes

#3713 chore(build): add blacklist for known-bad releases (currently 0.25.0)
  WORKSPACE
  version.bzl
Labels: cla: yes

#3715 fix(cxx_indexer): always add . to the VFS
  kythe/cxx/indexer/cxx/KytheVFS.cc
Labels: cla: yes

#3716 fix(cxx_indexer): insist that compilation units have working directories
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/testdata/kindex_test.unit
Labels: cla: yes

#3717 fix(tooling): allow sample UI dependencies to be disabled
  external.bzl
Labels: cla: yes

#3718 fix: update out of date script in verifier example
  kythe/docs/schema/writing-an-indexer.txt
Labels: cla: yes

#3719 feat(tooling): add --semantic_scopes flag to `kythe decor` command
  kythe/go/services/cli/command_decor.go
Labels: API, CLI, cla: yes

#3712 feat(post_processing): implement basic callers in PagedCrossReferences
  kythe/go/serving/pipeline/beam.go
  kythe/go/serving/pipeline/beam_test.go
Labels: cla: yes, post-processing

#3714 feat(schema): add Java utility to convert Node/Entry protos
  kythe/java/com/google/devtools/kythe/util/schema/BUILD
  kythe/java/com/google/devtools/kythe/util/schema/Nodes.java
  kythe/javatests/com/google/devtools/kythe/util/schema/BUILD
  kythe/javatests/com/google/devtools/kythe/util/schema/NodesTest.java
Labels: cla: yes, java, schema

#3720 Update a link to the verifier documentation.
  kythe/cxx/verifier/verifier_main.cc
Labels: buildbot, cla: yes

#3721 chore: update go.mod and go.sum files
  go.mod
  go.sum
Labels: buildbot, cla: yes

#3722 chore(cxx_common): update Clang/LLVM to r360148
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  tools/build_rules/cc_resources.bzl
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_deps.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3724 fix(typescript_indexer): remove deprecated childof edge from anchor to file
  kythe/typescript/indexer.ts
Labels: cla: yes, indexing, typescript

#3725 chore(cxx_common): update Abseil and use type-safe printf over libc
  external.bzl
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/indexing/KytheCachingOutput.cc
  kythe/cxx/common/indexing/KytheOutputStream.h
  kythe/cxx/doc/BUILD
  kythe/cxx/doc/doc.cc
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/CommandLineUtils.cc
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/cxx/extractor/path_utils.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheClaimClient.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/tools/fyi/fyi.cc
  kythe/cxx/tools/generate_compile_commands/BUILD
  kythe/cxx/tools/generate_compile_commands/extract_compile_command.cc
  kythe/cxx/tools/kindex_tool_main.cc
  kythe/cxx/tools/shuck_main.cc
  kythe/cxx/tools/static_claim_main.cc
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/pretty_printer.cc
  kythe/cxx/verifier/verifier_main.cc
Labels: cla: yes

#3726 chore(build): remove leftover LLVM debugging echo
  tools/build_rules/llvm/llvm.BUILD
Labels: cla: yes

#3727 chore(doc): remove cmake/ssl from deps and docs
  kythe/release/appengine/buildbot/Dockerfile
  kythe/web/site/getting-started-macos.md
  kythe/web/site/getting-started.md
  tools/docker/Dockerfile
  tools/platforms/Dockerfile
Labels: cla: yes

#3729 chore(java_extractor): rename build env jar in test
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#3730 chore(java_extractor): update one final test missed in the previous PR
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#3731 build: update Bazel rules_go to 0.18.4
  external.bzl
  kythe/go/indexer/testdata/go_indexer_test.bzl
  setup.bzl
Labels: build, cla: yes, go

#3732 build: update golang/protobuf to v1.3.0
  external.bzl
  go.mod
  go.sum
  kythe/go/util/riegeli/riegeli_test_go_proto/riegeli_test.pb.go
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/analysis_service_go_proto/analysis_service.pb.go
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/extraction_config_go_proto/extraction_config.pb.go
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/repo_go_proto/repo.pb.go
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/storage_service_go_proto/storage_service.pb.go
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: build, cla: yes, go

#3733 build(deps): update Apache Beam to 3cf3a4708
  external.bzl
  go.mod
  go.sum
Labels: build, cla: yes

#3735 docs: fix examples to use _CORPUS instead of _KYTHE_CORPUS
  kythe/extractors/gcp/README.md
Labels: cla: yes

#3736 build(bazel): support Bazel 0.25.2
  WORKSPACE
Labels: build, cla: yes

#3723 Create presubmit.yml for Bazel continuous integration
  .bazelci/presubmit.yml
Labels: buildbot, cla: yes

#3737 fix(tooling): fix #3246
  kythe/go/util/riegeli/compression.go
Labels: bug, cla: yes

#3738 feat(api): add build config to each related Anchor
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes, cleanup

#3739 fix(api): filter decoration overrides by desired build configs
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
Labels: API, bug, cla: yes

#3740 fix: update vulnerable outdated js-yaml NPM package
  package-lock.json
Labels: buildbot, cla: yes

#3742 fix(cxx_indexer): ngrmadlize windows paths
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
  kythe/cxx/indexer/cxx/KytheVFS.h
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/test_kindex.sh
  kythe/cxx/indexer/cxx/testdata/windows_test.header
  kythe/cxx/indexer/cxx/testdata/windows_test.main
  kythe/cxx/indexer/cxx/testdata/windows_test.unit
  kythe/cxx/indexer/cxx/testdata/windows_test.verify
Labels: cla: yes

#3743 chore(cxx_indexer): if if -> if in a comment
  kythe/cxx/indexer/cxx/KytheVFS.h
Labels: cla: yes

#3744 chore(zlib): only export actual public headers from zlib
  third_party/zlib.BUILD
Labels: cla: yes

#3747 fix(cxx): better support cuda extractions
  kythe/cxx/extractor/cxx_extractor.cc
Labels: cla: yes

#3748 chore: fix copyrights
  kythe/java/com/google/devtools/kythe/util/schema/Nodes.java
  kythe/javatests/com/google/devtools/kythe/util/schema/NodesTest.java
  tools/arc/linter.sh
Labels: cla: yes

#3749 style: clang-format
  kythe/cxx/tools/kindex_tool_main.cc
  tools/arc/linter.sh
Labels: cla: yes

#3750 feat(post_processing): allow nodes/anchors to be ranked
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
  tools/arc/linter.sh
Labels: cla: yes

#3751 chore(objectivec): Explicitly test multi arg method marked source
  kythe/cxx/indexer/cxx/testdata/objc/marked_method.m
Labels: cla: yes

#3753 chore(docs): fix sample ui links
  kythe/docs/exploring-kythe-sample-web-ui.txt
Labels: cla: yes

#3754 Disable tests that don't work on Linux in presubmit.yml.
  .bazelci/presubmit.yml
Labels: buildbot, cla: yes

#3755 feat(post_processing): add Nodes.fromSource conversion utility
  kythe/java/com/google/devtools/kythe/util/KytheURI.java
  kythe/java/com/google/devtools/kythe/util/schema/Nodes.java
  kythe/javatests/com/google/devtools/kythe/util/schema/NodesTest.java
Labels: cla: yes, post-processing

#3756 chore(examples): update example extraction to be more judicious
  kythe/web/site/examples.md
Labels: cla: yes

#3759 chore(cxx_common): update LLVM to r361353
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_deps.bzl
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#3760 chore(build): allow Bazel CI to opt out of version check
  version.bzl
Labels: cla: yes

#3761 chore(build): apply changes for forthcoming Bazel incompatibilities
  .bazelrc
  setup.bzl
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#3763 chore(bazel): enable compatibility option for string join
  .bazelrc
Labels: cla: yes

#3762 java_verifier_tests: declare deps for annotations
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: buildbot, cla: yes

#3764 fix(serving): properly return lookup errors
  kythe/go/storage/table/table.go
Labels: bug, cla: yes

#3766 build(bazel): support Bazel 0.25.3
  WORKSPACE
Labels: cla: yes

#3769 Migrate Kythe for Bazel 0.27
  kythe/cxx/tools/fyi/testdata/compile_commands.bzl
Labels: buildbot, cla: yes

#3770 chore(build): update Bazel to 0.26
  WORKSPACE
Labels: cla: yes

#3767 build: update bitbucket.org/creachadair/shell to v0.0.5
  external.bzl
Labels: buildbot, cla: yes

#3771 build: add .bazelversion file for Bazelisk
  .bazelversion
Labels: build, cla: yes

#3774 chore: add missing include
  kythe/cxx/common/kzip_writer_test.cc
Labels: cla: yes

#3773 Initial buildkite scripts and configuration
  WORKSPACE
  kythe/release/kubernetes/buildkite/Dockerfile
  kythe/release/kubernetes/buildkite/bazelrc
  kythe/release/kubernetes/buildkite/cloudbuild.yaml
  kythe/release/kubernetes/buildkite/deploy.sh
  kythe/release/kubernetes/buildkite/deployment.yaml
  kythe/release/kubernetes/buildkite/setup.sh
Labels: cla: yes

#3775 feat(typescript_indexer): add `defines` anchors for functions
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/function.ts
Labels: buildbot, cla: yes

#3776 fix(post_processing): split semantic callers within xrefs group
  kythe/go/serving/pipeline/beam.go
Labels: cla: yes, post-processing

#3777 chore(cxx_indexer): remove redundant working_directory field
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/frontend.h
Labels: cla: yes
