Repository kythe/kythe, pull requests merged in 2020-11, with the labels that each got.

#4732 chore: upgrade py_binary to v3
  tools/build_rules/verifier_test/BUILD
Labels: cla: yes

#4735 chore: replace uses of deprecated proto functions
  kythe/cxx/common/indexing/KytheCachingOutput.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/tools/static_claim_main.cc
  kythe/cxx/verifier/verifier_main.cc
Labels: cla: yes

#4734 fix(java_indexer): blame instance/static callsites on ctor/cinit methods
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaNode.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/TreeContext.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java
Labels: cla: yes, indexing, java

#4736 build: add buildozer fix command for ibazel
  .bazel_fix_commands.json
Labels: cla: yes

#4738 fix(java_indexer): special-case builtin Array class lookup
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/SpecialMembers.java
Labels: cla: yes

#4737 style: cleanup some lint warnings
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaNode.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes, cleanup

#4739 fix(java_indexer): add zero-length definition for cinit
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
Labels: cla: yes, indexing, java

#4740 fix(java_indexer): blame callsites under static fields on the clinit
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/TreeContext.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
Labels: cla: yes, indexing, java

#4742 Fix invalid escape sequences
  kythe/data/vnames.bzl
Labels: buildbot, cla: yes

#4743 chore: update to new llvm revision
  kythe/cxx/extractor/cxx_extractor.cc
  tools/build_rules/llvm/cmake_defines.bzl
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4741 fix(java_indexer): handle doc refs to primitives
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
Labels: cla: yes, indexing, java

#4746 feat(java_indexer): tag abstract methods/classes as such
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AbstractClass.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
Labels: cla: yes

#4750 One more invalid escape sequence fix
  kythe/docs/asciidoc.bzl
Labels: buildbot, cla: yes

#4751 Yet another invalid escape sequence
  kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl
Labels: buildbot, cla: yes

#4752 build: enable more ErrorProne warnings
  .bazelrc
  kythe/go/serving/tools/testdata/kwazthis_test.sh
  kythe/java/com/google/devtools/kythe/analyzers/base/EntrySet.java
  kythe/java/com/google/devtools/kythe/analyzers/base/FactEmitter.java
  kythe/java/com/google/devtools/kythe/analyzers/java/AutoValuePlugin.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/MiniAnchor.java
  kythe/java/com/google/devtools/kythe/analyzers/java/SourceText.java
  kythe/java/com/google/devtools/kythe/doc/DocUnbracketer.java
  kythe/java/com/google/devtools/kythe/doc/MarkedSourceRenderer.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/shared/ExtractorUtils.java
  kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitBasedJavaFileStore.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStore.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/BlockAnonymousSignatureGenerator.java
  kythe/java/com/google/devtools/kythe/platform/shared/Metadata.java
  kythe/java/com/google/devtools/kythe/platform/shared/MetadataLoader.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/java/com/google/devtools/kythe/util/schema/Nodes.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/MiniAnchorTest.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/TestPlugin.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AutoValues.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Definitions.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DeprecationAnnotations.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Enums.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericClass.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericComments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericMethod.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericMethodRef.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Generics.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Inheritance.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Interfaces.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JDK.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Lambdas.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Scopes.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Selectors.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/SpecialMembers.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/StaticMethods.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/StaticVariables.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Variables.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/WildcardMethod.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/SunSource.java
  kythe/javatests/com/google/devtools/kythe/doc/MarkedSourceRendererTest.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/FileDataCacheTest.java
  kythe/javatests/com/google/devtools/kythe/platform/shared/FileDataDirectoryTest.java
  tools/javacopts.bazelrc
Labels: cla: yes, cleanup

#4753 build: add more ErrorProne checks
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/extractors/java/SystemExploder.java
  kythe/java/com/google/devtools/kythe/extractors/shared/ExtractorUtils.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitBasedJavaFileStore.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/JCTreeScanner.java
  kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java
  kythe/java/com/google/devtools/kythe/util/DeleteRecursively.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java
  tools/javacopts.bazelrc
Labels: cla: yes

#4754 style: another batch of ErrorProne checks
  kythe/java/com/google/devtools/kythe/analyzers/base/CorpusPath.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
  kythe/java/com/google/devtools/kythe/platform/shared/CompilationUnits.java
  kythe/java/com/google/devtools/kythe/platform/shared/FileDataProvider.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/TestPlugin.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericComments.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Generics.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Imports.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Lambdas.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/BUILD
  tools/javacopts.bazelrc
Labels: cla: yes, cleanup

#4755 style: even more ErrorProne checks
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/SourceText.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
  kythe/java/com/google/devtools/kythe/analyzers/jvm/JvmGraph.java
  kythe/java/com/google/devtools/kythe/doc/DocUnbracketer.java
  kythe/java/com/google/devtools/kythe/doc/MarkedSourceRenderer.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/JarExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BazelJvmExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/shared/ExtractorUtils.java
  kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
  kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
  kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipReader.java
  kythe/java/com/google/devtools/kythe/platform/shared/CompilationUnits.java
  kythe/java/com/google/devtools/kythe/platform/shared/TestDataUtil.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemProvider.java
  kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java
  kythe/java/com/google/devtools/kythe/util/JsonUtil.java
  kythe/java/com/google/devtools/kythe/util/QualifiedNameExtractor.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AutoValues.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Imports.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Interfaces.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/SpecialMembers.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/Nullable.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/NullableRef.java
  kythe/javatests/com/google/devtools/kythe/util/KytheURITest.java
  tools/javacopts.bazelrc
Labels: cla: yes, cleanup

#4756 fix(java_indexer): emit references to .class literals
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/analyzers/java/SourceText.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/SpecialMembers.java
Labels: cla: yes, indexing, java

#4757 fix(cxx_common): always initialize fields in FileOutputStream
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/indexing/KytheCachingOutput.cc
  kythe/cxx/common/indexing/KytheCachingOutput.h
Labels: cla: yes

#4749 feat(verifier): add souffle/libffi
  autotools.bzl
  external.bzl
  third_party/libffi.BUILD
  third_party/souffle.BUILD
Labels: cla: yes

#4758 fix(java_indexer): add MarkedSource for class initializer
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
Labels: cla: yes, indexing, java

#4745 chore(docs): add tag/static and tag/abstract documentation
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4761 fix(docs): fix some squigglies for rendering
  kythe/docs/schema/schema.txt
  kythe/web/site/Gemfile.lock
Labels: cla: yes

#4762 chore: update LLVM
  kythe/cxx/tools/fyi/fyi.cc
  tools/build_rules/llvm/BUILD
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4763 chore: update bazel-toolchains repo
  WORKSPACE
Labels: cla: yes

#4747 chore(go_indexer): Add a marked source test for methods
  kythe/go/indexer/testdata/code/methdecl.go
Labels: cla: yes

#4764 feat(cxx_common): extend bazel artifact selection to allow stateful selectors
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/bazel_artifact.h
  kythe/cxx/extractor/bazel_artifact_reader.cc
  kythe/cxx/extractor/bazel_artifact_reader.h
  kythe/cxx/extractor/bazel_artifact_selector.cc
  kythe/cxx/extractor/bazel_artifact_selector.h
  kythe/cxx/extractor/bazel_artifact_selector_test.cc
  kythe/proto/BUILD
  kythe/proto/bazel_artifact_selector.proto
  tools/build_rules/build_event_stream/repo.bzl
Labels: cla: yes

#4766 chore: fix typo in comment
  kythe/cxx/extractor/bazel_artifact_selector.h
  kythe/cxx/extractor/bazel_artifact_selector_test.cc
Labels: cla: yes

#4767 feat(verifier): compile and run a simple datalog program
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/souffle_interpreter.cc
  kythe/cxx/verifier/souffle_interpreter.h
  kythe/cxx/verifier/souffle_interpreter_test.cc
  third_party/souffle.BUILD
  third_party/souffle/BUILD
  third_party/souffle/LICENSE
  third_party/souffle/README.google
  third_party/souffle/parse_transform.cc
  third_party/souffle/parse_transform.h
Labels: cla: yes
