Repository kythe/kythe, pull requests merged in 2020-06, with the labels that each got.

#4529 chore: migrate most jsonpb usages to proto v2 API
  kythe/go/extractors/config/BUILD
  kythe/go/extractors/config/config_parser_test.go
  kythe/go/extractors/config/config_selector.go
  kythe/go/extractors/config/config_selector_test.go
  kythe/go/extractors/gcp/config/BUILD
  kythe/go/extractors/gcp/config/converter.go
  kythe/go/platform/kcd/kythe/BUILD
  kythe/go/platform/kcd/kythe/units.go
  kythe/go/platform/kcd/kythe/units_test.go
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/kzip/kzip_test.go
  kythe/go/platform/tools/kzip/createcmd/BUILD
  kythe/go/platform/tools/kzip/createcmd/flag.go
  kythe/go/platform/tools/kzip/infocmd/BUILD
  kythe/go/platform/tools/kzip/infocmd/infocmd.go
  kythe/go/platform/tools/kzip/viewcmd/BUILD
  kythe/go/platform/tools/kzip/viewcmd/viewcmd.go
  kythe/go/platform/tools/viewindex/BUILD
  kythe/go/platform/tools/viewindex/viewindex.go
  kythe/go/services/cli/BUILD
  kythe/go/services/cli/cli.go
  kythe/go/services/link/BUILD
  kythe/go/services/link/link.go
  kythe/go/services/link/link_test.go
  kythe/go/services/web/BUILD
  kythe/go/services/web/web.go
  kythe/go/util/tools/vnames/BUILD
  kythe/go/util/tools/vnames/apply.go
  kythe/go/util/vnameutil/BUILD
  kythe/go/util/vnameutil/rewrite.go
  kythe/go/util/vnameutil/rewrite_test.go
  kythe/go/util/vnameutil/test/test_vname_rules.go
  kythe/proto/BUILD
Labels: cla: yes

#4500 docs: add context for the correct use of ref/id
  kythe/docs/schema/schema.txt
Labels: buildbot, cla: yes

#4531 example(rust): Create Rust example project
  .gitignore
  external.bzl
  kythe/rust/examples/hello_world/BUILD
  kythe/rust/examples/hello_world/README.md
  kythe/rust/examples/hello_world/cargo/BUILD
  kythe/rust/examples/hello_world/cargo/Cargo.lock
  kythe/rust/examples/hello_world/cargo/Cargo.toml
  kythe/rust/examples/hello_world/cargo/crates.bzl
  kythe/rust/examples/hello_world/cargo/remote/BUILD
  kythe/rust/examples/hello_world/cargo/remote/atty-0.2.14.BUILD
  kythe/rust/examples/hello_world/cargo/remote/colored-1.9.3.BUILD
  kythe/rust/examples/hello_world/cargo/remote/hermit-abi-0.1.13.BUILD
  kythe/rust/examples/hello_world/cargo/remote/lazy_static-1.4.0.BUILD
  kythe/rust/examples/hello_world/cargo/remote/libc-0.2.71.BUILD
  kythe/rust/examples/hello_world/cargo/remote/winapi-0.3.8.BUILD
  kythe/rust/examples/hello_world/cargo/remote/winapi-i686-pc-windows-gnu-0.4.0.BUILD
  kythe/rust/examples/hello_world/cargo/remote/winapi-x86_64-pc-windows-gnu-0.4.0.BUILD
  kythe/rust/examples/hello_world/src/main.rs
  setup.bzl
Labels: buildbot, cla: yes

#4536 docs(runextractor): add more detail on using runextractor
  kythe/web/site/examples.md
Labels: cla: yes

#4538 chore: update max bazel version to 3.2.0
  .bazelversion
  WORKSPACE
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.2.0/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4537 feat(rust): Add basic Rust extractor
  kythe/extractors/BUILD
Labels: buildbot, cla: yes, extraction

#4539 feat(rust): Remove deprecated Rust indexer
  kythe/rust/indexer/.gitignore
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/Cargo.toml
  kythe/rust/indexer/README.md
  kythe/rust/indexer/src/kythe/mod.rs
  kythe/rust/indexer/src/kythe/schema.rs
  kythe/rust/indexer/src/kythe/writer.rs
  kythe/rust/indexer/src/lib.rs
  kythe/rust/indexer/src/pass.rs
  kythe/rust/indexer/src/visitor.rs
  kythe/rust/indexer/testdata/BUILD
  kythe/rust/indexer/testdata/basic/a.rs
  kythe/rust/indexer/testdata/basic/const.rs
  kythe/rust/indexer/testdata/basic/file_content.rs
  kythe/rust/indexer/testdata/basic/file_node.rs
  kythe/rust/indexer/testdata/basic/static.rs
  kythe/rust/indexer/testdata/basic/var_ref.rs
  kythe/rust/indexer/testdata/basic/vardecl_local_anchor.rs
  kythe/rust/indexer/testdata/basic/vardecl_local_destructure.rs
  kythe/rust/indexer/testdata/basic/vardecl_local_shadow.rs
  kythe/rust/indexer/testdata/function/function_call.rs
  kythe/rust/indexer/testdata/function/function_decl.rs
  kythe/rust/indexer/testdata/function/function_for_loop.rs
  kythe/rust/indexer/testdata/function/function_params.rs
  kythe/rust/indexer/testdata/function/function_reference.rs
  kythe/rust/indexer/testdata/function/function_unnamed.rs
  kythe/rust/indexer/testdata/function/impl_method_call.rs
  kythe/rust/indexer/testdata/function/method_instance_call.rs
  kythe/rust/indexer/testdata/function/method_static_call.rs
  kythe/rust/indexer/testdata/handle_results.sh
  kythe/rust/indexer/testdata/one_case.sh
  kythe/rust/indexer/testdata/parse_args.sh
  kythe/rust/indexer/testdata/rust_indexer_test.bzl
  kythe/rust/indexer/testdata/variants/enum_decl.rs
  kythe/rust/indexer/testdata/variants/enum_pat.rs
  kythe/rust/indexer/testdata/variants/struct_record.rs
  kythe/rust/indexer/testdata/variants/struct_record_pat.rs
  kythe/rust/indexer/testdata/variants/struct_tuple.rs
  kythe/rust/indexer/testdata/variants/struct_tuple_pat.rs
  kythe/rust/indexer/testdata/variants/struct_unit.rs
Labels: buildbot, cla: yes

#4540 fix(build): special case inconsistently-cased paths in LLVM build
  tools/build_rules/llvm/llvm.bzl
Labels: cla: yes

#4541 chore: partially migrate kythe/go/util to proto v2 API
  kythe/go/util/markedsource/BUILD
  kythe/go/util/markedsource/markedsource_test.go
  kythe/go/util/riegeli/BUILD
  kythe/go/util/riegeli/golden_test.go
  kythe/go/util/riegeli/reader.go
  kythe/go/util/riegeli/riegeli.go
  kythe/go/util/riegeli/riegeli_test.go
  kythe/go/util/riegeli/transpose_decoder.go
  kythe/go/util/riegeli/transpose_encoder.go
  kythe/go/util/riegeli/transpose_util.go
  kythe/go/util/riegeli/writer.go
  kythe/go/util/tools/scan_leveldb/BUILD
  kythe/go/util/tools/scan_leveldb/scan_leveldb.go
  kythe/go/util/tools/write_extra_action/BUILD
  kythe/go/util/tools/write_extra_action/write_extra_action.go
  third_party/riegeli/records_metadata_go_proto/records_metadata.pb.go
Labels: cla: yes

#4543 fix(cxx_common): typo in kzip_encoding.h
  kythe/cxx/common/kzip_encoding.h
Labels: cla: yes

#4544 feat(compdb): continue processing other compilations on error
  kythe/go/extractors/config/runextractor/compdb/compdb.go
Labels: cla: yes

#4546 feat(compdb): print out command for failed extractions
  kythe/go/extractors/config/runextractor/compdb/compdb.go
Labels: cla: yes

#4547 feat: Change kzip writer implementations to use proto kzip encoding by default.
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer_test.cc
  kythe/cxx/extractor/testdata/test_kzip.sh
  kythe/go/platform/kzip/kzip.go
  kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java
Labels: buildbot, cla: yes

#4545 feat(kzip): add subcommand and proto for metadata kzips
  kythe/go/platform/kzip/buildmetadata/BUILD
  kythe/go/platform/kzip/buildmetadata/buildmetadata.go
  kythe/go/platform/tools/kzip/BUILD
  kythe/go/platform/tools/kzip/kzip.go
  kythe/go/platform/tools/kzip/metadatacmd/BUILD
  kythe/go/platform/tools/kzip/metadatacmd/metadatacmd.go
  kythe/go/platform/tools/kzip/metadatacmd/test.sh
  kythe/proto/BUILD
  kythe/proto/analysis.proto
  kythe/proto/analysis_go_proto/analysis.pb.go
Labels: cla: yes

#4548 fix(build): remove jq dependency
  kythe/go/platform/tools/kzip/metadatacmd/BUILD
  kythe/go/platform/tools/kzip/metadatacmd/test.sh
Labels: cla: yes

#4549 test(kzip metadata): save test kzip to $TEST_TMPDIR
  kythe/go/platform/tools/kzip/metadatacmd/test.sh
Labels: cla: yes

#4551 Don't attempt to extract compilation from assembly
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
Labels: buildbot, cla: yes

#4552 Release v0.0.45
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4553 fix(verifier): compile with the xcode clang
  kythe/cxx/verifier/assertions.yy
Labels: cla: yes

#4555 fix(bazel extractor): fix path to bazelisk in docker image
  kythe/extractors/bazel/Dockerfile
Labels: cla: yes

#4554 feat(extraction): generate build metadata kzip in bazel-extractor docker image
  kythe/extractors/bazel/extract.sh
Labels: cla: yes

#4557 chore(kindex): remove deprecated viewindex tool
  kythe/go/platform/tools/viewindex/BUILD
  kythe/go/platform/tools/viewindex/viewindex.go
  kythe/javatests/com/google/devtools/kythe/analyzers/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/indexer_test.sh
  kythe/release/BUILD
  kythe/release/README.md
  kythe/release/release_test.sh
  kythe/testdata/test.kindex
Labels: cla: yes

#4556 feat(cxx_indexer): blame variable references on the surrounding context
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/clang_utils.cc
  kythe/cxx/indexer/cxx/clang_utils.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/df/df_var_ref_blame.cc
  kythe/cxx/indexer/cxx/testdata/df/df_var_ref_file_blame.cc
Labels: cla: yes

#4558 feat(cxx_indexer): annotate edges we know are writes to vars and ivars
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/clang_utils.cc
  kythe/cxx/indexer/cxx/clang_utils.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/df/df_var_ref_blame.cc
  kythe/cxx/indexer/cxx/testdata/df/df_var_rw.cc
  kythe/cxx/indexer/cxx/testdata/objc/categories/extension_property.m
  kythe/cxx/indexer/cxx/testdata/objc/ivar_decl.m
  kythe/cxx/indexer/cxx/testdata/objc/property_decl_defn_synth.m
  kythe/cxx/indexer/cxx/testdata/rec/rec_class_member_ptr.cc
Labels: cla: yes

#4560 fix(cxx_indexer): properly filter empty ref/init exprs
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc
Labels: cla: yes

#4566 Bazel update
  .bazelversion
  WORKSPACE
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/cc/module.modulemap
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.0/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4567 fix: allow PushScope to work with braced-init
  kythe/cxx/common/BUILD
  kythe/cxx/common/scope_guard.h
  kythe/cxx/common/scope_guard_test.cc
Labels: cla: yes

#4559 feat(cxx_indexer): record var-to-var influence
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/indexer_worklist.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/df/df_var_influence.cc
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4563 TS Marked Source for object properties and class members
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/marked_source/property.ts
Labels: buildbot, cla: yes

#4561 Cleanup TS indexer types and build file
  kythe/typescript/indexer.ts
  kythe/typescript/package.json
  kythe/typescript/yarn.lock
Labels: buildbot, cla: yes

#4569 Support deprecated tags in TS marked source
  kythe/typescript/indexer.ts
  kythe/typescript/kythe.ts
  kythe/typescript/testdata/jsdoc.ts
Labels: buildbot, cla: yes

#4571 fix(cxx_indexer): make sure init-list-expr has a type
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
Labels: cla: yes
