Repository kythe/kythe, pull requests merged in 2020-08, with the labels that each got.

#4618 Remove deprecated flag from bazelrc
  .bazelrc
Labels: buildbot, cla: yes

#4619 build: add stub bzl_library rules
  BUILD
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/proto/testdata/BUILD
  kythe/cxx/extractor/textproto/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/proto/testdata/BUILD
  kythe/cxx/indexer/textproto/testdata/BUILD
  kythe/cxx/tools/fyi/testdata/BUILD
  kythe/data/BUILD
  kythe/docs/BUILD
  kythe/docs/schema/BUILD
  kythe/extractors/BUILD
  kythe/go/extractors/bazel/BUILD
  kythe/go/indexer/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/proto/BUILD
  kythe/rust/extractor/BUILD
  tools/build_rules/build_event_stream/BUILD
  tools/build_rules/external_tools/BUILD
  tools/build_rules/lexyacc/BUILD
  tools/build_rules/llvm/BUILD
  tools/build_rules/verifier_test/BUILD
Labels: build, cla: yes

#4615 feat(textproto): index enum values
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
  kythe/cxx/indexer/textproto/analyzer.cc
  kythe/cxx/indexer/textproto/testdata/BUILD
  kythe/cxx/indexer/textproto/testdata/enum_value.pbtxt
  kythe/cxx/indexer/textproto/testdata/example.proto
Labels: cla: yes

#4620 chore: cleanup bzl lint errors
  tools/build_rules/verifier_test/BUILD
  tools/build_rules/verifier_test/rust_indexer_test.bzl
Labels: cla: yes

#4621 fix(serving): turn diffmatchpatch panics into internal errors
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/util/span/span.go
  kythe/go/util/span/span_test.go
Labels: cla: yes

#4622 fix(cxx_indexer): handle null init expr
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
Labels: cla: yes

#4617 feat(rust): Support emitting function definitions
  kythe/rust/cargo/BUILD
  kythe/rust/cargo/Cargo.lock
  kythe/rust/cargo/Cargo.toml
  kythe/rust/cargo/crates.bzl
  kythe/rust/cargo/remote/byteorder-1.3.4.BUILD
  kythe/rust/cargo/remote/derive-new-0.5.8.BUILD
  kythe/rust/cargo/remote/either-1.5.3.BUILD
  kythe/rust/cargo/remote/fst-0.3.5.BUILD
  kythe/rust/cargo/remote/itertools-0.8.2.BUILD
  kythe/rust/cargo/remote/itoa-0.4.6.BUILD
  kythe/rust/cargo/remote/json-0.11.15.BUILD
  kythe/rust/cargo/remote/log-0.4.11.BUILD
  kythe/rust/cargo/remote/proc-macro2-1.0.19.BUILD
  kythe/rust/cargo/remote/quote-1.0.7.BUILD
  kythe/rust/cargo/remote/rls-analysis-0.18.1.BUILD
  kythe/rust/cargo/remote/ryu-1.0.5.BUILD
  kythe/rust/cargo/remote/serde_json-1.0.57.BUILD
  kythe/rust/cargo/remote/syn-1.0.36.BUILD
  kythe/rust/cargo/remote/unicode-xid-0.2.1.BUILD
  kythe/rust/extractor/src/bin/extractor.rs
  kythe/rust/extractor/tests/integration_test.rs
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/error.rs
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/src/indexer/entries.rs
  kythe/rust/indexer/src/indexer/mod.rs
  kythe/rust/indexer/src/indexer/save_analysis.rs
  kythe/rust/indexer/src/providers.rs
  kythe/rust/indexer/testdata/anchors.rs
  kythe/rust/indexer/testdata/basic.rs
  kythe/rust/indexer/testdata/comment.rs
  kythe/rust/indexer/testdata/function.rs
  kythe/rust/indexer/tests/indexer_entries.rs
  kythe/rust/indexer/tests/indexer_save_analysis.rs
  kythe/rust/indexer/tests/lib.rs
  kythe/rust/indexer/tests/testanalysis.json
Labels: buildbot, cla: yes

#4625 fix(schema): document the use of special spans for implicit modules
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4627 chore(proto_indexer): remove unused FileVNameGenerator
  kythe/cxx/indexer/proto/indexer_frontend.cc
  kythe/cxx/indexer/proto/proto_analyzer.cc
  kythe/cxx/indexer/proto/proto_analyzer.h
Labels: cla: yes

#4628 fix(schema): add defines/implicit and examples
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4631 fix(cxx_indexer): avoid an assert check in Clang, silence errors
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/marked_source.cc
Labels: cla: yes

#4632 chore: extract schema node kind/subkind methods
  kythe/java/com/google/devtools/kythe/util/schema/Nodes.java
Labels: cla: yes

#4629 feat(rust): Add support to the Rust indexer for emitting module definitions and anchors
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/src/indexer/mod.rs
  kythe/rust/indexer/src/indexer/offset.rs
  kythe/rust/indexer/src/lib.rs
  kythe/rust/indexer/testdata/modules/main.rs
  kythe/rust/indexer/testdata/modules/test.rs
Labels: buildbot, cla: yes

#4624 feat(fuchsia): Fuchsia-specific extractor
  kythe/cxx/common/kzip_writer_c_api.cc
  kythe/rust/cargo/BUILD
  kythe/rust/cargo/Cargo.toml
  kythe/rust/cargo/remote/argh-0.1.3.BUILD
  kythe/rust/cargo/remote/argh_derive-0.1.1.BUILD
  kythe/rust/cargo/remote/argh_shared-0.1.1.BUILD
  kythe/rust/cargo/remote/heck-0.3.1.BUILD
  kythe/rust/cargo/remote/proc-macro-error-1.0.3.BUILD
  kythe/rust/cargo/remote/proc-macro-error-attr-1.0.3.BUILD
  kythe/rust/cargo/remote/regexp-0.3.2.BUILD
  kythe/rust/cargo/remote/structopt-0.3.15.BUILD
  kythe/rust/cargo/remote/structopt-derive-0.4.8.BUILD
  kythe/rust/cargo/remote/syn-mid-0.5.0.BUILD
  kythe/rust/cargo/remote/unicode-segmentation-1.6.0.BUILD
  kythe/rust/cargo/remote/version_check-0.9.2.BUILD
  kythe/rust/fuchsia_extractor/BUILD
  kythe/rust/fuchsia_extractor/README.md
  kythe/rust/fuchsia_extractor/src/bin/main.rs
  kythe/rust/fuchsia_extractor/src/kzip.rs
  kythe/rust/fuchsia_extractor/testdata/BUILD
  kythe/rust/fuchsia_extractor/testdata/README.md
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/out/terminal.x64/save-analysis-temp/nom.json
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/out/terminal.x64/x64-shared/obj/third_party/rust_crates/liblazy_static-cdf593bd3fb3d68f.rlib
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/out/terminal.x64/x64-shared/obj/third_party/rust_crates/libmemchr-523a962cdfbcb111.rlib
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/out/terminal.x64/x64-shared/obj/third_party/rust_crates/libregex-be3eec66bf66867d.rlib
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/third_party/rust_crates/vendor/nom/dir/file.rs
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/third_party/rust_crates/vendor/nom/dummy
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/third_party/rust_crates/vendor/nom/lib.rs
Labels: buildbot, cla: yes

#4634 feat(rust): Adds Fuchsia Rust extractor to release
  kythe/release/BUILD
Labels: buildbot, cla: yes

#4635 chore: update Gem dependencies
  kythe/web/site/Gemfile.lock
Labels: cla: yes

#4633 feat(rust): Add support for indexing enums
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/testdata/enum.rs
Labels: buildbot, cla: yes

#4639 Replace `stream::iterator` with alternatives in enhanced for loops.
  kythe/java/com/google/devtools/kythe/extractors/java/SystemExploder.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: buildbot, cla: yes

#4637 fix(rust): Fix fuchsia_extractor test data
  kythe/rust/cargo/Cargo.lock
  kythe/rust/fuchsia_extractor/src/bin/main.rs
  kythe/rust/fuchsia_extractor/src/kzip.rs
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/third_party/rust_crates/vendor/nom/dir/file.rs
  kythe/rust/fuchsia_extractor/testdata/test_dir_1/compilation-root/third_party/rust_crates/vendor/nom/lib.rs
Labels: buildbot, cla: yes

#4638 feat(rust): Support emitting remaining definition types
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/testdata/struct.rs
  kythe/rust/indexer/testdata/tbuiltin.rs
  kythe/rust/indexer/testdata/trait.rs
  kythe/rust/indexer/testdata/type.rs
  kythe/rust/indexer/testdata/union.rs
  kythe/rust/indexer/testdata/variable.rs
  tools/rust/rustfmt.sh
Labels: buildbot, cla: yes

#4642 fix(rust): Fix small bugs in the Rust implementation
  kythe/rust/extractor/src/bin/extractor.rs
  kythe/rust/indexer/testdata/struct.rs
Labels: buildbot, cla: yes

#4640 feat(rust): Makes the extractor more robust
  kythe/rust/fuchsia_extractor/src/bin/main.rs
Labels: buildbot, cla: yes

#4644 fix(rust): Fix Rust indexer issue with Trait definitions
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/testdata/modules/test.rs
  kythe/rust/indexer/testdata/struct.rs
  kythe/rust/indexer/testdata/trait.rs
Labels: buildbot, cla: yes

#4641 feat(rust): Add support for Rust cross-references
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/src/indexer/entries.rs
  kythe/rust/indexer/testdata/xrefs.rs
Labels: buildbot, cla: yes

#4646 fix(rust): write_all instead of write in the extractor
  kythe/rust/extractor/src/bin/extractor.rs
Labels: buildbot, cla: yes

#4645 fix(rust): Fix definition anchors and xrefs in the indexer
  kythe/rust/fuchsia_extractor/src/bin/main.rs
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/indexer/analyzers.rs
  kythe/rust/indexer/testdata/xrefs/log.rs
  kythe/rust/indexer/testdata/xrefs/main.rs
  tools/rust/extra_action/src/main.rs
Labels: buildbot, cla: yes

#4649 fix(tools): kzip merge uses proto as default encoding
  kythe/go/platform/kzip/kzip.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#4650 fix(rust): Fixes the kzip generation
  kythe/rust/fuchsia_extractor/BUILD
  kythe/rust/fuchsia_extractor/src/bin/main.rs
Labels: buildbot, cla: yes

#4651 chore: enable symbolized stacktraces on crash
  kythe/cxx/common/BUILD
  kythe/cxx/common/init.cc
  kythe/cxx/common/init.h
  kythe/cxx/doc/BUILD
  kythe/cxx/doc/doc.cc
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor_bazel_main.cc
  kythe/cxx/extractor/cxx_extractor_main.cc
  kythe/cxx/extractor/dump_bazel_artifacts.cc
  kythe/cxx/extractor/objc_extractor_bazel_main.cc
  kythe/cxx/extractor/proto/BUILD
  kythe/cxx/extractor/proto/proto_extractor_main.cc
  kythe/cxx/extractor/textproto/BUILD
  kythe/cxx/extractor/textproto/textproto_extractor.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/indexer/proto/kythe_indexer_main.cc
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/tools/fyi/fyi_main.cc
  kythe/cxx/tools/generate_compile_commands/BUILD
  kythe/cxx/tools/generate_compile_commands/extract_compile_command.cc
  kythe/cxx/tools/proto_metadata_plugin.cc
  kythe/cxx/tools/static_claim_main.cc
  kythe/cxx/verifier/BUILD
  kythe/cxx/verifier/verifier_main.cc
Labels: cla: yes

#4652 release: v0.0.46
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4654 fix(rust): Add crate name to generated signatures
  kythe/rust/indexer/src/indexer/analyzers.rs
Labels: buildbot, cla: yes

#4655 fix(cxx): normalize release config, include assert stacktraces
  .bazelrc
  kythe/cxx/common/BUILD
  kythe/cxx/common/init.cc
  kythe/release/setup_release.sh
Labels: cla: yes

#4647 fix(rust): parallelize the extraction process
  kythe/rust/cargo/BUILD
  kythe/rust/cargo/Cargo.toml
  kythe/rust/cargo/crates.bzl
  kythe/rust/cargo/remote/crossbeam-deque-0.7.3.BUILD
  kythe/rust/cargo/remote/crossbeam-epoch-0.8.2.BUILD
  kythe/rust/cargo/remote/crossbeam-queue-0.2.3.BUILD
  kythe/rust/cargo/remote/crossbeam-utils-0.7.2.BUILD
  kythe/rust/cargo/remote/maybe-uninit-2.0.0.BUILD
  kythe/rust/cargo/remote/memoffset-0.5.5.BUILD
  kythe/rust/cargo/remote/num_cpus-1.13.0.BUILD
  kythe/rust/cargo/remote/rayon-1.3.1.BUILD
  kythe/rust/cargo/remote/rayon-core-1.7.1.BUILD
  kythe/rust/fuchsia_extractor/BUILD
  kythe/rust/fuchsia_extractor/src/bin/main.rs
Labels: buildbot, cla: yes

#4657 Release v0.0.47
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4656 fix(textproto indexer): handle tabs correctly
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
  kythe/cxx/indexer/proto/offset_util.cc
  kythe/cxx/indexer/proto/offset_util.h
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/analyzer.cc
  kythe/cxx/indexer/textproto/testdata/basics.pbtxt
Labels: cla: yes

#4623 feat(textproto): prototype support for indexer plugins
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/analyzer.cc
  kythe/cxx/indexer/textproto/analyzer.h
  kythe/cxx/indexer/textproto/plugin.h
  kythe/cxx/indexer/textproto/plugins/example/BUILD
  kythe/cxx/indexer/textproto/plugins/example/plugin.cc
  kythe/cxx/indexer/textproto/plugins/example/plugin.h
  kythe/cxx/indexer/textproto/plugins/example/testdata/BUILD
  kythe/cxx/indexer/textproto/plugins/example/testdata/example.proto
  kythe/cxx/indexer/textproto/plugins/example/testdata/plugin_test.pbtxt
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
Labels: cla: yes

#4658 fix(textproto): remove StringPiece override of CreateAndAddAnchorNode
  kythe/cxx/indexer/textproto/analyzer.cc
Labels: cla: yes

#4660 chore(textproto): enable bazel layering_check
  kythe/cxx/indexer/textproto/analyzer.cc
  kythe/cxx/indexer/textproto/plugins/example/BUILD
  kythe/cxx/indexer/textproto/plugins/example/testdata/BUILD
Labels: cla: yes

#4659 feat(textproto): move plugin loader to a library
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/plugin_registry.cc
  kythe/cxx/indexer/textproto/plugin_registry.h
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
Labels: cla: yes

#4661 chore: add link to slack #general channel
  kythe/web/site/_data/development.yml
  kythe/web/site/development.md
Labels: cla: yes

#4662 chore: use a string to avoid accidental comment
  kythe/web/site/.gitignore
  kythe/web/site/development.md
Labels: cla: yes

#4663 feat(runextractor): Pass flags to the compdb extractor
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
  kythe/go/extractors/config/runextractor/compdb/compdb.go
  kythe/go/extractors/config/runextractor/compdb/compdb_test.go
  kythe/go/extractors/config/runextractor/compdbcmd/compdbcmd.go
Labels: buildbot, cla: yes

#4665 fix(fuschia_extractor_test): sort required_inputs
  kythe/rust/fuchsia_extractor/src/bin/main.rs
Labels: cla: yes

#4666 chore: refactor compdb extractor options
  .ycm_extra_conf.py
  kythe/go/extractors/config/runextractor/compdb/compdb.go
  kythe/go/extractors/config/runextractor/compdbcmd/compdbcmd.go
Labels: cla: yes

#4667 fix(bazel): align options between `query` and `build`
  .bazelrc
Labels: cla: yes

#4668 feat(textproto_verifier_test): allow multiple textproto files
  kythe/cxx/indexer/textproto/plugins/example/testdata/BUILD
  kythe/cxx/indexer/textproto/testdata/BUILD
  kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl
Labels: cla: yes

#4669 feat(textproto): make example plugin more interesting
  kythe/cxx/indexer/textproto/plugin_registry.cc
  kythe/cxx/indexer/textproto/plugins/example/plugin.cc
  kythe/cxx/indexer/textproto/plugins/example/plugin.h
  kythe/cxx/indexer/textproto/plugins/example/testdata/BUILD
  kythe/cxx/indexer/textproto/plugins/example/testdata/example.proto
  kythe/cxx/indexer/textproto/plugins/example/testdata/plugin_test.pbtxt
  kythe/cxx/indexer/textproto/plugins/example/testdata/syntax_test.pbtxt
  kythe/cxx/indexer/textproto/plugins/example/testdata/test1.pbtxt
  kythe/cxx/indexer/textproto/plugins/example/testdata/test2.pbtxt
Labels: cla: yes

#4673 chore: s/verifyFlags/checkFlags/ for internal consistency
  kythe/extractors/gcp/examples/restcheck/rest_auth_check.go
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
  kythe/go/extractors/config/runextractor/compdbcmd/compdbcmd.go
  kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
  kythe/go/extractors/config/runextractor/mavencmd/mavencmd.go
  kythe/go/extractors/gcp/config/yamlgen/yamlgen.go
  kythe/go/platform/tools/extraction/extractrepo/extractrepo.go
  kythe/go/platform/tools/extraction/repotester/repotester.go
Labels: cla: yes

#4674 feat(java_common): add methods to explode/implode a schema Node
  kythe/java/com/google/devtools/kythe/util/schema/Nodes.java
  kythe/javatests/com/google/devtools/kythe/util/schema/NodesTest.java
Labels: cla: yes
