Repository kythe/kythe, pull requests merged in 2020-10, with the labels that each got.

#4698 feat(api): add revision fields for file/anchor locations
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes

#4699 feat(api): add revision to non-anchor locations that may ref a file
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes

#4700 feat(cxx_indexer): opt-in to emitting influence edges
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/docs/schema/example-cxx.sh
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#4701 feat(cxx_indexer): add user-provided template instantiation excludelist
  kythe/cxx/common/BUILD
  kythe/cxx/common/re2_flag.cc
  kythe/cxx/common/re2_flag.h
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/clang_utils.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/template/exclude_this_file.h
  kythe/cxx/indexer/cxx/testdata/template/include_this_file.h
  kythe/cxx/indexer/cxx/testdata/template/template_exclude.cc
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#4702 chore: Make filegroup for testdata
  kythe/javatests/com/google/devtools/kythe/doc/BUILD
Labels: cla: yes

#4704 fix(go_test): dynamically create files for vfs_test
  kythe/go/platform/vfs/BUILD
  kythe/go/platform/vfs/testdata/a/b/*/c/empty.txt
  kythe/go/platform/vfs/testdata/a/b/c/d/empty.txt
  kythe/go/platform/vfs/vfs_test.go
Labels: cla: yes

#4705 chore: update bazel version to 3.6.0
  .bazelversion
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/cc/module.modulemap
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.6.0/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4706 chore: update bazel-toolchains to match bazel
  WORKSPACE
Labels: cla: yes

#4707 feat(common): add kytheuri CorpusPath helpers
  kythe/go/util/kytheuri/BUILD
  kythe/go/util/kytheuri/uri.go
  kythe/go/util/kytheuri/uri_test.go
  kythe/java/com/google/devtools/kythe/util/BUILD
  kythe/java/com/google/devtools/kythe/util/KytheURI.java
  kythe/javatests/com/google/devtools/kythe/util/BUILD
  kythe/javatests/com/google/devtools/kythe/util/KytheURITest.java
Labels: cla: yes

#4708 feat(serving): add revision serving fields for #4699/#4698
  kythe/proto/serving.proto
  kythe/proto/serving_go_proto/serving.pb.go
Labels: cla: yes, serving

#4709 chore(cxx_common): fix includes for uses absl::StatusOr
  kythe/cxx/common/BUILD
  kythe/cxx/common/json_proto.cc
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_reader_test.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer_test.cc
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/indexer/proto/kythe_indexer_main.cc
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
Labels: cla: yes

#4711 fix(build): use @io_kythe// instead of @// in bazel build file template
  tools/build_rules/external_tools/external_tools_configure.bzl
Labels: cla: yes

#4712 chore(build): move npm_install to external.bzl
  WORKSPACE
  external.bzl
Labels: cla: yes

#4713 chore(build): move bind() from WORKSPACE to external.bzl
  WORKSPACE
  external.bzl
Labels: cla: yes

#4710 feat(serving): plumb revision data for XRefService responses
  kythe/go/serving/xrefs/columnar.go
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
Labels: cla: yes, serving

#4714 feat(tooling): add optional analysis timeout to driver
  kythe/go/platform/analysis/driver/driver.go
  kythe/go/platform/analysis/driver/driver_test.go
Labels: cla: yes

#4715 fix(typescript_indexer): don't emit defines/binding for computed properties
  kythe/typescript/README.md
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/function.ts
  kythe/typescript/testdata/object.ts
Labels: buildbot, cla: yes

#4719 chore(typescript_indexer): group related test files in subdirectories.
  kythe/typescript/testdata/compilefail_group/compilefail.ts
  kythe/typescript/testdata/compilefail_group/compilefail_import.ts
  kythe/typescript/testdata/declaration_group/declaration.d.ts
  kythe/typescript/testdata/declaration_group/declaration_import.ts
  kythe/typescript/testdata/default_import_group/default_export.ts
  kythe/typescript/testdata/default_import_group/default_import.ts
  kythe/typescript/testdata/equals_export_group/equals_export.ts
  kythe/typescript/testdata/equals_export_group/equals_import.ts
  kythe/typescript/testdata/import.ts
  kythe/typescript/testdata/imports_dts_group/import.ts
  kythe/typescript/testdata/imports_dts_group/modules.d.ts
  kythe/typescript/testdata/imports_group/export.ts
  kythe/typescript/testdata/imports_group/import.ts
  kythe/typescript/testdata/imports_group/module.ts
  kythe/typescript/testdata/index_module_group/index_importer.ts
  kythe/typescript/testdata/index_module_group/index_module/index.ts
  kythe/typescript/testdata/schema.ts
Labels: buildbot, cla: yes

#4721 feat(textproto): expose DescriptorPool in plugin api
  kythe/cxx/indexer/textproto/analyzer.cc
  kythe/cxx/indexer/textproto/plugin.h
Labels: cla: yes

#4722 chore: properly use current toolchain/runtime in java_verifier_test
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#4724 chore: configure in-solidarity to ignore some generated files
  .github/in-solidarity.yml
Labels: cla: yes

#4723 chore: update to new LLVM version
  external.bzl
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/testdata/alternate_platform_test.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/tools/fyi/fyi.cc
  kythe/cxx/tools/fyi/testdata/nothing.cc.expected
  kythe/release/BUILD
  tools/build_rules/llvm/cmake_defines.bzl
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4726 chore: update some dependencies
  external.bzl
  setup.bzl
  third_party/libzip.BUILD
  third_party/libzip/BUILD
  third_party/libzip/genziperrs.py
  tools/build_rules/build_event_stream/repo.bzl
Labels: cla: yes

#4727 chore: update go dependencies
  external.bzl
  go.mod
  go.sum
  kythe/go/util/riegeli/BUILD
  kythe/go/util/riegeli/riegeli_test_go_proto/riegeli_test.pb.go
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/analysis_service_go_proto/analysis_service.pb.go
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/extraction_config_go_proto/extraction_config.pb.go
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/generate_go_protobufs.py
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/repo_go_proto/repo.pb.go
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/storage_service_go_proto/storage_service.pb.go
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
  setup.bzl
Labels: cla: yes

#4728 deprecation(api): remove deprecated DecorationsReply.generated_by field
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
  kythe/proto/xref.proto
  kythe/proto/xref_go_proto/xref.pb.go
Labels: API, cla: yes, cleanup

#3963 fix(doc): update documentation regarding (non)empty Root
  kythe/docs/kythe-storage.txt
Labels: cla: yes

#4729 chore: update more simple C++ dependencies
  external.bzl
Labels: cla: yes
