Repository kythe/kythe, pull requests merged in 2020-04, with the labels that each got.

#4460 feat: add lib for reading artifacts from bazel event streams
  external.bzl
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/bazel_artifact_reader.cc
  kythe/cxx/extractor/bazel_artifact_reader.h
  kythe/cxx/extractor/bazel_artifact_reader_test.cc
  kythe/cxx/extractor/bazel_event_reader.cc
  kythe/cxx/extractor/bazel_event_reader.h
  kythe/cxx/extractor/bazel_event_reader_test.cc
  kythe/cxx/extractor/dump_bazel_artifacts.cc
  tools/build_rules/build_event_stream/BUILD
  tools/build_rules/build_event_stream/repo.bzl
Labels: cla: yes

#4461 fix(cxx_indexer): emit zero-width spans for entities in macro bodies
  external.bzl
  kythe/cxx/indexer/cxx/clang_range_finder.cc
  kythe/cxx/indexer/cxx/clang_range_finder_test.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/macro_body.cc
Labels: cla: yes

#4462 fix(cxx_indexer): emit ref and ref/init for designated inits
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/rec/rec_designated_initializer.c
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4465 chore: update Bazel version
  .bazelversion
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.0.0/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4466 chore: update npm and yarn dependencies
  kythe/typescript/yarn.lock
  package-lock.json
  package.json
  setup.bzl
Labels: cla: yes

#4467 chore: normalize and fix schema formatting
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4468 fix(cxx_indexer): properly emit ref/init edges in all cases
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_designated_initializer.c
Labels: cla: yes

#4469 chore: fix buildbot groups
  kythe/release/appengine/buildbot/master/master.cfg
Labels: cla: yes

#4463 fix(ts_indexer): bug related to overriden functions.
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
  kythe/typescript/testdata/export_interface/implementation.ts
  kythe/typescript/testdata/export_interface/interface.ts
Labels: buildbot, cla: yes

#4470 chore(java_indexer): simplify access to field/method enclosing class
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes, indexing, java

#4472 fix(java_indexer): only consider Symbols without a source file external
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: API, cla: yes, indexing

#4471 fix(cxx_indexer): don't check-fail on copy-init-list
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc
Labels: cla: yes

#4474 chore(cxx_indexer): avoid redundant visitation of syntactic init lists
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
Labels: cla: yes

#4476 feat(cxx_indexer): emit ref/id to class when class and ctor overlap
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
  kythe/cxx/indexer/cxx/GraphObserver.h
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/testdata/function/function_ctor.cc
  kythe/cxx/indexer/cxx/testdata/function/function_ctor_new.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_ctor_dtor_ref_class.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_nested_ctor.cc
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4479 fix(extraction): deterministically write files to kzip
  kythe/go/extractors/bazel/extractor.go
Labels: cla: yes, extraction

#4480 chore: update LLVM; support extended integer types
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/recursive_type_visitor.h
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4481 build: suppress ErrorProne DefaultPackage error in testdata
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
Labels: cla: yes

#4482 test: fix extractor_test.go
  kythe/go/extractors/bazel/extractor.go
  kythe/go/extractors/bazel/extractor_test.go
Labels: cla: yes

#4483 feat(cxx_extractor): cache symlink resolution in PathRealizer
  kythe/cxx/common/BUILD
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils.h
Labels: cla: yes

#4484 chore(cxx_extractor): don't attempt to relativize builtin paths
  kythe/cxx/extractor/cxx_extractor.cc
Labels: cla: yes

#4477 build: update jrs250 annotations to tomcat v9.0.34
  external.bzl
  kythe/extractors/BUILD
  kythe/java/com/google/devtools/kythe/common/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
  kythe/release/BUILD
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#4485 chore: fix for clang-tidy issues
  kythe/cxx/common/path_utils.h
Labels: cla: yes

#4486 Release v0.0.44
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4487 fix(serving): avoid returning a nil node in map
  kythe/go/serving/xrefs/xrefs.go
Labels: cla: yes, serving

#4488 chore: update for bazel 3.1.0
  .bazelversion
  WORKSPACE
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.1.0/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4490 feat(java_indexer): experimentally emit named edges to JVM nodes
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java
Labels: cla: yes

#4491 build: specify long timeout for test
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#4492 feat: add BazelEventReaderInterface
  kythe/cxx/extractor/bazel_artifact_reader.h
  kythe/cxx/extractor/bazel_event_reader.h
Labels: cla: yes

#4495 fix(java_indexer): do not crash visiting special members
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/SpecialMembers.java
Labels: bug, cla: yes, indexing, java

#4496 fix(java_indexer): expand scope of null guard to handle primitives
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
Labels: bug, cla: yes, indexing, java

#4497 test(java_indexer): check @value document references
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
Labels: cla: yes, indexing, java

#4499 fix(java_indexer): avoid NPE when visiting lambda targets
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#4498 fix(java_indexer): don't crash on invalid paths in metadata loader
  kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java
Labels: cla: yes, indexing, java

#4501 chore: fix bazel toolchain url
  WORKSPACE
Labels: cla: yes

#4503 fix(java_indexer): handle ERROR types to avoid crashes
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes, indexing, java

#4505 docs(schema): use `named` edge to connect JVM nodes
  .commitlintrc.js
  kythe/docs/schema/example-java.sh
  kythe/docs/schema/schema.txt
  kythe/java/com/google/devtools/kythe/analyzers/jvm/DESIGN.md
Labels: cla: yes, documentation, schema

#4506 deprecation: remove obsolete Java name nodes
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Names.java
Labels: cla: yes, cleanup, indexing, java

#4507 fix(java_indexer): skip erroneous types to avoid NPEs
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes, indexing, java
