Repository kythe/kythe, pull requests merged in 2020-05, with the labels that each got.

#4508 fix(java_indexer): guard against exceptions when checking for errors
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes, indexing, java

#4509 fix(java_indexer): don't emit JVM nodes for erroneous types
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes, indexing, java

#4478 fix(ts_indexer): emit ref/call edges from calls.
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/class.ts
  kythe/typescript/testdata/refcall.ts
Labels: buildbot, cla: yes

#4510 chore(java_indexer): guard log line with --verbose flag
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
Labels: cla: yes

#4511 chore(typescript): fix lint warnings
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4512 chore(cxx_indexer): update LLVM to 123bee602a26
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/recursive_type_visitor.h
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4515 Fix memory leak in http_server.
  kythe/go/serving/xrefs/columnar.go
Labels: buildbot, cla: yes

#4516 fix(cxx_indexer): don't emit ref/init for unspecified fields
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc
Labels: cla: yes

#4517 fix(cxx_common): add compatibility type alias to StatusOr
  kythe/cxx/common/status_or.h
Labels: cla: yes

#4518 build: update rules_go
  .bazelminversion
  WORKSPACE
  external.bzl
  go.mod
  go.sum
  kythe/go/indexer/testdata/foo.a
  setup.bzl
  version.bzl
Labels: cla: yes

#4519 chore: update ycm_extra_conf to use bazel directly
  .gitignore
  .ycm_extra_conf.py
Labels: cla: yes

#4521 deprecation(java_indexer): remove --emit_jvm_references feature
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java
Labels: cla: yes, cleanup, indexing, java

#4522 feat: include local path for bazel artifacts
  kythe/cxx/extractor/bazel_artifact_reader.cc
  kythe/cxx/extractor/bazel_artifact_reader.h
  kythe/cxx/extractor/bazel_artifact_reader_test.cc
  kythe/cxx/extractor/dump_bazel_artifacts.cc
Labels: cla: yes

#4524 build: update generate_go_protobufs.py
  kythe/proto/generate_go_protobufs.py
Labels: cla: yes

#4525 build: update Go protobuf to v1.4.1
  external.bzl
  go.mod
  go.sum
  kythe/go/util/riegeli/riegeli_test_go_proto/riegeli_test.pb.go
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/analysis_service_go_proto/analysis_service.pb.go
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/extraction_config_go_proto/extraction_config.pb.go
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/repo_go_proto/repo.pb.go
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/storage_service_go_proto/storage_service.pb.go
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: cla: yes

#4528 Remove layering_check and parse_headers from cxx/intexer/proto package
  kythe/cxx/indexer/proto/BUILD
Labels: buildbot, cla: yes

#4523 Support generation of TS MarkedSource code facts
  WORKSPACE
  kythe/proto/BUILD
  kythe/typescript/BUILD
  kythe/typescript/indexer.ts
  kythe/typescript/test.ts
  kythe/typescript/testdata/marked_source/variable.ts
  kythe/typescript/tsconfig.json
  package-lock.json
  package.json
Labels: buildbot, cla: yes
