Repository kythe/kythe, pull requests merged in 2020-02, with the labels that each got.

#4345 feat: add and use vfs.Walk for recursive merge
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
  kythe/go/platform/vfs/vfs.go
Labels: cla: yes

#4346 test(extraction): check VNameRewriteRules can roundtrip through JSON
  kythe/go/util/vnameutil/BUILD
  kythe/go/util/vnameutil/rewrite.go
  kythe/go/util/vnameutil/rewrite_test.go
Labels: cla: yes

#4347 feat(tooling): add vnames utility for handling rewrite rules
  kythe/go/util/tools/vnames/BUILD
  kythe/go/util/tools/vnames/apply.go
  kythe/go/util/tools/vnames/convert.go
  kythe/go/util/tools/vnames/vnames.go
  kythe/go/util/vnameutil/BUILD
  kythe/go/util/vnameutil/rewrite.go
  kythe/go/util/vnameutil/rewrite_test.go
  kythe/proto/storage.proto
  kythe/proto/storage_go_proto/storage.pb.go
Labels: cla: yes

#4349 chore(tooling): add input/output path support to 'vnames convert-rules'
  kythe/go/util/tools/vnames/apply.go
  kythe/go/util/tools/vnames/convert.go
Labels: cla: yes

#4348 fix(go_indexer): use the anchor for the file-file generates edges
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/meta.go
Labels: cla: yes

#4350 test: ensure protos are compared properly
  kythe/go/util/vnameutil/rewrite_test.go
Labels: cla: yes

#4351 fix(tooling): keep track of added source file paths
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
Labels: cla: yes

#4352 fix(tooling): ensure VNameRewriteRule JSON encoding is canonical
  kythe/go/util/vnameutil/BUILD
  kythe/go/util/vnameutil/rewrite.go
  kythe/go/util/vnameutil/rewrite_test.go
Labels: cla: yes

#4353 fix(kzip_merge): add a test that globwalker behaves like filepath.Walk
  kythe/go/platform/vfs/BUILD
  kythe/go/platform/vfs/testdata/a/b/*/c/empty.txt
  kythe/go/platform/vfs/testdata/a/b/c/d/empty.txt
  kythe/go/platform/vfs/vfs.go
  kythe/go/platform/vfs/vfs_test.go
Labels: cla: yes

#4354 feat(extractors): add a passthrough bazel extractor
  kythe/go/extractors/cmd/bazel/copy_kzip/BUILD
  kythe/go/extractors/cmd/bazel/copy_kzip/copy_kzip.go
Labels: cla: yes

#4355 fix(copy_kzip): actually use err value
  kythe/go/extractors/cmd/bazel/copy_kzip/copy_kzip.go
Labels: cla: yes

#4356 build(bazel): support Bazel 2.1.0
  .bazelversion
  version.bzl
Labels: build, cla: yes

#4358 feat(cxx_indexer): emit USRs for macros (#4315)
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/usr_macro.cc
Labels: cla: yes

#4359 fix: centralize common shared testdata
  kythe/cxx/common/BUILD
  kythe/cxx/common/kzip_reader_test.cc
  kythe/cxx/common/kzip_writer_test.cc
  kythe/cxx/common/testdata/BUILD
  kythe/go/platform/kcd/kythe/BUILD
  kythe/go/platform/kcd/kythe/units_test.go
  kythe/go/platform/kzip/BUILD
  kythe/go/platform/kzip/kzip_test.go
  kythe/java/com/google/devtools/kythe/platform/shared/TestDataUtil.java
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/javatests/com/google/devtools/kythe/platform/shared/BUILD
  kythe/testdata/platform/56bf5044e1b5c4c1cc7c4b131ac2fb979d288460e63352b10eef80ca35bd0a7b.pbtxt
  kythe/testdata/platform/BUILD
  kythe/testdata/platform/bb761979683e7c268e967eb5bcdedaa7fa5d1d472b0826b00b69acafbaad7ee6.pbtxt
  kythe/testdata/platform/e9e170dcfca53c8126755bbc8b703994dedd3af32584291e01fba164ab5d3f32.pbtxt
  kythe/testdata/platform/empty.kzip
  kythe/testdata/platform/garbage_unit.kzip
  kythe/testdata/platform/malformed.kzip
  kythe/testdata/platform/missing-pbunit.kzip
  kythe/testdata/platform/missing-unit.kzip
  kythe/testdata/platform/stringset.kzip
  kythe/testdata/platform/stringset_with_empty_file.kzip
Labels: cla: yes

#4360 fix: centralize shared testdata protos
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/proto.cc
  kythe/cxx/indexer/cxx/testdata/proto/proto2.cc
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto2.java
  kythe/testdata/indexers/proto/BUILD
  kythe/testdata/indexers/proto/testdata.proto
  kythe/testdata/indexers/proto/testdata2.proto
Labels: cla: yes

#4361 fix(example): childof edges to files are no longer required
  kythe/docs/schema/writing-an-indexer.txt
Labels: cla: yes

#4364 update examples.md
  kythe/web/site/examples.md
Labels: buildbot, cla: yes

#4363 feat(cxx_indexer): add test for proto/c++ xrefs with included proto
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
  kythe/cxx/indexer/cxx/testdata/proto/proto3.cc
  kythe/testdata/indexers/proto/BUILD
  kythe/testdata/indexers/proto/testdata3.proto
  kythe/testdata/indexers/proto/testdata3a.proto
Labels: cla: yes

#4365 fix(copy_kzip): hard links always fail under bazel so don't try
  kythe/go/extractors/cmd/bazel/copy_kzip/copy_kzip.go
Labels: cla: yes

#4367 chore: Fixup binary comment
  kythe/go/extractors/cmd/gotool/gotool.go
Labels: cla: yes

#4368 fix: cc_kythe_proto_library handles multiple deps
  kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#4369 test: add VName test for corpus branch names
  kythe/cxx/common/kythe_uri_test.cc
  kythe/go/util/kytheuri/uri_test.go
  kythe/javatests/com/google/devtools/kythe/util/KytheURITest.java
Labels: cla: yes

#4370 fix: increase the coverage of the proto/cc indexing tests
  kythe/cxx/indexer/cxx/testdata/proto/BUILD
  kythe/cxx/indexer/cxx/testdata/proto/proto3.cc
  kythe/cxx/indexer/cxx/testdata/proto/proto4.cc
  kythe/testdata/indexers/proto/BUILD
  kythe/testdata/indexers/proto/testdata3.proto
  kythe/testdata/indexers/proto/testdata3b.proto
  kythe/testdata/indexers/proto/testdata4a.proto
  kythe/testdata/indexers/proto/testdata4b.proto
  kythe/testdata/indexers/proto/testdata4c.proto
Labels: cla: yes

#4366 feat(kzip_merge): allow applying vname rules during merge
  kythe/go/platform/tools/kzip/mergecmd/BUILD
  kythe/go/platform/tools/kzip/mergecmd/flag.go
  kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Labels: cla: yes

#4371 feat(cxx_indexer): add DebugString to VNameRef
  kythe/cxx/common/indexing/KytheOutputStream.h
Labels: cla: yes

#4372 fix(cxx_indexer): use anchor not decl for file-file generates endpoint
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
Labels: cla: yes

#4373 fix: use a more distinct corpus for the URI test
  kythe/javatests/com/google/devtools/kythe/util/KytheURITest.java
Labels: cla: yes

#4375 fix(vfs): use correct FileInfo in globWalker
  kythe/go/platform/vfs/vfs.go
  kythe/go/platform/vfs/vfs_test.go
Labels: cla: yes

#4376 fix(java_extractor_test): make error test less picky on required input
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#4377 fix(cxx_indexer): emit exactly one file-file generates edge for proto
  kythe/cxx/common/protobuf_metadata_file.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
Labels: cla: yes

#4378 fix(java_indexer): fix NPE on null diagnostic source
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
Labels: cla: yes

#4380 feat(go extractor): relativize paths against KYTHE_ROOT_DIRECTORY
  kythe/go/extractors/cmd/gotool/gotool.go
  kythe/go/extractors/golang/golang.go
  kythe/go/extractors/govname/govname.go
Labels: cla: yes

#4379 fix(cxx_indexer): address marked-source differences on builtin functions
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
Labels: cla: yes

#4382 fix(go_build): update deps to fix #4264
  .bazelminversion
  WORKSPACE
  external.bzl
  go.mod
  go.sum
  setup.bzl
  version.bzl
Labels: cla: yes

#4383 feat(go indexer): add option to only emit doc/uri facts for stdlib pkgs
  kythe/go/indexer/cmd/go_indexer/go_indexer.go
  kythe/go/indexer/emit.go
Labels: cla: yes

#4384 Release v0.0.42
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4386 fix(build): fix uses of empty globs
  .bazelrc
  third_party/go/BUILD
  tools/build_rules/llvm/llvm.bzl
Labels: cla: yes

#4387 chore: update npm managed dependencies
  kythe/typescript/yarn.lock
  package-lock.json
  package.json
  setup.bzl
Labels: cla: yes

#4388 docs: add instructions for extracting gradle projects
  kythe/web/site/examples.md
Labels: cla: yes

#4393 fix(runextractor): set --build_file default to build.gradle
  kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
Labels: cla: yes

#4394 fix: update to latest bazel version
  .bazelversion
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.1.1/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4398 fix(docs): s/gradle.build/build.gradle/
  kythe/go/extractors/config/preprocessor/README.md
  kythe/go/extractors/config/preprocessor/modifier/build_gradle_modifier.go
  kythe/go/extractors/config/preprocessor/modifier/pom_xml_modifier.go
  kythe/go/extractors/config/runextractor/README.md
  kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
Labels: cla: yes

#4399 feat(java_extractor): attribute corpus based on sources if unambiguous
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
  kythe/javatests/com/google/devtools/kythe/extractors/shared/FileVNamesTest.java
Labels: cla: yes, extraction, java

#4397 feat(runextractor): improved debug info for maven subcommand
  kythe/go/extractors/config/runextractor/backup/BUILD
  kythe/go/extractors/config/runextractor/backup/backup.go
  kythe/go/extractors/config/runextractor/mavencmd/mavencmd.go
Labels: cla: yes

#4400 fix(cxx_indexer): emit ref to class from ctor
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/rec/rec_ctor_dtor_ref_class.cc
Labels: cla: yes

#4391 fix(docs): improve formatting of gradle extraction example
  kythe/web/site/examples.md
Labels: cla: yes

#4403 Add property/reads and property/writes edge kinds to KytheGraphRecorder.
  kythe/cxx/common/indexing/KytheGraphRecorder.cc
  kythe/cxx/common/indexing/KytheGraphRecorder.h
Labels: buildbot, cla: yes

#4404 fix(cxx_common): migrate to absl::Status
  external.bzl
  kythe/cxx/common/BUILD
  kythe/cxx/common/index_reader.h
  kythe/cxx/common/index_writer.h
  kythe/cxx/common/json_proto.cc
  kythe/cxx/common/json_proto.h
  kythe/cxx/common/kzip_reader.cc
  kythe/cxx/common/kzip_reader.h
  kythe/cxx/common/kzip_reader_test.cc
  kythe/cxx/common/kzip_writer.cc
  kythe/cxx/common/kzip_writer.h
  kythe/cxx/common/kzip_writer_test.cc
  kythe/cxx/common/libzip/error.cc
  kythe/cxx/common/libzip/error.h
  kythe/cxx/common/path_utils.cc
  kythe/cxx/common/path_utils_test.cc
  kythe/cxx/common/status.cc
  kythe/cxx/common/status.h
  kythe/cxx/common/status_or.h
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/indexer/textproto/analyzer.cc
  kythe/cxx/indexer/textproto/analyzer.h
  kythe/cxx/indexer/textproto/textproto_indexer_main.cc
  kythe/cxx/verifier/assertion_ast.h
  setup.bzl
Labels: cla: yes

#4405 chore: remove redudnant genSrcDir parameter and ask fileManager
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#4406 Revert "chore: remove redudnant genSrcDir parameter and ask fileManag…
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#4407 fix(cxx_indexer): refactor TypeLoc visitation into separate class
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/recursive_type_visitor.h
  kythe/cxx/indexer/cxx/recursive_type_visitor_test.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/template/template_dependent_name_ref.cc
Labels: cla: yes

#4410 chore: update llvm to 84bd26afb62d
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4409 fix(cmake docs): make output directory before extracting
  kythe/web/site/examples.md
Labels: cla: yes

#4411 chore(java_extractor): use SOURCE_OUTPUT rather than genSrcDir
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes
