Repository kythe/kythe, pull requests merged in 2020-03, with the labels that each got.

#4412 docs: update minimum Clang version to 8
  kythe/web/site/getting-started.md
Labels: buildbot, cla: yes

#4413 Revert "fix(cxx_indexer): refactor TypeLoc visitation into separate c…
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/recursive_type_visitor.h
  kythe/cxx/indexer/cxx/recursive_type_visitor_test.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/template/template_dependent_name_ref.cc
Labels: cla: yes

#4414 feat(go_indexer): support GeneratedCodeInfo .meta textproto files
  kythe/go/indexer/cmd/go_indexer/BUILD
  kythe/go/indexer/cmd/go_indexer/go_indexer.go
Labels: cla: yes, go, indexing

#4416 chore: update max bazel version
  .bazelversion
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_2.2.0/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4417 feat(bazel_toolchains): add update script
  tools/platforms/configs/update.sh
Labels: cla: yes

#4419 chore: update bazelisk
  external.bzl
  kythe/extractors/bazel/BUILD
  kythe/extractors/bazel/Dockerfile
  kythe/release/kubernetes/buildkite/Dockerfile
Labels: cla: yes

#4420 fix(build): add dep for new version of bazelisk
  external.bzl
Labels: cla: yes

#4418 feat(cxx_indexer): allow using compilation corpus instead of empty
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/namespace_vnames.cc
  kythe/cxx/indexer/cxx/testdata/basic/vname_corpus.cc
  kythe/cxx/indexer/cxx/testdata/basic/vname_corpus.json
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#4422 fix(bazel-extractor): update docker image for c++17
  kythe/extractors/bazel/Dockerfile
Labels: cla: yes

#4424 fix(bazel extractor): add missing deps to docker image
  kythe/extractors/bazel/Dockerfile
Labels: cla: yes

#4357 feat(example): recommend a way to handle TypeScript/&c-style modules
  kythe/docs/schema/BUILD
  kythe/docs/schema/modules.txt
Labels: cla: yes, schema

#4425 fix(bazel_go_extractor): record canonical importpath for archives
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
Labels: cla: yes

#4415 fix(cxx_indexer): refactor TypeLoc visitation into separate class
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/indexed_parent_iterator.h
  kythe/cxx/indexer/cxx/recursive_type_visitor.h
  kythe/cxx/indexer/cxx/recursive_type_visitor_test.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/template/template_dependent_name_ref.cc
  kythe/cxx/indexer/cxx/testdata/template/template_dependent_sized_array.cc
Labels: cla: yes

#4426 fix(objc_tests): run objc tests on more platforms
  .bazelci/presubmit.yml
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/objc/categories/extension_property.h
  kythe/cxx/indexer/cxx/testdata/objc/categories/extension_property.m
  kythe/cxx/indexer/cxx/testdata/objc/property_decl_defn_synth.m
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#4427 chore: fix typo
  kythe/cxx/indexer/cxx/testdata/objc/property_decl_defn_synth.m
Labels: cla: yes

#4428 chore: update bazel-toolchains repo
  WORKSPACE
Labels: cla: yes

#4429 fix(cxx_indexer): avoid allocating TypeSourceInfo for type ids
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
Labels: cla: yes

#4431 fix(release): don't include the current working directory in release
  kythe/release/package_release.sh
Labels: cla: yes

#4432 release: v0.0.43
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4433 chore: these flags should no longer appear in the wild
  kythe/cxx/extractor/CommandLineUtils.cc
Labels: cla: yes

#4434 fix(java_indexer): only apply jdk override for non-source symbols
  kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/SunSource.java
Labels: cla: yes

#4436 feat(runextractor cmake): add -extra_cmake_args option
  kythe/go/extractors/config/runextractor/cmakecmd/BUILD
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
Labels: cla: yes

#4437 chore: update llvm
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/GoogleFlagsLibrarySupport.cc
  kythe/cxx/indexer/cxx/marked_source.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4438 feat(build): have arc run bazel test with named config
  .bazelrc
  tools/arc/unit/engine/BazelTestEngine.php
Labels: cla: yes

#4435 feat(indexing): add ref/id edge
  kythe/docs/schema/schema.txt
Labels: cla: yes

#4439 fix(cxx_indexer): update proto literal support to mirror current lib
  kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
  kythe/cxx/indexer/cxx/testdata/libraries/parsetextproto.h
  kythe/cxx/indexer/cxx/testdata/libraries/proto_parsetextproto_tabs.cc
Labels: cla: yes

#4440 chore: update go dependencies
  external.bzl
  go.mod
  go.sum
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/analysis_service_go_proto/analysis_service.pb.go
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/repo_go_proto/repo.pb.go
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/storage_service_go_proto/storage_service.pb.go
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
  setup.bzl
Labels: cla: yes

#4441 fix(java_indexer): ensure annotated type vars generate consistent VNames
  kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/Nullable.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/regression/NullableRef.java
Labels: cla: yes, indexing, java

#4442 docs: update JDK installation notes for macOS
  kythe/web/site/getting-started-macos.md
Labels: buildbot, cla: yes

#4443 fix(java_tests): export jdk_kzip
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/BUILD
Labels: cla: yes

#4444 chore(cxx_indexer): remove argument which is unused or invariant
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
Labels: cla: yes

#4445 chore: remove use of std::make_pair
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
Labels: cla: yes

#4446 build: avoid deprecated depset union operators
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
Labels: build, cla: yes

#4447 build: avoid deprecated depset union operators part 2
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: build, cla: yes

#4448 Support TypeScript 3.8 AST
  kythe/typescript/indexer.ts
  package-lock.json
  package.json
Labels: buildbot, cla: yes

#4449 chore(cxx_indexer): centralize and unittest some range handling
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/clang_range_finder.cc
  kythe/cxx/indexer/cxx/clang_range_finder.h
  kythe/cxx/indexer/cxx/clang_range_finder_test.cc
  kythe/cxx/indexer/cxx/clang_utils_test.cc
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/basic/new_operator.cc
  kythe/cxx/indexer/cxx/testdata/function/function_operator_overload_names.cc
Labels: cla: yes

#4450 chore(cxx_indexer): replace ad-hoc loc/range expansion w/ NormalizeRange
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/clang_range_finder.cc
  kythe/cxx/indexer/cxx/clang_range_finder.h
  kythe/cxx/indexer/cxx/clang_range_finder_test.cc
  kythe/cxx/indexer/cxx/clang_utils.cc
  kythe/cxx/indexer/cxx/clang_utils.h
  kythe/cxx/indexer/cxx/clang_utils_test.cc
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/cxx/testdata/function/function_member_operator.cc
Labels: cla: yes

#4451 chore: generate partial compile_commands.json
  .ycm_extra_conf.py
  tools/cpp/generate_compilation_database.sh
Labels: cla: yes

#4452 chore: remove spurious file data log messages
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/platform/shared/FileDataCache.java
Labels: cla: yes

#4453 chore: fix lint warnings
  kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
  kythe/java/com/google/devtools/kythe/platform/shared/BUILD
  kythe/java/com/google/devtools/kythe/platform/shared/FileDataCache.java
  kythe/proto/BUILD
Labels: cla: yes

#4454 chore: Add test for undecalred property getter
  kythe/cxx/indexer/cxx/testdata/objc/property_decl_defn.m
Labels: cla: yes

#4456 fix: require flex version 2.6 or newer
  kythe/web/site/getting-started.md
  tools/build_rules/lexyacc/lexyacc.bzl
Labels: cla: yes

#4457 docs: install flex via Homebrew for macOS
  kythe/web/site/getting-started-macos.md
  tools/build_rules/lexyacc/lexyacc.bzl
Labels: buildbot, cla: yes

#4458 feat(api): return Documentation node defs even if no facts are found
  kythe/go/serving/xrefs/xrefs.go
  kythe/go/serving/xrefs/xrefs_test.go
Labels: API, cla: yes

#4459 feat(cxx_indexer): expose a useful internal metadata loading function
  kythe/cxx/common/kythe_metadata_file.cc
  kythe/cxx/common/kythe_metadata_file.h
Labels: cla: yes
