Repository kythe/kythe, pull requests merged in 2020-01, with the labels that each got.

#4293 chore: exclude third_party from lint checks
  .arclint
Labels: cla: yes

#4294 chore: fix copyright year check
  tools/arc/linter.sh
Labels: cla: yes

#4295 chore: libraries with main should be binaries
  kythe/cxx/doc/BUILD
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/verifier/BUILD
Labels: cla: yes

#4297 fix(java_indexer): handle --system none properly
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4299 fix(java_indexer): use in-memory class_output path for modular builds
  external.bzl
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
Labels: cla: yes

#4301 fix(java_extractor): add the processor classpath to the extractor action
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
Labels: cla: yes, extraction, java

#4302 feat(kzip): add source/input directories recursively
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
Labels: cla: yes

#4303 feat(kzip_create): relativize input paths
  kythe/go/platform/tools/kzip/createcmd/createcmd.go
Labels: cla: yes

#4262 feat(java_indexer): support implicit protobuf metadata
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProtobufImplicitMetadata.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProtobufImplicitMetadata.java.pb.meta
Labels: cla: yes

#4304 fix(java_indexer): correctly reference JVM field nodes
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java
Labels: cla: yes

#4305 fix(java_common): filemanager NPE => UnsupportedOperationException
  kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
Labels: cla: yes

#4306 fix(java_extractor): java nits
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#4307 fix(java_indexer): only attempt to load implilcit metadata if it exists
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#4308 fix(java_indexer): lower severity of expected exceptions
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Labels: cla: yes

#4309 chore(kzip): expose Encoding of Reader
  kythe/go/platform/kzip/kzip.go
Labels: cla: yes

#4310 chore(java_indexer): group and classify diagnostics per-file
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
Labels: cla: yes

#4311 typescript: depend on node v10 definition of types
  kythe/typescript/package.json
  kythe/typescript/yarn.lock
Labels: buildbot, cla: yes

#4312 typescript: smarter cache of standard library
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#4313 chore(java_extractor): refactor java extractor for readability
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes

#4314 typescript: handle indexer crashes in tests
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#4316 typescript: run autoformatter
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4317 typescript: handle the case where symbol has no name
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/compilefail.ts
Labels: buildbot, cla: yes

#4318 chore(cmake): log the command we are running
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
Labels: cla: yes

#4319 chore(cmake): Tell cmake we are clang
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
Labels: cla: yes

#4320 release: v0.0.40
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4321 feat(java_indexer): add generates edges for proto-generated java files
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/java/com/google/devtools/kythe/platform/shared/Metadata.java
  kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto2.java
Labels: cla: yes

#4322 test(java_indexer): add tests for tag/deprecated facts on abs nodes
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DeprecationAnnotations.java
Labels: cla: yes

#4323 feat(java_extractor): allow passing search paths as a map
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes

#4325 chore: export testdata for external usage
  kythe/cxx/indexer/cxx/testdata/BUILD
Labels: cla: yes

#4324 fix(go extractor): treat -arc flag like -importpath
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
Labels: cla: yes

#4326 don't assume Symbol.valueDeclaration exists
  kythe/typescript/indexer.ts
Labels: buildbot, cla: yes

#4327 chore(java_extractor): refactor extraction into a separate class
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes

#4328 chore: update llvm to f6bb58542aca
  kythe/cxx/extractor/cxx_details.cc
  kythe/cxx/extractor/cxx_extractor.cc
  kythe/cxx/extractor/cxx_extractor_test.cc
  kythe/cxx/extractor/objc_bazel_support.cc
  kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheIndexerUnitTest.cc
  kythe/cxx/indexer/cxx/KytheVFS.cc
  kythe/cxx/indexer/cxx/frontend.cc
  kythe/cxx/indexer/cxx/marked_source.cc
  kythe/cxx/indexer/cxx/semantic_hash.cc
  kythe/cxx/tools/fyi/fyi.cc
  third_party/llvm/src/cxx_extractor_preprocessor_utils.cc
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/llvm/llvm.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4329 fix(java_extractor): use a stable working directory if possible
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
  kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
Labels: cla: yes

#4330 fix(java_extractor): wrong number of logger arguments
  kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Labels: cla: yes

#4331 fix(cxx_common): rework VNameRef to conform to VName, templatize VNameLess
  kythe/cxx/common/indexing/KytheOutputStream.h
  kythe/cxx/common/vname_ordering.h
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/examples/proto/proto_indexer.cc
Labels: cla: yes

#4333 chore: refactor openjdk11 build files
  kythe/extractors/openjdk11/BUILD
  kythe/extractors/openjdk11/extract/BUILD
  kythe/extractors/openjdk11/extract/extract.go
  kythe/extractors/openjdk11/java_wrapper/BUILD
Labels: cla: yes

#4334 chore: implement Get flag method
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes

#4332 feat(cxx_indexer): add generates edges for proto-generated files
  kythe/cxx/common/kythe_metadata_file.cc
  kythe/cxx/common/kythe_metadata_file.h
  kythe/cxx/common/protobuf_metadata_file.cc
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/KytheGraphObserver.cc
  kythe/cxx/indexer/cxx/KytheGraphObserver.h
  kythe/cxx/indexer/cxx/testdata/proto/proto2.cc
Labels: buildbot, cla: yes

#4335 fix: indirect runfiles path in opendjk11 extractor
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes

#4338 feat: allow openjdk11 build and src dirs to differ
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes

#4339 build: inline find_java_toolchain and find_java_runtime_toolchain
  tools/build_rules/verifier_test/java_verifier_test.bzl
Labels: cla: yes

#4340 Reuse splitters in KytheURI by making the private static final
  kythe/java/com/google/devtools/kythe/util/KytheURI.java
Labels: buildbot, cla: yes

#4341 feat: allow excluding modules from openjdk11 extraction
  kythe/extractors/openjdk11/extract/extract.go
  kythe/extractors/openjdk11/java_wrapper/BUILD
  kythe/extractors/openjdk11/java_wrapper/java_wrapper.go
Labels: buildbot, cla: yes

#4342 release: v0.0.41
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes

#4337 feat(go_indexer): add generates edges for proto-generated files
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/meta.go
  kythe/go/indexer/testdata/meta.go.linkage
Labels: cla: yes

#4343 chore: only print errors if there are any
  kythe/extractors/openjdk11/extract/extract.go
Labels: cla: yes
