Repository kythe/kythe, pull requests merged in 2020-07, with the labels that each got.

#4572 chore: update bazel to 3.3.1
  .bazelversion
  WORKSPACE
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/cc/module.modulemap
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.3.1/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4573 chore: keep_going on more arc bazel queries
  tools/arc/unit/engine/BazelTestEngine.php
Labels: cla: yes

#4575 build: remove dependency on generally unsupported stropts.h
  third_party/curl.BUILD
Labels: cla: yes

#4574 chore: update LLVM
  kythe/cxx/extractor/testdata/BUILD
  kythe/cxx/extractor/testdata/modules_test.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  tools/build_rules/llvm/generated_cmake_targets.bzl
  tools/build_rules/llvm/generated_llvm_build_targets.bzl
  tools/build_rules/llvm/repo.bzl
Labels: cla: yes

#4576 Convert PackAny's parameter to absl::string_view.
  kythe/cxx/common/json_proto.cc
  kythe/cxx/common/json_proto.h
Labels: buildbot, cla: yes

#4577 chore: add dummy attribute to ease imports
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/cpp/BUILD
  tools/cpp/dummy.sh
Labels: cla: yes

#4579 build(cmakecmd): remove dep on go-uuid
  kythe/go/extractors/config/runextractor/cmakecmd/BUILD
  kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
Labels: cla: yes

#4578 chore(cxx_extractor): silence warnings in the extractor
  kythe/cxx/extractor/cxx_extractor.cc
Labels: cla: yes

#4580 fix(cxx_indexer): increase flexibility of proto library plugin
  kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
  kythe/cxx/indexer/cxx/testdata/libraries/proto_parsetextproto.cc
Labels: cla: yes

#4564 feat(rust): Change Rust indexer FileProvider
  external.bzl
  kythe/rust/indexer/src/error.rs
  kythe/rust/indexer/src/providers.rs
  kythe/rust/indexer/testfiles/testkzip.kzip
  kythe/rust/indexer/tests/providers.rs
  setup.bzl
Labels: buildbot, cla: yes

#4581 chore: add namespace qualifier to global name
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
Labels: cla: yes

#4582 feat(go-extractor image): record commit timestamp in kzip
  kythe/go/extractors/cmd/gotool/analyze_packages.sh
Labels: cla: yes

#4584 fix(cxx_indexer): handle list-init on incomplete types
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc
Labels: cla: yes

#4585 chore: update toolchains for bazel 3.4.1
  .bazelversion
  WORKSPACE
  tools/platforms/configs/.latest.bazelrc
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/cc/armeabi_cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/cc/builtin_include_directory_paths
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/cc/cc_toolchain_config.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/cc/cc_wrapper.sh
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/cc/module.modulemap
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/config/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_3.4.1/java/BUILD
  tools/platforms/configs/versions.bzl
  version.bzl
Labels: cla: yes

#4586 chore: tell git to ignore .cache files
  .gitignore
Labels: cla: yes

#4587 chore: enable layering_check for select C++ packages
  kythe/cxx/common/BUILD
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/indexing/MemcachedHashCache.cc
  kythe/cxx/common/schema/BUILD
  kythe/cxx/doc/BUILD
  kythe/cxx/extractor/BUILD
  kythe/cxx/extractor/proto/BUILD
  kythe/cxx/extractor/textproto/BUILD
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/DynamicClaimClient.cc
  kythe/cxx/indexer/proto/BUILD
  kythe/cxx/indexer/textproto/BUILD
  kythe/cxx/tools/fyi/BUILD
  kythe/cxx/tools/generate_compile_commands/BUILD
  kythe/cxx/verifier/BUILD
  setup.bzl
  tools/build_rules/llvm/llvm.bzl
Labels: cla: yes

#4562 TS indexer: marked source for binding elements
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/marked_source/variable.ts
Labels: buildbot, cla: yes

#4588 Visit JSDocs for types and interfaces
  kythe/typescript/indexer.ts
  kythe/typescript/testdata/jsdoc.ts
Labels: buildbot, cla: yes

#4589 chore: remove unused includes/deps
  kythe/cxx/common/BUILD
  kythe/cxx/common/status.h
Labels: cla: yes

#4591 Do not group files in nested test directories by default
  kythe/typescript/test.ts
  kythe/typescript/testdata/export_interface_group/implementation.ts
  kythe/typescript/testdata/export_interface_group/interface.ts
  kythe/typescript/testdata/fake-genfiles_group/testdata/alt_module.ts
  kythe/typescript/testdata/imports_group/import.ts
  kythe/typescript/testdata/imports_group/modules.d.ts
  kythe/typescript/testdata/index_importer.ts
  kythe/typescript/testdata/index_module_group/index.ts
  kythe/typescript/testdata/reexport_group/main.ts
  kythe/typescript/testdata/reexport_group/reexport.ts
  kythe/typescript/testdata/tsconfig.for.tests.json
Labels: buildbot, cla: yes

#4593 Use template literal instead of concating number and string
  kythe/typescript/test.ts
Labels: buildbot, cla: yes

#4592 feat: Add support for defining environment variables passed to extractors
  kythe/extractors/extractors.bzl
Labels: buildbot, cla: yes

#4596 chore: update TS deps
  kythe/typescript/yarn.lock
  package-lock.json
  package.json
Labels: cla: yes

#4600 fix: Clean up old Rust tools
  tools/build_rules/rust/BUILD
  tools/build_rules/rust/cargo.bzl
  tools/build_rules/rust/run_cargo.sh
Labels: buildbot, cla: yes

#4601 fix: Remove old cargo-kythe directory
  kythe/rust/cargo-kythe/.gitignore
  kythe/rust/cargo-kythe/Cargo.toml
  kythe/rust/cargo-kythe/README.md
  kythe/rust/cargo-kythe/build.rs
  kythe/rust/cargo-kythe/src/main.rs
Labels: buildbot, cla: yes

#4594 feat: Add library for generating Rust save_analysis files
  external.bzl
  kythe/rust/extractor/BUILD
  kythe/rust/extractor/cargo/BUILD
  kythe/rust/extractor/cargo/Cargo.lock
  kythe/rust/extractor/cargo/Cargo.toml
  kythe/rust/extractor/cargo/crates.bzl
  kythe/rust/extractor/cargo/remote/BUILD
  kythe/rust/extractor/cargo/remote/fuchsia-cprng-0.1.1.BUILD
  kythe/rust/extractor/cargo/remote/libc-0.2.73.BUILD
  kythe/rust/extractor/cargo/remote/rand-0.4.6.BUILD
  kythe/rust/extractor/cargo/remote/rand_core-0.3.1.BUILD
  kythe/rust/extractor/cargo/remote/rand_core-0.4.2.BUILD
  kythe/rust/extractor/cargo/remote/rdrand-0.4.0.BUILD
  kythe/rust/extractor/cargo/remote/remove_dir_all-0.5.3.BUILD
  kythe/rust/extractor/cargo/remote/tempdir-0.3.7.BUILD
  kythe/rust/extractor/cargo/remote/winapi-0.3.9.BUILD
  kythe/rust/extractor/cargo/remote/winapi-i686-pc-windows-gnu-0.4.0.BUILD
  kythe/rust/extractor/cargo/remote/winapi-x86_64-pc-windows-gnu-0.4.0.BUILD
  kythe/rust/extractor/extractor_test.bzl
  kythe/rust/extractor/src/lib.rs
  kythe/rust/extractor/tests/test.rs
  setup.bzl
  tools/rust/rustfmt.sh
  tools/rust/rustfmt.toml
Labels: buildbot, cla: yes

#4610 feat(java_common): add ByteString overloads for fact value conversions
  kythe/go/util/schema/mkdata/mkdata.go
Labels: cla: yes

#4608 KZIP Writer C API (and Rust FFI)
  kythe/cxx/common/BUILD
  kythe/cxx/common/kzip_writer_c_api.cc
  kythe/cxx/common/kzip_writer_c_api.h
  kythe/cxx/common/kzip_writer_c_api_test.cc
  kythe/rust/fuchsia_extractor/BUILD
  kythe/rust/fuchsia_extractor/README.md
  kythe/rust/fuchsia_extractor/src/kzip.rs
  kythe/rust/fuchsia_extractor/src/kzip_sys.rs
  kythe/rust/fuchsia_extractor/src/lib.rs
Labels: buildbot, cla: yes

#4605 feat(rust): Create Rust indexer CLI
  kythe/rust/extractor/tests/integration_test.rs
  kythe/rust/fuchsia_extractor/src/kzip.rs
  kythe/rust/fuchsia_extractor/src/lib.rs
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/src/bin/main.rs
  kythe/rust/indexer/src/indexer/mod.rs
  kythe/rust/indexer/src/lib.rs
Labels: buildbot, cla: yes

#4613 fix(cxx_indexer): report errors more directly rather than stderr
  kythe/cxx/indexer/cxx/BUILD
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
Labels: cla: yes

#4614 fix(java_indexer): workaround JDK bug on Java 11
  kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java
  tools/git/pre-push.sh
Labels: cla: yes

#4612 feat(rust): Add Bazel rule for running Rust indexer tests
  kythe/rust/extractor/BUILD
  kythe/rust/extractor/extractor_test.bzl
  kythe/rust/indexer/BUILD
  kythe/rust/indexer/testdata/basic.rs
  kythe/rust/indexer/tests/providers.rs
  kythe/rust/indexer/tests/testkzip.kzip
  tools/build_rules/verifier_test/rust_indexer_test.bzl
  tools/rust/extra_action/BUILD
  tools/rust/extra_action/src/main.rs
  tools/rust/rustfmt.sh
Labels: buildbot, cla: yes

#4616 fix(rust): Ensure that Rust extractor creates a top-level folder
  .arclint
  kythe/rust/extractor/src/bin/extractor.rs
  kythe/rust/extractor/tests/integration_test.rs
  kythe/rust/indexer/src/providers.rs
Labels: buildbot, cla: yes

#4603 Add "web UI manual build note" to documentation
  kythe/web/site/examples.md
Labels: buildbot, cla: yes, documentation
