Repository kythe/kythe, pull requests merged in 2021-03, with the labels that each got.

#4846 chore: update protobuf to 3.15.3
  external.bzl
  kythe/go/util/riegeli/riegeli_test_go_proto/riegeli_test.pb.go
  kythe/proto/analysis_go_proto/analysis.pb.go
  kythe/proto/analysis_service_go_proto/analysis_service.pb.go
  kythe/proto/buildinfo_go_proto/buildinfo.pb.go
  kythe/proto/claim_go_proto/claim.pb.go
  kythe/proto/common_go_proto/common.pb.go
  kythe/proto/cxx_go_proto/cxx.pb.go
  kythe/proto/driver_go_proto/driver.pb.go
  kythe/proto/entryset_go_proto/entryset.pb.go
  kythe/proto/explore_go_proto/explore.pb.go
  kythe/proto/extraction_config_go_proto/extraction_config.pb.go
  kythe/proto/filecontext_go_proto/filecontext.pb.go
  kythe/proto/filetree_go_proto/filetree.pb.go
  kythe/proto/go_go_proto/go.pb.go
  kythe/proto/graph_go_proto/graph.pb.go
  kythe/proto/graph_serving_go_proto/graph_serving.pb.go
  kythe/proto/identifier_go_proto/identifier.pb.go
  kythe/proto/internal_go_proto/internal.pb.go
  kythe/proto/java_go_proto/java.pb.go
  kythe/proto/link_go_proto/link.pb.go
  kythe/proto/pipeline_go_proto/pipeline.pb.go
  kythe/proto/repo_go_proto/repo.pb.go
  kythe/proto/schema_go_proto/schema.pb.go
  kythe/proto/serving_go_proto/serving.pb.go
  kythe/proto/status_service_go_proto/status_service.pb.go
  kythe/proto/storage_go_proto/storage.pb.go
  kythe/proto/storage_service_go_proto/storage_service.pb.go
  kythe/proto/xref_go_proto/xref.pb.go
  kythe/proto/xref_serving_go_proto/xref_serving.pb.go
Labels: buildbot, cla: yes

#4850 chore: run buildifier on relevant BUILD files
  .bazelrc
  kythe/go/serving/pipeline/beamio/BUILD
  kythe/rust/extractor/BUILD
  kythe/rust/indexer/BUILD
Labels: cla: yes

#4849 fix(java): ensure a corpus is always set in extracted compilation units
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
  kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
  kythe/java/com/google/devtools/kythe/extractors/shared/EnvironmentUtils.java
  kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
  kythe/javatests/com/google/devtools/kythe/extractors/shared/BUILD
Labels: buildbot, cla: yes

#4852 Ensure correct dependency on cc toolchain from Starlark rules.
  tools/build_rules/verifier_test/rust_indexer_test.bzl
Labels: cla: yes

#4854 chore(go_indexer): make Go indexer err checkable
  kythe/go/indexer/indexer.go
Labels: cla: yes

#4853 chore: fix lint issues found by buildifier
  BUILD
  kythe/cxx/common/BUILD
  kythe/cxx/common/indexing/BUILD
  kythe/cxx/common/testdata/BUILD
  kythe/cxx/indexer/cxx/testdata/BUILD
  kythe/cxx/indexer/proto/testdata/BUILD
  kythe/cxx/indexer/proto/testdata/proto_verifier_test.bzl
  kythe/cxx/indexer/textproto/plugins/example/BUILD
  kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl
  kythe/cxx/tools/BUILD
  kythe/cxx/tools/fyi/testdata/BUILD
  kythe/cxx/tools/testdata/BUILD
  kythe/cxx/verifier/BUILD
  kythe/data/BUILD
  kythe/docs/asciidoc.bzl
  kythe/extractors/BUILD
  kythe/go/extractors/gcp/config/kziptool/BUILD
  kythe/go/indexer/BUILD
  kythe/go/serving/pipeline/beamtest/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
  kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
  kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
  kythe/javatests/com/google/devtools/kythe/platform/kzip/BUILD
  kythe/proto/BUILD
  kythe/proto/go.bzl
  kythe/release/base/BUILD
  kythe/release/release.BUILD
  kythe/rust/extractor/BUILD
  kythe/rust/fuchsia_extractor/BUILD
  kythe/rust/indexer/BUILD
  kythe/typescript/BUILD
  setup.bzl
  third_party/bazel/BUILD
  third_party/beam/BUILD
  third_party/libzip.BUILD
  third_party/riegeli/BUILD
  third_party/souffle.BUILD
  third_party/souffle/BUILD
  tools/build_rules/docker.bzl
  tools/build_rules/lexyacc/BUILD
  tools/build_rules/llvm/llvm.BUILD
  tools/build_rules/shims.bzl
  tools/build_rules/verifier_test/cc_indexer_test.bzl
  tools/build_rules/verifier_test/java_verifier_test.bzl
  tools/build_rules/verifier_test/jvm_verifier_test.bzl
  tools/build_rules/verifier_test/verifier_test.bzl
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_4.0.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_4.0.0/config/BUILD
  tools/rust/extra_action/BUILD
Labels: cla: yes

#4855 chore: add logname to keep command output
  kythe/release/appengine/buildbot/master/master.cfg
Labels: cla: yes

#4856 chore: add ruby-dev to the buildbot worker
  kythe/release/appengine/buildbot/Dockerfile
Labels: cla: yes

#4843 fix(typescript): tslints
  kythe/typescript/indexer.ts
Labels: cla: yes

#4859 Close the graph columnar db iterator.
  kythe/go/serving/graph/columnar.go
Labels: buildbot, cla: yes

#4861 fix(java): emit "static" facts for classes and methods
  kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/StaticMethods.java
  kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Variables.java
Labels: cla: yes

#4862 fix(serving): move defer to after error check
  kythe/go/serving/graph/columnar.go
Labels: cla: yes

#4857 fix(docs): Use rules_ruby to hermetically generated the web site
  .gitignore
  WORKSPACE
  external.bzl
  kythe/docs/BUILD
  kythe/docs/asciidoc.bzl
  kythe/docs/schema/BUILD
  kythe/release/appengine/default/deploy.sh
  kythe/web/site/.gitignore
  kythe/web/site/BUILD
  kythe/web/site/Gemfile
  kythe/web/site/Gemfile.lock
  kythe/web/site/_config.yml
  kythe/web/site/build.sh
  kythe/web/site/check_links.sh
  kythe/web/site/check_links_test.sh
  kythe/web/site/doc_header.rb
  kythe/web/site/site_docs.bzl
  kythe/web/site/sync_docs.sh
  setup.bzl
  third_party/rules_ruby_allow_empty.patch
  tools/platforms/BUILD
  tools/platforms/Dockerfile
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_4.0.0/cc/BUILD
  tools/platforms/configs/default_toolchain_config_spec_name/bazel_4.0.0/config/BUILD
Labels: cla: yes

#4863 feat(verifier): don't spend time sorting input for the fast solver
  kythe/cxx/verifier/verifier.cc
  kythe/cxx/verifier/verifier.h
  kythe/cxx/verifier/verifier_main.cc
Labels: cla: yes

#4864 fix(typescript): prepare for breakage in upcoming 4.2 migration
  kythe/typescript/indexer.ts
Labels: cla: yes

#4865 chore: remove logspam
  kythe/go/serving/xrefs/xrefs.go
Labels: cla: yes

#4866 chore: lazily get the default corpus to quiet inaccurate warnings
  kythe/docs/schema/example-base.sh
  kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
Labels: cla: yes

#4867 fix(go_indexer): fallback to method ownership by pos
  kythe/go/indexer/BUILD
  kythe/go/indexer/indexer.go
  kythe/go/indexer/testdata/dependent.go
  kythe/go/indexer/testdata/go_indexer_test.bzl
  kythe/go/indexer/testdata/types.go
  tools/build_rules/verifier_test/verifier_test.sh.in
Labels: bug, cla: yes, go, indexing

#4869 Don't skip edges in the pipeline.
  kythe/go/serving/pipeline/nodes/nodes.go
  kythe/go/serving/pipeline/nodes/nodes_test.go
Labels: buildbot, cla: yes

#4872 fix(proto): only decorate the relative type name in fields
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
  kythe/cxx/indexer/proto/testdata/basic/extend.proto
  kythe/cxx/indexer/proto/testdata/basic/nested-message-field.proto
  kythe/cxx/indexer/proto/testdata/corner_cases/import_syntax.proto
  kythe/cxx/indexer/proto/testdata/corner_cases/tabs.proto
Labels: cla: yes

#4873 chore: add comment on why split proto type name
  kythe/cxx/indexer/proto/file_descriptor_walker.cc
Labels: cla: yes

#4874 fix(bazel_go_extractor): include .x files in required input
  kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
Labels: cla: yes

#4875 release: v0.0.50
  RELEASES.md
  kythe/release/BUILD
Labels: cla: yes
