Repository kythe/kythe, pull requests merged in 2021-12, with the labels that each got.

#5135 feat(cxx_indexer): add a flag to the C++ indexer to control abs nodes
  kythe/cxx/indexer/cxx/IndexerASTHooks.cc
  kythe/cxx/indexer/cxx/IndexerASTHooks.h
  kythe/cxx/indexer/cxx/IndexerFrontendAction.cc
  kythe/cxx/indexer/cxx/IndexerFrontendAction.h
  kythe/cxx/indexer/cxx/KytheIndexerMain.cc
  kythe/cxx/indexer/cxx/KytheIndexerUnitTest.cc
  tools/build_rules/verifier_test/cc_indexer_test.bzl
Labels: cla: yes

#5136 feat(typescript_indexer): emit tvar and tparam.N
  kythe/typescript/indexer.ts
  kythe/typescript/kythe.ts
  kythe/typescript/testdata/generic_tvar.ts
Labels: cla: yes

#5137 feat: add completedby edge kind enum
  kythe/go/util/schema/indexdata.go
  kythe/proto/schema.proto
  kythe/proto/schema_go_proto/schema.pb.go
Labels: cla: yes

#5140 Update BUILD since $(PLUGIN_OUT) is removed and $(OUT) placeholder replaced.
  kythe/extractors/BUILD
Labels: cla: yes

#5151 feat(go_indexer): tvar/tparam support for generics
  external.bzl
  kythe/go/indexer/BUILD
  kythe/go/indexer/emit.go
  kythe/go/indexer/indexer.go
  kythe/go/indexer/testdata/generics/genericfunc.go
  kythe/go/indexer/testdata/generics/genericinterface.go
  kythe/go/indexer/testdata/generics/genericmethod.go
  kythe/go/indexer/testdata/generics/genericstruct.go
  kythe/go/util/schema/edges/edges.go
  kythe/go/util/schema/nodes/nodes.go
  kythe/release/cloudbuild/go-builder/Dockerfile
  setup.bzl
Labels: go, indexing

#5154 feat(schema): include Go generics examples
  kythe/docs/schema/schema.txt
  tools/build_rules/external_tools/external_tools_configure.bzl
Labels: schema

#5156 feat(go_indexer): support satisfies edges for instance types
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/generics/genericinterface.go
  kythe/go/indexer/testdata/generics/genericmethod.go
Labels: go, indexing

#5157 feat(go_indexer): ensure references are to non-instantiated methods
  kythe/go/indexer/emit.go
  kythe/go/indexer/testdata/generics/genericfunc.go
  kythe/go/indexer/testdata/generics/genericmethod.go
Labels: go, indexing

#5158 feat(go_indexer): emit tapps for instantiated Named types
  kythe/go/indexer/emit.go
  kythe/go/indexer/markedsource.go
  kythe/go/indexer/testdata/generics/genericmethod.go
  kythe/go/indexer/testdata/generics/genericstruct.go
Labels: go, indexing

#5159 feat(go_indexer): add MarkedSource for function type parameters
  kythe/go/indexer/markedsource.go
  kythe/go/indexer/testdata/generics/genericfunc.go
Labels: go, indexing

#5160 feat(go_indexer): add receiver type parameters to MarkedSource
  kythe/go/indexer/markedsource.go
  kythe/go/indexer/testdata/generics/genericmethod.go
Labels: go, indexing

#5163 feat(go_indexer): correct instantiated member references
  kythe/go/indexer/emit.go
  kythe/go/indexer/indexer.go
  kythe/go/indexer/testdata/generics/genericstruct.go
Labels: go, indexing
